/** ***********************************************************************************************
* @class        MainObjectConnectorHydraulicActuatorSimpleParameters
* @brief        Parameter class for MainObjectConnectorHydraulicActuatorSimple
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
* @date         2026-09-15  00:33:14 (last modified)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN
                
************************************************************************************************ */

#ifndef MAINOBJECTCONNECTORHYDRAULICACTUATORSIMPLEPARAMETERS__H
#define MAINOBJECTCONNECTORHYDRAULICACTUATORSIMPLEPARAMETERS__H

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

#include <pybind11/pybind11.h>      //! AUTO: include pybind for dictionary access
#include <pybind11/stl.h>           //! AUTO: needed for stl-casts; otherwise py::cast with std::vector<Real> crashes!!!
namespace py = pybind11;            //! AUTO: "py" used throughout in code
#include "Autogenerated/CObjectConnectorHydraulicActuatorSimple.h"

#include "Autogenerated/VisuObjectConnectorHydraulicActuatorSimple.h"

//! AUTO: Parameters for class MainObjectConnectorHydraulicActuatorSimpleParameters
class MainObjectConnectorHydraulicActuatorSimpleParameters // AUTO: 
{
public: // AUTO: 
};


/** ***********************************************************************************************
* @class        MainObjectConnectorHydraulicActuatorSimple
* @brief        A basic hydraulic actuator with pressure build up equations. The actuator follows a valve input value, which results in a in- or outflow of fluid depending on the pressure difference. Valve values can be prescribed by user functions (not yet available) or with the \texttt{MainSystem} \texttt{PreStepUserFunction(...)}.
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN
                
************************************************************************************************ */

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

//! AUTO: MainObjectConnectorHydraulicActuatorSimple
class MainObjectConnectorHydraulicActuatorSimple: public MainObjectConnector // AUTO: 
{
protected: // AUTO: 
    CObjectConnectorHydraulicActuatorSimple* cObjectConnectorHydraulicActuatorSimple; //pointer to computational object (initialized in object factory) AUTO:
    VisualizationObjectConnectorHydraulicActuatorSimple* visualizationObjectConnectorHydraulicActuatorSimple; //pointer to computational object (initialized in object factory) AUTO:

public: // AUTO: 
    //! AUTO: default constructor with parameter initialization
    MainObjectConnectorHydraulicActuatorSimple()
    {
        name = "";
    };

    // AUTO: access functions
    //! AUTO: Get pointer to computational class
    CObjectConnectorHydraulicActuatorSimple* GetCObjectConnectorHydraulicActuatorSimple() { return cObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Get const pointer to computational class
    const CObjectConnectorHydraulicActuatorSimple* GetCObjectConnectorHydraulicActuatorSimple() const { return cObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Set pointer to computational class (do this only in object factory!!!)
    void SetCObjectConnectorHydraulicActuatorSimple(CObjectConnectorHydraulicActuatorSimple* pCObjectConnectorHydraulicActuatorSimple) { cObjectConnectorHydraulicActuatorSimple = pCObjectConnectorHydraulicActuatorSimple; }

    //! AUTO: Get pointer to visualization class
    VisualizationObjectConnectorHydraulicActuatorSimple* GetVisualizationObjectConnectorHydraulicActuatorSimple() { return visualizationObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Get const pointer to visualization class
    const VisualizationObjectConnectorHydraulicActuatorSimple* GetVisualizationObjectConnectorHydraulicActuatorSimple() const { return visualizationObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Set pointer to visualization class (do this only in object factory!!!)
    void SetVisualizationObjectConnectorHydraulicActuatorSimple(VisualizationObjectConnectorHydraulicActuatorSimple* pVisualizationObjectConnectorHydraulicActuatorSimple) { visualizationObjectConnectorHydraulicActuatorSimple = pVisualizationObjectConnectorHydraulicActuatorSimple; }

    //! AUTO: Get const pointer to computational base class object
    virtual CObject* GetCObject() const { return cObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Set pointer to computational base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetCObject(CObject* pCObject) { cObjectConnectorHydraulicActuatorSimple = (CObjectConnectorHydraulicActuatorSimple*)pCObject; }

    //! AUTO: Get const pointer to visualization base class object
    virtual VisualizationObject* GetVisualizationObject() const { return visualizationObjectConnectorHydraulicActuatorSimple; }
    //! AUTO: Set pointer to visualization base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetVisualizationObject(VisualizationObject* pVisualizationObject) { visualizationObjectConnectorHydraulicActuatorSimple = (VisualizationObjectConnectorHydraulicActuatorSimple*)pVisualizationObject; }

    //! AUTO:  provide requested nodeType for objects; used for automatic checks in CheckSystemIntegrity(); where no exact type can be given, a generic type is used and the check is done in CheckPreAssembleConsistency(...)
    virtual Node::Type GetRequestedNodeType() const override
    {
        return Node::_None;
    }

    //! AUTO:  Check consistency prior to CSystem::Assemble(); needs to find all possible violations such that Assemble() would fail
    virtual bool CheckPreAssembleConsistency(const MainSystem& mainSystem, STDstring& errorString) const override;

    //! AUTO:  Get type name of node (without keyword 'Object'...!); could also be realized via a string -> type conversion?
    virtual const char* GetTypeName() const override
    {
        return "HydraulicActuatorSimple";
    }


    //! AUTO:  dictionary write access
    virtual void SetWithDictionary(const py::dict& d) override
    {
        EPyUtils::ItemIndexFromPython<MarkerIndex>(d["markerNumbers"], cObjectConnectorHydraulicActuatorSimple->GetParameters().markerNumbers); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::ItemIndexFromPython<NodeIndex>(d["nodeNumbers"], cObjectConnectorHydraulicActuatorSimple->GetParameters().nodeNumbers); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["offsetLength"], cObjectConnectorHydraulicActuatorSimple->GetParameters().offsetLength, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.offsetLength"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["strokeLength"], 0., "ObjectConnectorHydraulicActuatorSimple.strokeLength"); EPyUtils::FromPython(d["strokeLength"], cObjectConnectorHydraulicActuatorSimple->GetParameters().strokeLength, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.strokeLength"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["chamberCrossSection0"], 0., "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection0"); EPyUtils::FromPython(d["chamberCrossSection0"], cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection0, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection0"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["chamberCrossSection1"], 0., "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection1"); EPyUtils::FromPython(d["chamberCrossSection1"], cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection1, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection1"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["hoseVolume0"], 0., "ObjectConnectorHydraulicActuatorSimple.hoseVolume0"); EPyUtils::FromPython(d["hoseVolume0"], cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume0, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.hoseVolume0"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["hoseVolume1"], 0., "ObjectConnectorHydraulicActuatorSimple.hoseVolume1"); EPyUtils::FromPython(d["hoseVolume1"], cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume1, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.hoseVolume1"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["valveOpening0"], cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening0, "ObjectConnectorHydraulicActuatorSimple.valveOpening0"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["valveOpening1"], cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening1, "ObjectConnectorHydraulicActuatorSimple.valveOpening1"); /* AUTO:  read out dictionary and cast to C++ type*/
        if (EPyUtils::DictItemExists(d, "actuatorDamping")) { EPyUtils::FromPython(d["actuatorDamping"], cObjectConnectorHydraulicActuatorSimple->GetParameters().actuatorDamping, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.actuatorDamping"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        EPyUtils::RequireGiven(d["oilBulkModulus"], 0., "ObjectConnectorHydraulicActuatorSimple.oilBulkModulus"); EPyUtils::FromPython(d["oilBulkModulus"], cObjectConnectorHydraulicActuatorSimple->GetParameters().oilBulkModulus, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.oilBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["cylinderBulkModulus"], cObjectConnectorHydraulicActuatorSimple->GetParameters().cylinderBulkModulus, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.cylinderBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["hoseBulkModulus"], cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseBulkModulus, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.hoseBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::RequireGiven(d["nominalFlow"], 0., "ObjectConnectorHydraulicActuatorSimple.nominalFlow"); EPyUtils::FromPython(d["nominalFlow"], cObjectConnectorHydraulicActuatorSimple->GetParameters().nominalFlow, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.nominalFlow"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["systemPressure"], cObjectConnectorHydraulicActuatorSimple->GetParameters().systemPressure, "ObjectConnectorHydraulicActuatorSimple.systemPressure"); /* AUTO:  read out dictionary and cast to C++ type*/
        EPyUtils::FromPython(d["tankPressure"], cObjectConnectorHydraulicActuatorSimple->GetParameters().tankPressure, "ObjectConnectorHydraulicActuatorSimple.tankPressure"); /* AUTO:  read out dictionary and cast to C++ type*/
        if (EPyUtils::DictItemExists(d, "useChamberVolumeChange")) { EPyUtils::FromPython(d["useChamberVolumeChange"], cObjectConnectorHydraulicActuatorSimple->GetParameters().useChamberVolumeChange, "ObjectConnectorHydraulicActuatorSimple.useChamberVolumeChange"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "activeConnector")) { EPyUtils::FromPython(d["activeConnector"], cObjectConnectorHydraulicActuatorSimple->GetParameters().activeConnector, "ObjectConnectorHydraulicActuatorSimple.activeConnector"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        EPyUtils::FromPython(d["name"], name); /* AUTO:  read out dictionary and cast to C++ type*/
        if (EPyUtils::DictItemExists(d, "Vshow")) { EPyUtils::FromPython(d["Vshow"], visualizationObjectConnectorHydraulicActuatorSimple->GetShow(), "ObjectConnectorHydraulicActuatorSimple.Vshow"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VcylinderRadius")) { EPyUtils::FromPython(d["VcylinderRadius"], visualizationObjectConnectorHydraulicActuatorSimple->GetCylinderRadius(), "ObjectConnectorHydraulicActuatorSimple.VcylinderRadius"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VrodRadius")) { EPyUtils::FromPython(d["VrodRadius"], visualizationObjectConnectorHydraulicActuatorSimple->GetRodRadius(), "ObjectConnectorHydraulicActuatorSimple.VrodRadius"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VpistonRadius")) { EPyUtils::FromPython(d["VpistonRadius"], visualizationObjectConnectorHydraulicActuatorSimple->GetPistonRadius(), "ObjectConnectorHydraulicActuatorSimple.VpistonRadius"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VpistonLength")) { EPyUtils::FromPython(d["VpistonLength"], visualizationObjectConnectorHydraulicActuatorSimple->GetPistonLength(), "ObjectConnectorHydraulicActuatorSimple.VpistonLength"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VrodMountRadius")) { EPyUtils::FromPython(d["VrodMountRadius"], visualizationObjectConnectorHydraulicActuatorSimple->GetRodMountRadius(), "ObjectConnectorHydraulicActuatorSimple.VrodMountRadius"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VbaseMountRadius")) { EPyUtils::FromPython(d["VbaseMountRadius"], visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountRadius(), "ObjectConnectorHydraulicActuatorSimple.VbaseMountRadius"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VbaseMountLength")) { EPyUtils::FromPython(d["VbaseMountLength"], visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountLength(), "ObjectConnectorHydraulicActuatorSimple.VbaseMountLength"); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VcolorCylinder")) { visualizationObjectConnectorHydraulicActuatorSimple->GetColorCylinder() = py::cast<std::vector<float>>(d["VcolorCylinder"]); /* AUTO:  read out dictionary and cast to C++ type*/} 
        if (EPyUtils::DictItemExists(d, "VcolorPiston")) { visualizationObjectConnectorHydraulicActuatorSimple->GetColorPiston() = py::cast<std::vector<float>>(d["VcolorPiston"]); /* AUTO:  read out dictionary and cast to C++ type*/} 
        GetCObject()->ParametersHaveChanged();
    }

    //! AUTO:  dictionary read access
    virtual py::dict GetDictionary(bool addGraphicsData=false) const override
    {
        auto d = py::dict();
        d["objectType"] = (std::string)GetTypeName();
        d["markerNumbers"] = EPyUtils::ItemIndexToPython<MarkerIndex>(cObjectConnectorHydraulicActuatorSimple->GetParameters().markerNumbers); //! AUTO: cast variables into python (not needed for standard types) 
        d["nodeNumbers"] = EPyUtils::ItemIndexToPython<NodeIndex>(cObjectConnectorHydraulicActuatorSimple->GetParameters().nodeNumbers); //! AUTO: cast variables into python (not needed for standard types) 
        d["offsetLength"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().offsetLength; //! AUTO: cast variables into python (not needed for standard types) 
        d["strokeLength"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().strokeLength; //! AUTO: cast variables into python (not needed for standard types) 
        d["chamberCrossSection0"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection0; //! AUTO: cast variables into python (not needed for standard types) 
        d["chamberCrossSection1"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection1; //! AUTO: cast variables into python (not needed for standard types) 
        d["hoseVolume0"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume0; //! AUTO: cast variables into python (not needed for standard types) 
        d["hoseVolume1"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume1; //! AUTO: cast variables into python (not needed for standard types) 
        d["valveOpening0"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening0; //! AUTO: cast variables into python (not needed for standard types) 
        d["valveOpening1"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening1; //! AUTO: cast variables into python (not needed for standard types) 
        d["actuatorDamping"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().actuatorDamping; //! AUTO: cast variables into python (not needed for standard types) 
        d["oilBulkModulus"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().oilBulkModulus; //! AUTO: cast variables into python (not needed for standard types) 
        d["cylinderBulkModulus"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().cylinderBulkModulus; //! AUTO: cast variables into python (not needed for standard types) 
        d["hoseBulkModulus"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseBulkModulus; //! AUTO: cast variables into python (not needed for standard types) 
        d["nominalFlow"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().nominalFlow; //! AUTO: cast variables into python (not needed for standard types) 
        d["systemPressure"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().systemPressure; //! AUTO: cast variables into python (not needed for standard types) 
        d["tankPressure"] = (Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().tankPressure; //! AUTO: cast variables into python (not needed for standard types) 
        d["useChamberVolumeChange"] = (bool)cObjectConnectorHydraulicActuatorSimple->GetParameters().useChamberVolumeChange; //! AUTO: cast variables into python (not needed for standard types) 
        d["activeConnector"] = (bool)cObjectConnectorHydraulicActuatorSimple->GetParameters().activeConnector; //! AUTO: cast variables into python (not needed for standard types) 
        d["name"] = (std::string)name; //! AUTO: cast variables into python (not needed for standard types) 
        d["Vshow"] = (bool)visualizationObjectConnectorHydraulicActuatorSimple->GetShow(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VcylinderRadius"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetCylinderRadius(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VrodRadius"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetRodRadius(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VpistonRadius"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetPistonRadius(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VpistonLength"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetPistonLength(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VrodMountRadius"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetRodMountRadius(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VbaseMountRadius"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountRadius(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VbaseMountLength"] = (float)visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountLength(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VcolorCylinder"] = (std::vector<float>)visualizationObjectConnectorHydraulicActuatorSimple->GetColorCylinder(); //! AUTO: cast variables into python (not needed for standard types) 
        d["VcolorPiston"] = (std::vector<float>)visualizationObjectConnectorHydraulicActuatorSimple->GetColorPiston(); //! AUTO: cast variables into python (not needed for standard types) 
        return d; 
    }

    //! AUTO:  parameter read access
    virtual py::object GetParameter(const STDstring& parameterName) const override 
    {
        if (parameterName.compare("name") == 0) { return py::cast((std::string)name);} //! AUTO: get parameter
        else if (parameterName.compare("markerNumbers") == 0) { return py::cast(EPyUtils::ItemIndexToPython<MarkerIndex>(cObjectConnectorHydraulicActuatorSimple->GetParameters().markerNumbers));} //! AUTO: get parameter
        else if (parameterName.compare("nodeNumbers") == 0) { return py::cast(EPyUtils::ItemIndexToPython<NodeIndex>(cObjectConnectorHydraulicActuatorSimple->GetParameters().nodeNumbers));} //! AUTO: get parameter
        else if (parameterName.compare("offsetLength") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().offsetLength);} //! AUTO: get parameter
        else if (parameterName.compare("strokeLength") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().strokeLength);} //! AUTO: get parameter
        else if (parameterName.compare("chamberCrossSection0") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection0);} //! AUTO: get parameter
        else if (parameterName.compare("chamberCrossSection1") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection1);} //! AUTO: get parameter
        else if (parameterName.compare("hoseVolume0") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume0);} //! AUTO: get parameter
        else if (parameterName.compare("hoseVolume1") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume1);} //! AUTO: get parameter
        else if (parameterName.compare("valveOpening0") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening0);} //! AUTO: get parameter
        else if (parameterName.compare("valveOpening1") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening1);} //! AUTO: get parameter
        else if (parameterName.compare("actuatorDamping") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().actuatorDamping);} //! AUTO: get parameter
        else if (parameterName.compare("oilBulkModulus") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().oilBulkModulus);} //! AUTO: get parameter
        else if (parameterName.compare("cylinderBulkModulus") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().cylinderBulkModulus);} //! AUTO: get parameter
        else if (parameterName.compare("hoseBulkModulus") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseBulkModulus);} //! AUTO: get parameter
        else if (parameterName.compare("nominalFlow") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().nominalFlow);} //! AUTO: get parameter
        else if (parameterName.compare("systemPressure") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().systemPressure);} //! AUTO: get parameter
        else if (parameterName.compare("tankPressure") == 0) { return py::cast((Real)cObjectConnectorHydraulicActuatorSimple->GetParameters().tankPressure);} //! AUTO: get parameter
        else if (parameterName.compare("useChamberVolumeChange") == 0) { return py::cast((bool)cObjectConnectorHydraulicActuatorSimple->GetParameters().useChamberVolumeChange);} //! AUTO: get parameter
        else if (parameterName.compare("activeConnector") == 0) { return py::cast((bool)cObjectConnectorHydraulicActuatorSimple->GetParameters().activeConnector);} //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { return py::cast((bool)visualizationObjectConnectorHydraulicActuatorSimple->GetShow());} //! AUTO: get parameter
        else if (parameterName.compare("VcylinderRadius") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetCylinderRadius());} //! AUTO: get parameter
        else if (parameterName.compare("VrodRadius") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetRodRadius());} //! AUTO: get parameter
        else if (parameterName.compare("VpistonRadius") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetPistonRadius());} //! AUTO: get parameter
        else if (parameterName.compare("VpistonLength") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetPistonLength());} //! AUTO: get parameter
        else if (parameterName.compare("VrodMountRadius") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetRodMountRadius());} //! AUTO: get parameter
        else if (parameterName.compare("VbaseMountRadius") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountRadius());} //! AUTO: get parameter
        else if (parameterName.compare("VbaseMountLength") == 0) { return py::cast((float)visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountLength());} //! AUTO: get parameter
        else if (parameterName.compare("VcolorCylinder") == 0) { return py::cast((std::vector<float>)visualizationObjectConnectorHydraulicActuatorSimple->GetColorCylinder());} //! AUTO: get parameter
        else if (parameterName.compare("VcolorPiston") == 0) { return py::cast((std::vector<float>)visualizationObjectConnectorHydraulicActuatorSimple->GetColorPiston());} //! AUTO: get parameter
        else  {PyError(STDstring("ObjectConnectorHydraulicActuatorSimple::GetParameter(...): illegal parameter name ")+parameterName+" cannot be read");} // AUTO: add warning for user
        return py::object();
    }


    //! AUTO:  parameter write access
    virtual void SetParameter(const STDstring& parameterName, const py::object& value) override 
    {
        if (parameterName.compare("name") == 0) { EPyUtils::FromPython(value, name); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("markerNumbers") == 0) { EPyUtils::ItemIndexFromPython<MarkerIndex>(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().markerNumbers); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("nodeNumbers") == 0) { EPyUtils::ItemIndexFromPython<NodeIndex>(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().nodeNumbers); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("offsetLength") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().offsetLength, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.offsetLength"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("strokeLength") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().strokeLength, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.strokeLength"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("chamberCrossSection0") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection0, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection0"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("chamberCrossSection1") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().chamberCrossSection1, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.chamberCrossSection1"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("hoseVolume0") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume0, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.hoseVolume0"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("hoseVolume1") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseVolume1, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.hoseVolume1"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("valveOpening0") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening0, "ObjectConnectorHydraulicActuatorSimple.valveOpening0"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("valveOpening1") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().valveOpening1, "ObjectConnectorHydraulicActuatorSimple.valveOpening1"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("actuatorDamping") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().actuatorDamping, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.actuatorDamping"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("oilBulkModulus") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().oilBulkModulus, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.oilBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("cylinderBulkModulus") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().cylinderBulkModulus, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.cylinderBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("hoseBulkModulus") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().hoseBulkModulus, EPyUtils::RangeCheck::nonNegative, "ObjectConnectorHydraulicActuatorSimple.hoseBulkModulus"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("nominalFlow") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().nominalFlow, EPyUtils::RangeCheck::positive, "ObjectConnectorHydraulicActuatorSimple.nominalFlow"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("systemPressure") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().systemPressure, "ObjectConnectorHydraulicActuatorSimple.systemPressure"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("tankPressure") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().tankPressure, "ObjectConnectorHydraulicActuatorSimple.tankPressure"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("useChamberVolumeChange") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().useChamberVolumeChange, "ObjectConnectorHydraulicActuatorSimple.useChamberVolumeChange"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("activeConnector") == 0) { EPyUtils::FromPython(value, cObjectConnectorHydraulicActuatorSimple->GetParameters().activeConnector, "ObjectConnectorHydraulicActuatorSimple.activeConnector"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetShow(), "ObjectConnectorHydraulicActuatorSimple.Vshow"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VcylinderRadius") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetCylinderRadius(), "ObjectConnectorHydraulicActuatorSimple.VcylinderRadius"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VrodRadius") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetRodRadius(), "ObjectConnectorHydraulicActuatorSimple.VrodRadius"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VpistonRadius") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetPistonRadius(), "ObjectConnectorHydraulicActuatorSimple.VpistonRadius"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VpistonLength") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetPistonLength(), "ObjectConnectorHydraulicActuatorSimple.VpistonLength"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VrodMountRadius") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetRodMountRadius(), "ObjectConnectorHydraulicActuatorSimple.VrodMountRadius"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VbaseMountRadius") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountRadius(), "ObjectConnectorHydraulicActuatorSimple.VbaseMountRadius"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VbaseMountLength") == 0) { EPyUtils::FromPython(value, visualizationObjectConnectorHydraulicActuatorSimple->GetBaseMountLength(), "ObjectConnectorHydraulicActuatorSimple.VbaseMountLength"); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VcolorCylinder") == 0) { visualizationObjectConnectorHydraulicActuatorSimple->GetColorCylinder() = py::cast<std::vector<float>>(value); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else if (parameterName.compare("VcolorPiston") == 0) { visualizationObjectConnectorHydraulicActuatorSimple->GetColorPiston() = py::cast<std::vector<float>>(value); /* AUTO:  read out dictionary and cast to C++ type*/; } //! AUTO: get parameter
        else  {PyError(STDstring("ObjectConnectorHydraulicActuatorSimple::SetParameter(...): illegal parameter name ")+parameterName+" cannot be modified");} // AUTO: add warning for user
        GetCObject()->ParametersHaveChanged();
    }

};



#endif //#ifdef include once...
