/** ***********************************************************************************************
* @class        MainMarkerBodyMassParameters
* @brief        Parameter class for MainMarkerBodyMass
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
* @date         2026-09-15  11:13:32 (last modified)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#ifndef MAINMARKERBODYMASSPARAMETERS__H
#define MAINMARKERBODYMASSPARAMETERS__H

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

#include <pybind11/pybind11.h>      //! AUTO: include pybind for dictionary access
#include <pybind11/stl.h>           //! AUTO: needed for stl-casts; otherwise py::cast with std::vector<Real> crashes!!!
namespace py = pybind11;            //! AUTO: "py" used throughout in code
#include "Autogenerated/CMarkerBodyMass.h"

#include "Autogenerated/VisuMarkerBodyMass.h"

//! AUTO: Parameters for class MainMarkerBodyMassParameters
class MainMarkerBodyMassParameters // AUTO:
{
public: // AUTO:
};


/** ***********************************************************************************************
* @class        MainMarkerBodyMass
* @brief        A marker attached to the body mass; use this marker to apply a body-load (e.g. gravitational force).
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

//! AUTO: MainMarkerBodyMass
class MainMarkerBodyMass: public MainMarker // AUTO:
{
protected: // AUTO:
    CMarkerBodyMass* cMarkerBodyMass; //!< AUTO: pointer to computational object (initialized in object factory)
    VisualizationMarkerBodyMass* visualizationMarkerBodyMass; //!< AUTO: pointer to visualization object (initialized in object factory)

public: // AUTO:
    //! AUTO: default constructor with parameter initialization
    MainMarkerBodyMass()
    {
        name = "";
    };

    // AUTO: access functions
    //! AUTO: Get pointer to computational class
    CMarkerBodyMass* GetCMarkerBodyMass() { return cMarkerBodyMass; }
    //! AUTO: Get const pointer to computational class
    const CMarkerBodyMass* GetCMarkerBodyMass() const { return cMarkerBodyMass; }
    //! AUTO: Set pointer to computational class (do this only in object factory!!!)
    void SetCMarkerBodyMass(CMarkerBodyMass* pCMarkerBodyMass) { cMarkerBodyMass = pCMarkerBodyMass; }

    //! AUTO: Get pointer to visualization class
    VisualizationMarkerBodyMass* GetVisualizationMarkerBodyMass() { return visualizationMarkerBodyMass; }
    //! AUTO: Get const pointer to visualization class
    const VisualizationMarkerBodyMass* GetVisualizationMarkerBodyMass() const { return visualizationMarkerBodyMass; }
    //! AUTO: Set pointer to visualization class (do this only in object factory!!!)
    void SetVisualizationMarkerBodyMass(VisualizationMarkerBodyMass* pVisualizationMarkerBodyMass) { visualizationMarkerBodyMass = pVisualizationMarkerBodyMass; }

    //! AUTO: Get const pointer to computational base class object
    virtual CMarker* GetCMarker() const { return cMarkerBodyMass; }
    //! AUTO: Set pointer to computational base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetCMarker(CMarker* pCMarker) { cMarkerBodyMass = (CMarkerBodyMass*)pCMarker; }

    //! AUTO: Get const pointer to visualization base class object
    virtual VisualizationMarker* GetVisualizationMarker() const { return visualizationMarkerBodyMass; }
    //! AUTO: Set pointer to visualization base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetVisualizationMarker(VisualizationMarker* pVisualizationMarker) { visualizationMarkerBodyMass = (VisualizationMarkerBodyMass*)pVisualizationMarker; }

    //! AUTO:  Get type name of marker (without keyword 'Marker'...!); could also be realized via a string -> type conversion?
    virtual const char* GetTypeName() const override
    {
        return "BodyMass";
    }


    //! AUTO:  dictionary write access
    virtual void SetWithDictionary(const py::dict& d) override
    {
        EPyUtils::ItemIndexFromPython<ObjectIndex>(d["bodyNumber"], cMarkerBodyMass->GetParameters().bodyNumber);
        EPyUtils::FromPython(d["name"], name);
        if (EPyUtils::DictItemExists(d, "Vshow")) { EPyUtils::FromPython(d["Vshow"], visualizationMarkerBodyMass->GetShow(), "MarkerBodyMass.Vshow"); }
    }

    //! AUTO:  dictionary read access
    virtual py::dict GetDictionary() const override
    {
        auto d = py::dict();
        d["markerType"] = (std::string)GetTypeName();
        d["bodyNumber"] = (ObjectIndex)cMarkerBodyMass->GetParameters().bodyNumber;
        d["name"] = (std::string)name;
        d["Vshow"] = (bool)visualizationMarkerBodyMass->GetShow();
        return d;
    }

    //! AUTO:  parameter read access
    virtual py::object GetParameter(const STDstring& parameterName) const override
    {
        if (parameterName.compare("name") == 0) { return py::cast((std::string)name); } //! AUTO: get parameter
        else if (parameterName.compare("bodyNumber") == 0) { return py::cast((ObjectIndex)cMarkerBodyMass->GetParameters().bodyNumber); } //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { return py::cast((bool)visualizationMarkerBodyMass->GetShow()); } //! AUTO: get parameter
        else {PyError(STDstring("MarkerBodyMass::GetParameter(...): illegal parameter name ")+parameterName+" cannot be read");} // AUTO: add warning for user
        return py::object();
    }


    //! AUTO:  parameter write access
    virtual void SetParameter(const STDstring& parameterName, const py::object& value) override
    {
        if (parameterName.compare("name") == 0) { EPyUtils::FromPython(value, name); } //! AUTO: set parameter
        else if (parameterName.compare("bodyNumber") == 0) { EPyUtils::ItemIndexFromPython<ObjectIndex>(value, cMarkerBodyMass->GetParameters().bodyNumber); } //! AUTO: set parameter
        else if (parameterName.compare("Vshow") == 0) { EPyUtils::FromPython(value, visualizationMarkerBodyMass->GetShow(), "MarkerBodyMass.Vshow"); } //! AUTO: set parameter
        else {PyError(STDstring("MarkerBodyMass::SetParameter(...): illegal parameter name ")+parameterName+" cannot be modified");} // AUTO: add warning for user
    }

};



#endif //#ifdef include once...
