// AUTO:  ++++++++++++++++++++++
// AUTO:  version info automatically generated by tracker; generated by Johannes Gerstmayr
// AUTO:  last modified = 2026-10-01
// AUTO:  ++++++++++++++++++++++
namespace EXUstd {
 const char* exudynVersion = "1.12.202.dev1";
}
