/** ***********************************************************************************************
* @class        MainObjectRigidBody2DParameters
* @brief        Parameter class for MainObjectRigidBody2D
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
* @date         2026-09-15  21:59:30 (last modified)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#ifndef MAINOBJECTRIGIDBODY2DPARAMETERS__H
#define MAINOBJECTRIGIDBODY2DPARAMETERS__H

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

#include <pybind11/pybind11.h>      //! AUTO: include pybind for dictionary access
#include <pybind11/stl.h>           //! AUTO: needed for stl-casts; otherwise py::cast with std::vector<Real> crashes!!!
namespace py = pybind11;            //! AUTO: "py" used throughout in code
#include <pybind11/functional.h> //! AUTO: for function handling ... otherwise gives a python error (no compilation error in C++ !)
#include "Autogenerated/objects/CObjectRigidBody2D.h"

#include "Autogenerated/objects/VisuObjectRigidBody2D.h"

//! AUTO: Parameters for class MainObjectRigidBody2DParameters
class MainObjectRigidBody2DParameters // AUTO:
{
public: // AUTO:
};


/** ***********************************************************************************************
* @class        MainObjectRigidBody2D
* @brief        A 2D rigid body which is attached to a rigid body 2D node. The body obtains coordinates, position, velocity, etc. from the underlying 2D node.
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

//! AUTO: MainObjectRigidBody2D
class MainObjectRigidBody2D: public MainObjectBody // AUTO:
{
protected: // AUTO:
    CObjectRigidBody2D* cObjectRigidBody2D; //!< AUTO: pointer to computational object (initialized in object factory)
    VisualizationObjectRigidBody2D* visualizationObjectRigidBody2D; //!< AUTO: pointer to visualization object (initialized in object factory)

public: // AUTO:
    //! AUTO: default constructor with parameter initialization
    MainObjectRigidBody2D()
    {
        name = "";
    };

    // AUTO: access functions
    //! AUTO: Get pointer to computational class
    CObjectRigidBody2D* GetCObjectRigidBody2D() { return cObjectRigidBody2D; }
    //! AUTO: Get const pointer to computational class
    const CObjectRigidBody2D* GetCObjectRigidBody2D() const { return cObjectRigidBody2D; }
    //! AUTO: Set pointer to computational class (do this only in object factory!!!)
    void SetCObjectRigidBody2D(CObjectRigidBody2D* pCObjectRigidBody2D) { cObjectRigidBody2D = pCObjectRigidBody2D; }

    //! AUTO: Get pointer to visualization class
    VisualizationObjectRigidBody2D* GetVisualizationObjectRigidBody2D() { return visualizationObjectRigidBody2D; }
    //! AUTO: Get const pointer to visualization class
    const VisualizationObjectRigidBody2D* GetVisualizationObjectRigidBody2D() const { return visualizationObjectRigidBody2D; }
    //! AUTO: Set pointer to visualization class (do this only in object factory!!!)
    void SetVisualizationObjectRigidBody2D(VisualizationObjectRigidBody2D* pVisualizationObjectRigidBody2D) { visualizationObjectRigidBody2D = pVisualizationObjectRigidBody2D; }

    //! AUTO: Get const pointer to computational base class object
    virtual CObject* GetCObject() const { return cObjectRigidBody2D; }
    //! AUTO: Set pointer to computational base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetCObject(CObject* pCObject) { cObjectRigidBody2D = (CObjectRigidBody2D*)pCObject; }

    //! AUTO: Get const pointer to visualization base class object
    virtual VisualizationObject* GetVisualizationObject() const { return visualizationObjectRigidBody2D; }
    //! AUTO: Set pointer to visualization base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetVisualizationObject(VisualizationObject* pVisualizationObject) { visualizationObjectRigidBody2D = (VisualizationObjectRigidBody2D*)pVisualizationObject; }

    //! AUTO:  Get type name of object; could also be realized via a string -> type conversion?
    virtual const char* GetTypeName() const override
    {
        return "RigidBody2D";
    }

    //! AUTO:  provide requested nodeType for objects; used for automatic checks in CheckSystemIntegrity(); where no exact type can be given, a generic type is used and the check is done in CheckPreAssembleConsistency(...)
    virtual Node::Type GetRequestedNodeType() const override
    {
        return (Node::Type)((Index)Node::Position2D + (Index)Node::Orientation2D);
    }


    //! AUTO:  dictionary write access
    virtual void SetWithDictionary(const py::dict& d) override
    {
        if (EPyUtils::DictItemExists(d, "physicsMass")) { EPyUtils::FromPython(d["physicsMass"], cObjectRigidBody2D->GetParameters().physicsMass, EPyUtils::RangeCheck::nonNegative, "ObjectRigidBody2D.physicsMass"); }
        if (EPyUtils::DictItemExists(d, "physicsInertia")) { EPyUtils::FromPython(d["physicsInertia"], cObjectRigidBody2D->GetParameters().physicsInertia, EPyUtils::RangeCheck::nonNegative, "ObjectRigidBody2D.physicsInertia"); }
        if (EPyUtils::DictItemExists(d, "physicsCenterOfMass")) { EPyUtils::FromPython(d["physicsCenterOfMass"], cObjectRigidBody2D->GetParameters().physicsCenterOfMass); }
        if (EPyUtils::DictItemExists(d, "nodeNumber")) { EPyUtils::ItemIndexFromPython<NodeIndex>(d["nodeNumber"], cObjectRigidBody2D->GetParameters().nodeNumber); }
        if (EPyUtils::DictItemExists(d, "name")) { EPyUtils::FromPython(d["name"], name); }
        if (EPyUtils::DictItemExists(d, "Vshow")) { EPyUtils::FromPython(d["Vshow"], visualizationObjectRigidBody2D->GetShow(), "ObjectRigidBody2D.Vshow"); }
        if (EPyUtils::DictItemExists(d, "VgraphicsDataUserFunction")) { visualizationObjectRigidBody2D->GetGraphicsDataUserFunction() = d["VgraphicsDataUserFunction"]; }
        if (EPyUtils::DictItemExists(d, "VgraphicsData")) { PyWriteBodyGraphicsDataList(d, "VgraphicsData", visualizationObjectRigidBody2D->GetGraphicsData()); }
        GetCObject()->ParametersHaveChanged();
    }

    //! AUTO:  dictionary read access
    virtual py::dict GetDictionary(bool addGraphicsData=false) const override
    {
        auto d = py::dict();
        d["objectType"] = (std::string)GetTypeName();
        d["physicsMass"] = (Real)cObjectRigidBody2D->GetParameters().physicsMass;
        d["physicsInertia"] = (Real)cObjectRigidBody2D->GetParameters().physicsInertia;
        d["physicsCenterOfMass"] = EPyUtils::ToPython(cObjectRigidBody2D->GetParameters().physicsCenterOfMass);
        d["nodeNumber"] = (NodeIndex)cObjectRigidBody2D->GetParameters().nodeNumber;
        d["name"] = (std::string)name;
        d["Vshow"] = (bool)visualizationObjectRigidBody2D->GetShow();
        d["VgraphicsDataUserFunction"] = (py::object)visualizationObjectRigidBody2D->GetGraphicsDataUserFunction();
        d["VgraphicsData"] = PyGetBodyGraphicsDataList(visualizationObjectRigidBody2D->GetGraphicsData(), addGraphicsData);
        return d;
    }

    //! AUTO:  parameter read access
    virtual py::object GetParameter(const STDstring& parameterName) const override
    {
        if (parameterName.compare("name") == 0) { return py::cast((std::string)name); } //! AUTO: get parameter
        else if (parameterName.compare("physicsMass") == 0) { return py::cast((Real)cObjectRigidBody2D->GetParameters().physicsMass); } //! AUTO: get parameter
        else if (parameterName.compare("physicsInertia") == 0) { return py::cast((Real)cObjectRigidBody2D->GetParameters().physicsInertia); } //! AUTO: get parameter
        else if (parameterName.compare("physicsCenterOfMass") == 0) { return EPyUtils::ToPython(cObjectRigidBody2D->GetParameters().physicsCenterOfMass); } //! AUTO: get parameter
        else if (parameterName.compare("nodeNumber") == 0) { return py::cast((NodeIndex)cObjectRigidBody2D->GetParameters().nodeNumber); } //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { return py::cast((bool)visualizationObjectRigidBody2D->GetShow()); } //! AUTO: get parameter
        else if (parameterName.compare("VgraphicsDataUserFunction") == 0) { return visualizationObjectRigidBody2D->GetGraphicsDataUserFunction().GetPythonDictionary(); } //! AUTO: get parameter
        else if (parameterName.compare("VgraphicsData") == 0) { return PyGetBodyGraphicsDataList(visualizationObjectRigidBody2D->GetGraphicsData(), true); } //! AUTO: get parameter
        else {PyError(STDstring("ObjectRigidBody2D::GetParameter(...): illegal parameter name ")+parameterName+" cannot be read");} // AUTO: add warning for user
        return py::object();
    }


    //! AUTO:  parameter write access
    virtual void SetParameter(const STDstring& parameterName, const py::object& value) override
    {
        if (parameterName.compare("name") == 0) { EPyUtils::FromPython(value, name); } //! AUTO: set parameter
        else if (parameterName.compare("physicsMass") == 0) { EPyUtils::FromPython(value, cObjectRigidBody2D->GetParameters().physicsMass, EPyUtils::RangeCheck::nonNegative, "ObjectRigidBody2D.physicsMass"); } //! AUTO: set parameter
        else if (parameterName.compare("physicsInertia") == 0) { EPyUtils::FromPython(value, cObjectRigidBody2D->GetParameters().physicsInertia, EPyUtils::RangeCheck::nonNegative, "ObjectRigidBody2D.physicsInertia"); } //! AUTO: set parameter
        else if (parameterName.compare("physicsCenterOfMass") == 0) { EPyUtils::FromPython(value, cObjectRigidBody2D->GetParameters().physicsCenterOfMass); } //! AUTO: set parameter
        else if (parameterName.compare("nodeNumber") == 0) { EPyUtils::ItemIndexFromPython<NodeIndex>(value, cObjectRigidBody2D->GetParameters().nodeNumber); } //! AUTO: set parameter
        else if (parameterName.compare("Vshow") == 0) { EPyUtils::FromPython(value, visualizationObjectRigidBody2D->GetShow(), "ObjectRigidBody2D.Vshow"); } //! AUTO: set parameter
        else if (parameterName.compare("VgraphicsDataUserFunction") == 0) { visualizationObjectRigidBody2D->GetGraphicsDataUserFunction() = value; } //! AUTO: set parameter
        else if (parameterName.compare("VgraphicsData") == 0) { PyWriteBodyGraphicsDataList(value, visualizationObjectRigidBody2D->GetGraphicsData()); } //! AUTO: set parameter
        else {PyError(STDstring("ObjectRigidBody2D::SetParameter(...): illegal parameter name ")+parameterName+" cannot be modified");} // AUTO: add warning for user
        GetCObject()->ParametersHaveChanged();
    }

};



#endif //#ifdef include once...
