/** ***********************************************************************************************
* @class        MainObjectBeamGeometricallyExactParameters
* @brief        Parameter class for MainObjectBeamGeometricallyExact
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
* @date         2026-09-18  21:48:31 (last modified)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#ifndef MAINOBJECTBEAMGEOMETRICALLYEXACTPARAMETERS__H
#define MAINOBJECTBEAMGEOMETRICALLYEXACTPARAMETERS__H

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

#include <pybind11/pybind11.h>      //! AUTO: include pybind for dictionary access
#include <pybind11/stl.h>           //! AUTO: needed for stl-casts; otherwise py::cast with std::vector<Real> crashes!!!
namespace py = pybind11;            //! AUTO: "py" used throughout in code
#include "Autogenerated/objects/CObjectBeamGeometricallyExact.h"

#include "Autogenerated/objects/VisuObjectBeamGeometricallyExact.h"
#include "Autogenerated/PyStructuralElementsDataStructures.h"

//! AUTO: Parameters for class MainObjectBeamGeometricallyExactParameters
class MainObjectBeamGeometricallyExactParameters // AUTO:
{
public: // AUTO:
};


/** ***********************************************************************************************
* @class        MainObjectBeamGeometricallyExact
* @brief        A 3D geometrically exact beam finite element, currently using two 3D rigid body nodes. The localPosition \f$x\f$ of the beam ranges from \f$-L/2\f$ (at node 0) to \f$L/2\f$ (at node 1). The axial coordinate is \f$x\f$ (first coordinate) and the cross section is spanned by local \f$y\f$/\f$z\f$ axes. NOTE: Requires further development and tests!
*
* @author       Gerstmayr Johannes
* @date         2019-07-01 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

//! AUTO: MainObjectBeamGeometricallyExact
class MainObjectBeamGeometricallyExact: public MainObjectBody // AUTO:
{
protected: // AUTO:
    CObjectBeamGeometricallyExact* cObjectBeamGeometricallyExact; //!< AUTO: pointer to computational object (initialized in object factory)
    VisualizationObjectBeamGeometricallyExact* visualizationObjectBeamGeometricallyExact; //!< AUTO: pointer to visualization object (initialized in object factory)

public: // AUTO:
    //! AUTO: default constructor with parameter initialization
    MainObjectBeamGeometricallyExact()
    {
        name = "";
    };

    // AUTO: access functions
    //! AUTO: Get pointer to computational class
    CObjectBeamGeometricallyExact* GetCObjectBeamGeometricallyExact() { return cObjectBeamGeometricallyExact; }
    //! AUTO: Get const pointer to computational class
    const CObjectBeamGeometricallyExact* GetCObjectBeamGeometricallyExact() const { return cObjectBeamGeometricallyExact; }
    //! AUTO: Set pointer to computational class (do this only in object factory!!!)
    void SetCObjectBeamGeometricallyExact(CObjectBeamGeometricallyExact* pCObjectBeamGeometricallyExact) { cObjectBeamGeometricallyExact = pCObjectBeamGeometricallyExact; }

    //! AUTO: Get pointer to visualization class
    VisualizationObjectBeamGeometricallyExact* GetVisualizationObjectBeamGeometricallyExact() { return visualizationObjectBeamGeometricallyExact; }
    //! AUTO: Get const pointer to visualization class
    const VisualizationObjectBeamGeometricallyExact* GetVisualizationObjectBeamGeometricallyExact() const { return visualizationObjectBeamGeometricallyExact; }
    //! AUTO: Set pointer to visualization class (do this only in object factory!!!)
    void SetVisualizationObjectBeamGeometricallyExact(VisualizationObjectBeamGeometricallyExact* pVisualizationObjectBeamGeometricallyExact) { visualizationObjectBeamGeometricallyExact = pVisualizationObjectBeamGeometricallyExact; }

    //! AUTO: Get const pointer to computational base class object
    virtual CObject* GetCObject() const { return cObjectBeamGeometricallyExact; }
    //! AUTO: Set pointer to computational base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetCObject(CObject* pCObject) { cObjectBeamGeometricallyExact = (CObjectBeamGeometricallyExact*)pCObject; }

    //! AUTO: Get const pointer to visualization base class object
    virtual VisualizationObject* GetVisualizationObject() const { return visualizationObjectBeamGeometricallyExact; }
    //! AUTO: Set pointer to visualization base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetVisualizationObject(VisualizationObject* pVisualizationObject) { visualizationObjectBeamGeometricallyExact = (VisualizationObjectBeamGeometricallyExact*)pVisualizationObject; }

    void SetInternalBeamSection(const py::object& pyObject); //! AUTO: special function which writes pyObject into local data
    PyBeamSection GetInternalBeamSection() const; //! AUTO: special function which returns BeamSection converted from local data
    //! AUTO:  Get type name of object; could also be realized via a string -> type conversion?
    virtual const char* GetTypeName() const override
    {
        return "BeamGeometricallyExact3D";
    }

    //! AUTO:  provide requested nodeType for objects; used for automatic checks in CheckSystemIntegrity(); where no exact type can be given, a generic type is used and the check is done in CheckPreAssembleConsistency(...)
    virtual Node::Type GetRequestedNodeType() const override
    {
        return (Node::Type)((Index)Node::Position + (Index)Node::Orientation);
    }


    //! AUTO:  dictionary write access
    virtual void SetWithDictionary(const py::dict& d) override
    {
        if (EPyUtils::DictItemExists(d, "nodeNumbers")) { EPyUtils::ItemIndexFromPython<NodeIndex>(d["nodeNumbers"], cObjectBeamGeometricallyExact->GetParameters().nodeNumbers); }
        if (EPyUtils::DictItemExists(d, "physicsLength")) { EPyUtils::RequireGiven(d["physicsLength"], 0., "ObjectBeamGeometricallyExact.physicsLength"); EPyUtils::FromPython(d["physicsLength"], cObjectBeamGeometricallyExact->GetParameters().physicsLength, EPyUtils::RangeCheck::positive, "ObjectBeamGeometricallyExact.physicsLength"); } else { EPyUtils::RequireGiven(py::cast(cObjectBeamGeometricallyExact->GetParameters().physicsLength), 0., "ObjectBeamGeometricallyExact.physicsLength"); }
        if (EPyUtils::DictItemExists(d, "name")) { EPyUtils::FromPython(d["name"], name); }
        if (EPyUtils::DictItemExists(d, "sectionData")) { SetInternalBeamSection(d["sectionData"]); }
        if (EPyUtils::DictItemExists(d, "Vshow")) { EPyUtils::FromPython(d["Vshow"], visualizationObjectBeamGeometricallyExact->GetShow(), "ObjectBeamGeometricallyExact.Vshow"); }
        if (EPyUtils::DictItemExists(d, "VsectionGeometry")) { visualizationObjectBeamGeometricallyExact->GetSectionGeometry() = py::cast<BeamSectionGeometry>(d["VsectionGeometry"]); }
        if (EPyUtils::DictItemExists(d, "Vcolor")) { EPyUtils::FromPython(d["Vcolor"], visualizationObjectBeamGeometricallyExact->GetColor(), "ObjectBeamGeometricallyExact.Vcolor"); }
        GetCObject()->ParametersHaveChanged();
    }

    //! AUTO:  dictionary read access
    virtual py::dict GetDictionary(bool addGraphicsData=false) const override
    {
        auto d = py::dict();
        d["objectType"] = (std::string)GetTypeName();
        d["nodeNumbers"] = EPyUtils::ItemIndexToPython<NodeIndex>((ArrayIndex)cObjectBeamGeometricallyExact->GetParameters().nodeNumbers);
        d["physicsLength"] = (Real)cObjectBeamGeometricallyExact->GetParameters().physicsLength;
        d["name"] = (std::string)name;
        d["sectionData"] = GetInternalBeamSection();
        d["Vshow"] = (bool)visualizationObjectBeamGeometricallyExact->GetShow();
        d["VsectionGeometry"] = (BeamSectionGeometry)visualizationObjectBeamGeometricallyExact->GetSectionGeometry();
        d["Vcolor"] = EPyUtils::ToPythonMember(visualizationObjectBeamGeometricallyExact->GetColor());
        return d;
    }

    //! AUTO:  parameter read access
    virtual py::object GetParameter(const STDstring& parameterName) const override
    {
        if (parameterName.compare("name") == 0) { return py::cast((std::string)name); } //! AUTO: get parameter
        else if (parameterName.compare("nodeNumbers") == 0) { return py::cast(EPyUtils::ItemIndexToPython<NodeIndex>((ArrayIndex)cObjectBeamGeometricallyExact->GetParameters().nodeNumbers)); } //! AUTO: get parameter
        else if (parameterName.compare("physicsLength") == 0) { return py::cast((Real)cObjectBeamGeometricallyExact->GetParameters().physicsLength); } //! AUTO: get parameter
        else if (parameterName.compare("sectionData") == 0) { return py::cast(GetInternalBeamSection()); } //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { return py::cast((bool)visualizationObjectBeamGeometricallyExact->GetShow()); } //! AUTO: get parameter
        else if (parameterName.compare("VsectionGeometry") == 0) { return py::cast((BeamSectionGeometry)visualizationObjectBeamGeometricallyExact->GetSectionGeometry()); } //! AUTO: get parameter
        else if (parameterName.compare("Vcolor") == 0) { return py::cast(EPyUtils::ToPythonMember(visualizationObjectBeamGeometricallyExact->GetColor())); } //! AUTO: get parameter
        else {PyError(STDstring("ObjectBeamGeometricallyExact::GetParameter(...): illegal parameter name ")+parameterName+" cannot be read", PyErrorType::valueError);} // AUTO: add warning for user
        return py::object();
    }


    //! AUTO:  parameter write access
    virtual void SetParameter(const STDstring& parameterName, const py::object& value) override
    {
        if (parameterName.compare("name") == 0) { EPyUtils::FromPython(value, name); } //! AUTO: set parameter
        else if (parameterName.compare("nodeNumbers") == 0) { EPyUtils::ItemIndexFromPython<NodeIndex>(value, cObjectBeamGeometricallyExact->GetParameters().nodeNumbers); } //! AUTO: set parameter
        else if (parameterName.compare("physicsLength") == 0) { EPyUtils::FromPython(value, cObjectBeamGeometricallyExact->GetParameters().physicsLength, EPyUtils::RangeCheck::positive, "ObjectBeamGeometricallyExact.physicsLength"); } //! AUTO: set parameter
        else if (parameterName.compare("sectionData") == 0) { SetInternalBeamSection(value); } //! AUTO: set parameter
        else if (parameterName.compare("Vshow") == 0) { EPyUtils::FromPython(value, visualizationObjectBeamGeometricallyExact->GetShow(), "ObjectBeamGeometricallyExact.Vshow"); } //! AUTO: set parameter
        else if (parameterName.compare("VsectionGeometry") == 0) { visualizationObjectBeamGeometricallyExact->GetSectionGeometry() = py::cast<BeamSectionGeometry>(value); } //! AUTO: set parameter
        else if (parameterName.compare("Vcolor") == 0) { EPyUtils::FromPython(value, visualizationObjectBeamGeometricallyExact->GetColor(), "ObjectBeamGeometricallyExact.Vcolor"); } //! AUTO: set parameter
        else {PyError(STDstring("ObjectBeamGeometricallyExact::SetParameter(...): illegal parameter name ")+parameterName+" cannot be modified", PyErrorType::valueError);} // AUTO: add warning for user
        GetCObject()->ParametersHaveChanged();
    }

};



#endif //#ifdef include once...
