/** ***********************************************************************************************
* @class        MainObjectFFRFParameters
* @brief        Parameter class for MainObjectFFRF
*
* @author       Gerstmayr Johannes, Zw\"olfer Andreas
* @date         2019-07-01 (generated)
* @date         2026-09-15  20:53:06 (last modified)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#ifndef MAINOBJECTFFRFPARAMETERS__H
#define MAINOBJECTFFRFPARAMETERS__H

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

#include <pybind11/pybind11.h>      //! AUTO: include pybind for dictionary access
#include <pybind11/stl.h>           //! AUTO: needed for stl-casts; otherwise py::cast with std::vector<Real> crashes!!!
namespace py = pybind11;            //! AUTO: "py" used throughout in code
#include <pybind11/functional.h> //! AUTO: for function handling ... otherwise gives a python error (no compilation error in C++ !)
#include "Autogenerated/objects/CObjectFFRF.h"

#include "Autogenerated/objects/VisuObjectFFRF.h"

//! AUTO: Parameters for class MainObjectFFRFParameters
class MainObjectFFRFParameters // AUTO:
{
public: // AUTO:
};


/** ***********************************************************************************************
* @class        MainObjectFFRF
* @brief        This object is used to represent equations modelled by the \hac{FFRF}. It contains a RigidBodyNode (always node 0) and a list of other nodes representing the finite element nodes used in the \hac{FFRF}. Note that temporary matrices and vectors are subject of change in future. NOTE: Usually you SHOULD NOT USE THIS OBJECT - use the much more efficient ObjectFFRFreducedOrder object with modal reduction instead.
*
* @author       Gerstmayr Johannes, Zw\"olfer Andreas
* @date         2019-07-01 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN

************************************************************************************************ */

#include <ostream>

#include "Utilities/ReleaseAssert.h"
#include "Utilities/BasicDefinitions.h"
#include "System/ItemIndices.h"

//! AUTO: MainObjectFFRF
class MainObjectFFRF: public MainObjectBody // AUTO:
{
protected: // AUTO:
    CObjectFFRF* cObjectFFRF; //!< AUTO: pointer to computational object (initialized in object factory)
    VisualizationObjectFFRF* visualizationObjectFFRF; //!< AUTO: pointer to visualization object (initialized in object factory)

public: // AUTO:
    //! AUTO: default constructor with parameter initialization
    MainObjectFFRF()
    {
        name = "";
    };

    // AUTO: access functions
    //! AUTO: Get pointer to computational class
    CObjectFFRF* GetCObjectFFRF() { return cObjectFFRF; }
    //! AUTO: Get const pointer to computational class
    const CObjectFFRF* GetCObjectFFRF() const { return cObjectFFRF; }
    //! AUTO: Set pointer to computational class (do this only in object factory!!!)
    void SetCObjectFFRF(CObjectFFRF* pCObjectFFRF) { cObjectFFRF = pCObjectFFRF; }

    //! AUTO: Get pointer to visualization class
    VisualizationObjectFFRF* GetVisualizationObjectFFRF() { return visualizationObjectFFRF; }
    //! AUTO: Get const pointer to visualization class
    const VisualizationObjectFFRF* GetVisualizationObjectFFRF() const { return visualizationObjectFFRF; }
    //! AUTO: Set pointer to visualization class (do this only in object factory!!!)
    void SetVisualizationObjectFFRF(VisualizationObjectFFRF* pVisualizationObjectFFRF) { visualizationObjectFFRF = pVisualizationObjectFFRF; }

    //! AUTO: Get const pointer to computational base class object
    virtual CObject* GetCObject() const { return cObjectFFRF; }
    //! AUTO: Set pointer to computational base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetCObject(CObject* pCObject) { cObjectFFRF = (CObjectFFRF*)pCObject; }

    //! AUTO: Get const pointer to visualization base class object
    virtual VisualizationObject* GetVisualizationObject() const { return visualizationObjectFFRF; }
    //! AUTO: Set pointer to visualization base class object (do this only in object factory; type is NOT CHECKED!!!)
    virtual void SetVisualizationObject(VisualizationObject* pVisualizationObject) { visualizationObjectFFRF = (VisualizationObjectFFRF*)pVisualizationObject; }

    //! AUTO:  Get type name of object; could also be realized via a string -> type conversion?
    virtual const char* GetTypeName() const override
    {
        return "FFRF";
    }

    //! AUTO:  provide requested nodeType for objects; used for automatic checks in CheckSystemIntegrity(); where no exact type can be given, a generic type is used and the check is done in CheckPreAssembleConsistency(...)
    virtual Node::Type GetRequestedNodeType() const override
    {
        return Node::_None;
    }

    //! AUTO:  Check consistency prior to CSystem::Assemble(); needs to find all possible violations such that Assemble() would fail
    virtual bool CheckPreAssembleConsistency(const MainSystem& mainSystem, STDstring& errorString) const override;


    //! AUTO:  dictionary write access
    virtual void SetWithDictionary(const py::dict& d) override
    {
        if (EPyUtils::DictItemExists(d, "nodeNumbers")) { EPyUtils::ItemIndexFromPython<NodeIndex>(d["nodeNumbers"], cObjectFFRF->GetParameters().nodeNumbers); }
        if (EPyUtils::DictItemExists(d, "massMatrixFF")) { EPyUtils::SetPyMatrixContainerSafely(d["massMatrixFF"], cObjectFFRF->GetParameters().massMatrixFF); }
        if (EPyUtils::DictItemExists(d, "stiffnessMatrixFF")) { EPyUtils::SetPyMatrixContainerSafely(d["stiffnessMatrixFF"], cObjectFFRF->GetParameters().stiffnessMatrixFF); }
        if (EPyUtils::DictItemExists(d, "dampingMatrixFF")) { EPyUtils::SetPyMatrixContainerSafely(d["dampingMatrixFF"], cObjectFFRF->GetParameters().dampingMatrixFF); }
        if (EPyUtils::DictItemExists(d, "forceVector")) { EPyUtils::FromPython(d["forceVector"], cObjectFFRF->GetParameters().forceVector); }
        if (EPyUtils::DictItemExists(d, "forceUserFunction")) { cObjectFFRF->GetParameters().forceUserFunction = d["forceUserFunction"]; }
        if (EPyUtils::DictItemExists(d, "massMatrixUserFunction")) { cObjectFFRF->GetParameters().massMatrixUserFunction = d["massMatrixUserFunction"]; }
        if (EPyUtils::DictItemExists(d, "computeFFRFterms")) { EPyUtils::FromPython(d["computeFFRFterms"], cObjectFFRF->GetParameters().computeFFRFterms, "ObjectFFRF.computeFFRFterms"); }
        if (EPyUtils::DictItemExists(d, "objectIsInitialized")) { EPyUtils::FromPython(d["objectIsInitialized"], cObjectFFRF->GetObjectIsInitialized(), "ObjectFFRF.objectIsInitialized"); }
        if (EPyUtils::DictItemExists(d, "name")) { EPyUtils::FromPython(d["name"], name); }
        if (EPyUtils::DictItemExists(d, "Vshow")) { EPyUtils::FromPython(d["Vshow"], visualizationObjectFFRF->GetShow(), "ObjectFFRF.Vshow"); }
        if (EPyUtils::DictItemExists(d, "Vcolor")) { EPyUtils::FromPython(d["Vcolor"], visualizationObjectFFRF->GetColor(), "ObjectFFRF.Vcolor"); }
        if (EPyUtils::DictItemExists(d, "VtriangleMesh")) { EPyUtils::FromPython(d["VtriangleMesh"], visualizationObjectFFRF->GetTriangleMesh()); }
        if (EPyUtils::DictItemExists(d, "VshowNodes")) { EPyUtils::FromPython(d["VshowNodes"], visualizationObjectFFRF->GetShowNodes(), "ObjectFFRF.VshowNodes"); }
        GetCObject()->ParametersHaveChanged();
    }

    //! AUTO:  dictionary read access
    virtual py::dict GetDictionary(bool addGraphicsData=false) const override
    {
        auto d = py::dict();
        d["objectType"] = (std::string)GetTypeName();
        d["nodeNumbers"] = EPyUtils::ItemIndexToPython<NodeIndex>(cObjectFFRF->GetParameters().nodeNumbers);
        d["massMatrixFF"] = (PyMatrixContainer)cObjectFFRF->GetParameters().massMatrixFF;
        d["stiffnessMatrixFF"] = (PyMatrixContainer)cObjectFFRF->GetParameters().stiffnessMatrixFF;
        d["dampingMatrixFF"] = (PyMatrixContainer)cObjectFFRF->GetParameters().dampingMatrixFF;
        d["forceVector"] = EPyUtils::ToPython(cObjectFFRF->GetParameters().forceVector);
        d["forceUserFunction"] = (py::object)cObjectFFRF->GetParameters().forceUserFunction;
        d["massMatrixUserFunction"] = (py::object)cObjectFFRF->GetParameters().massMatrixUserFunction;
        d["computeFFRFterms"] = (bool)cObjectFFRF->GetParameters().computeFFRFterms;
        d["coordinateIndexPerNode"] = EPyUtils::ToPythonMember(cObjectFFRF->GetCoordinateIndexPerNode());
        d["objectIsInitialized"] = (bool)cObjectFFRF->GetObjectIsInitialized();
        d["physicsMass"] = (Real)cObjectFFRF->GetPhysicsMass();
        d["physicsInertia"] = EPyUtils::ToPython(cObjectFFRF->GetPhysicsInertia());
        d["physicsCenterOfMass"] = EPyUtils::ToPython(cObjectFFRF->GetPhysicsCenterOfMass());
        d["PHItTM"] = EPyUtils::ToPython(cObjectFFRF->GetPHItTM());
        d["referencePositions"] = EPyUtils::ToPython(cObjectFFRF->GetReferencePositions());
        d["tempVector"] = EPyUtils::ToPython(cObjectFFRF->GetTempVector());
        d["tempCoordinates"] = EPyUtils::ToPython(cObjectFFRF->GetTempCoordinates());
        d["tempCoordinates_t"] = EPyUtils::ToPython(cObjectFFRF->GetTempCoordinates_t());
        d["tempRefPosSkew"] = EPyUtils::ToPython(cObjectFFRF->GetTempRefPosSkew());
        d["tempVelSkew"] = EPyUtils::ToPython(cObjectFFRF->GetTempVelSkew());
        d["name"] = (std::string)name;
        d["Vshow"] = (bool)visualizationObjectFFRF->GetShow();
        d["Vcolor"] = EPyUtils::ToPythonMember(visualizationObjectFFRF->GetColor());
        d["VtriangleMesh"] = EPyUtils::ToPython(visualizationObjectFFRF->GetTriangleMesh());
        d["VshowNodes"] = (bool)visualizationObjectFFRF->GetShowNodes();
        return d;
    }

    //! AUTO:  parameter read access
    virtual py::object GetParameter(const STDstring& parameterName) const override
    {
        if (parameterName.compare("name") == 0) { return py::cast((std::string)name); } //! AUTO: get parameter
        else if (parameterName.compare("nodeNumbers") == 0) { return py::cast(EPyUtils::ItemIndexToPython<NodeIndex>(cObjectFFRF->GetParameters().nodeNumbers)); } //! AUTO: get parameter
        else if (parameterName.compare("massMatrixFF") == 0) { return py::cast((PyMatrixContainer)cObjectFFRF->GetParameters().massMatrixFF); } //! AUTO: get parameter
        else if (parameterName.compare("stiffnessMatrixFF") == 0) { return py::cast((PyMatrixContainer)cObjectFFRF->GetParameters().stiffnessMatrixFF); } //! AUTO: get parameter
        else if (parameterName.compare("dampingMatrixFF") == 0) { return py::cast((PyMatrixContainer)cObjectFFRF->GetParameters().dampingMatrixFF); } //! AUTO: get parameter
        else if (parameterName.compare("forceVector") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetParameters().forceVector); } //! AUTO: get parameter
        else if (parameterName.compare("forceUserFunction") == 0) { return cObjectFFRF->GetParameters().forceUserFunction.GetPythonDictionary(); } //! AUTO: get parameter
        else if (parameterName.compare("massMatrixUserFunction") == 0) { return cObjectFFRF->GetParameters().massMatrixUserFunction.GetPythonDictionary(); } //! AUTO: get parameter
        else if (parameterName.compare("computeFFRFterms") == 0) { return py::cast((bool)cObjectFFRF->GetParameters().computeFFRFterms); } //! AUTO: get parameter
        else if (parameterName.compare("coordinateIndexPerNode") == 0) { return py::cast(EPyUtils::ToPythonMember(cObjectFFRF->GetCoordinateIndexPerNode())); } //! AUTO: get parameter
        else if (parameterName.compare("objectIsInitialized") == 0) { return py::cast((bool)cObjectFFRF->GetObjectIsInitialized()); } //! AUTO: get parameter
        else if (parameterName.compare("physicsMass") == 0) { return py::cast((Real)cObjectFFRF->GetPhysicsMass()); } //! AUTO: get parameter
        else if (parameterName.compare("physicsInertia") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetPhysicsInertia()); } //! AUTO: get parameter
        else if (parameterName.compare("physicsCenterOfMass") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetPhysicsCenterOfMass()); } //! AUTO: get parameter
        else if (parameterName.compare("PHItTM") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetPHItTM()); } //! AUTO: get parameter
        else if (parameterName.compare("referencePositions") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetReferencePositions()); } //! AUTO: get parameter
        else if (parameterName.compare("tempVector") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetTempVector()); } //! AUTO: get parameter
        else if (parameterName.compare("tempCoordinates") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetTempCoordinates()); } //! AUTO: get parameter
        else if (parameterName.compare("tempCoordinates_t") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetTempCoordinates_t()); } //! AUTO: get parameter
        else if (parameterName.compare("tempRefPosSkew") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetTempRefPosSkew()); } //! AUTO: get parameter
        else if (parameterName.compare("tempVelSkew") == 0) { return EPyUtils::ToPython(cObjectFFRF->GetTempVelSkew()); } //! AUTO: get parameter
        else if (parameterName.compare("Vshow") == 0) { return py::cast((bool)visualizationObjectFFRF->GetShow()); } //! AUTO: get parameter
        else if (parameterName.compare("Vcolor") == 0) { return py::cast(EPyUtils::ToPythonMember(visualizationObjectFFRF->GetColor())); } //! AUTO: get parameter
        else if (parameterName.compare("VtriangleMesh") == 0) { return EPyUtils::ToPython(visualizationObjectFFRF->GetTriangleMesh()); } //! AUTO: get parameter
        else if (parameterName.compare("VshowNodes") == 0) { return py::cast((bool)visualizationObjectFFRF->GetShowNodes()); } //! AUTO: get parameter
        else {PyError(STDstring("ObjectFFRF::GetParameter(...): illegal parameter name ")+parameterName+" cannot be read");} // AUTO: add warning for user
        return py::object();
    }


    //! AUTO:  parameter write access
    virtual void SetParameter(const STDstring& parameterName, const py::object& value) override
    {
        if (parameterName.compare("name") == 0) { EPyUtils::FromPython(value, name); } //! AUTO: set parameter
        else if (parameterName.compare("nodeNumbers") == 0) { EPyUtils::ItemIndexFromPython<NodeIndex>(value, cObjectFFRF->GetParameters().nodeNumbers); } //! AUTO: set parameter
        else if (parameterName.compare("massMatrixFF") == 0) { EPyUtils::SetPyMatrixContainerSafely(value, cObjectFFRF->GetParameters().massMatrixFF); } //! AUTO: set parameter
        else if (parameterName.compare("stiffnessMatrixFF") == 0) { EPyUtils::SetPyMatrixContainerSafely(value, cObjectFFRF->GetParameters().stiffnessMatrixFF); } //! AUTO: set parameter
        else if (parameterName.compare("dampingMatrixFF") == 0) { EPyUtils::SetPyMatrixContainerSafely(value, cObjectFFRF->GetParameters().dampingMatrixFF); } //! AUTO: set parameter
        else if (parameterName.compare("forceVector") == 0) { EPyUtils::FromPython(value, cObjectFFRF->GetParameters().forceVector); } //! AUTO: set parameter
        else if (parameterName.compare("forceUserFunction") == 0) { cObjectFFRF->GetParameters().forceUserFunction = value; } //! AUTO: set parameter
        else if (parameterName.compare("massMatrixUserFunction") == 0) { cObjectFFRF->GetParameters().massMatrixUserFunction = value; } //! AUTO: set parameter
        else if (parameterName.compare("computeFFRFterms") == 0) { EPyUtils::FromPython(value, cObjectFFRF->GetParameters().computeFFRFterms, "ObjectFFRF.computeFFRFterms"); } //! AUTO: set parameter
        else if (parameterName.compare("objectIsInitialized") == 0) { EPyUtils::FromPython(value, cObjectFFRF->GetObjectIsInitialized(), "ObjectFFRF.objectIsInitialized"); } //! AUTO: set parameter
        else if (parameterName.compare("Vshow") == 0) { EPyUtils::FromPython(value, visualizationObjectFFRF->GetShow(), "ObjectFFRF.Vshow"); } //! AUTO: set parameter
        else if (parameterName.compare("Vcolor") == 0) { EPyUtils::FromPython(value, visualizationObjectFFRF->GetColor(), "ObjectFFRF.Vcolor"); } //! AUTO: set parameter
        else if (parameterName.compare("VtriangleMesh") == 0) { EPyUtils::FromPython(value, visualizationObjectFFRF->GetTriangleMesh()); } //! AUTO: set parameter
        else if (parameterName.compare("VshowNodes") == 0) { EPyUtils::FromPython(value, visualizationObjectFFRF->GetShowNodes(), "ObjectFFRF.VshowNodes"); } //! AUTO: set parameter
        else {PyError(STDstring("ObjectFFRF::SetParameter(...): illegal parameter name ")+parameterName+" cannot be modified");} // AUTO: add warning for user
        GetCObject()->ParametersHaveChanged();
    }

};



#endif //#ifdef include once...
