#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# SimulationSettings definitions
#
# Details:  11 definitions, emitted from systemStructuresDefinition.py (revision plan step 31a).
#           This IS Python: import it and read "definitions", a list of dicts.
#
#           ORDER MATTERS. The generators emit in the order the definitions appear,
#           and the generated C++/pybind/RST is compared byte-for-byte, so
#           reordering this list changes generated files. Append at the end unless
#           you mean to reorder.
#
#           Only descriptions, LaTeX and C++ code are raw strings; every other field
#           is a name, a flag constant or a short literal and needs no escaping.
#
#           The constants come from definitionTypes.py, which is hand-written: a
#           value used here with no constant there stops the emit and says what to
#           add, so the two can never drift apart silently.
#
# Contents: SolutionSettings, NumericalDifferentiationSettings, DiscontinuousSettings, NewtonSettings, GeneralizedAlphaSettings, ExplicitIntegrationSettings, ...
#
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

from definitionTypes import *

definitions = []
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolutionSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolutionSettings',
    addDictionaryAccess=False,
    appendToFile=False,
    classDescription=r'General settings for exporting the solution (results) of a simulation.',
    latexText=r"""
%++++++++++++++++++++++++++++++++++++++
\mysubsectionlabel{Simulation settings}{sec:SimulationSettingsMain}
This section includes hierarchical structures for simulation settings, e.g., time integration, static solver, Newton iteration and solution file export.
""",
    typicalPaths='simulationSettings',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TFileName, cFlags=SFPybind,
            pythonName='coordinatesSolutionFileName',
            defaultValue='coordinatesSolution',
            description=r"filename and (relative) path of solution file (coordinatesSolutionFile) containing all multibody system coordinates versus time; directory will be created if it does not exist; character encoding of string is up to your filesystem, but for compatibility, it is recommended to use letters, numbers and '_' only; filename ending will be added automatically if not provided: .txt in case of text mode and .sol in case of binary solution files (binarySolutionFile=True)"),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='writeSolutionToFile',
            defaultValue=DVTrue,
            description=r'flag (true/false), which determines if (global) solution vector is written to the solution file (coordinatesSolutionFile); standard quantities that are written are: solution is written as displacements and coordinatesODE1; for additional coordinates in the solution file, see the options below'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='writeFileHeader',
            defaultValue=DVTrue,
            description=r'flag (true/false); if true, file header is written (turn off, e.g. for multiple runs of time integration)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='writeFileFooter',
            defaultValue=DVTrue,
            description=r'flag (true/false); if true, information at end of simulation is written: convergence, total solution time, statistics'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='writeInitialValues',
            defaultValue=DVTrue,
            description=r'flag (true/false); if true, initial values are exported for the start time; applies to coordinatesSolution and sensor files; this may not be wanted in the append file mode if the initial values are identical to the final values of a previous computation'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='solutionWritePeriod',
            defaultValue='0.01',
            description=r'time span (period), determines how often the solution file (coordinatesSolutionFile) is written during a simulation'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='binarySolutionFile',
            defaultValue=DVFalse,
            description=r'if true, the solution file is written in binary format for improved speed and smaller file sizes; setting outputPrecision >= 8 uses double (8 bytes), otherwise float (4 bytes) is used; note that appendToFile is ineffective and files are always replaced without asking! If not provided, file ending will read .sol in case of binary files and .txt in case of text files'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='appendToFile',
            defaultValue=DVFalse,
            description=r'flag (true/false); if true, solution and solverInformation is appended to existing file (otherwise created); in BINARY mode, files are always replaced and this parameter is ineffective!'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='flushFilesImmediately',
            defaultValue=DVFalse,
            description=r'flush file buffers after every solution period written (coordinatesSolutionFile and sensor files); if set False, the output is written through a buffer, which is highly efficient, but during simulation, files may be always in an incomplete state; if set True, this may add a large amount of CPU time as the process waits until files are really written to hard disc (especially for simulation of small scale systems, writing 10.000s of time steps; at least 5us per step/file, depending on hardware)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='flushFilesDOF',
            defaultValue='10000',
            description=r'number of DOF, above which solution file (coordinatesSolutionFile) buffers are always flushed, irrespectively of whether flushFilesImmediately is set True or False (see also flushFilesImmediately); for larger files, writing takes so much time that flushing does not add considerable time'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='exportAccelerations',
            defaultValue=DVTrue,
            description=r"""add \hac{ODE2} accelerations to solution file (coordinatesSolutionFile)"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='exportAlgebraicCoordinates',
            defaultValue=DVTrue,
            description=r'add algebraicCoordinates (=Lagrange multipliers) to solution file (coordinatesSolutionFile)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='exportDataCoordinates',
            defaultValue=DVTrue,
            description=r'add DataCoordinates to solution file (coordinatesSolutionFile)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='exportODE1Velocities',
            defaultValue=DVTrue,
            description=r'add coordinatesODE1_t to solution file (coordinatesSolutionFile)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='exportVelocities',
            defaultValue=DVTrue,
            description=r"""add \hac{ODE2} velocities to solution file (coordinatesSolutionFile)"""),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='outputPrecision',
            defaultValue='10',
            description=r'precision for floating point numbers written to solution and sensor files'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='writeRestartFile',
            defaultValue=DVFalse,
            description=r'flag (true/false), which determines if restart file is written regularly, see restartFileName for details'),
        StructureParameter(type=TFileName, cFlags=SFPybind,
            pythonName='restartFileName',
            defaultValue='restartFile.txt',
            description=r'filename and (relative) path of text file for storing solution after every restartWritePeriod if writeRestartFile=True; backup file is created with ending .bck, which should be used if restart file is crashed; use Python utility function InitializeFromRestartFile(...) to consistently restart'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='restartWritePeriod',
            defaultValue='0.01',
            description=r'time span (period), determines how often the restart file is updated; this should be often enough to enable restart without too much loss of data; too low values may influence performance'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='sensorsAppendToFile',
            defaultValue=DVFalse,
            description=r'flag (true/false); if true, sensor output is appended to existing file (otherwise created) or in case of internal storage, it is appended to existing currently stored data; this allows storing sensor values over different simulations'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='sensorsWriteFileHeader',
            defaultValue=DVTrue,
            description=r'flag (true/false); if true, file header is written for sensor output (turn off, e.g. for multiple runs of time integration)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='sensorsWriteFileFooter',
            defaultValue=DVFalse,
            description=r'flag (true/false); if true, file footer is written for sensor output (turn off, e.g. for multiple runs of time integration)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='sensorsWritePeriod',
            defaultValue='0.01',
            description=r'time span (period), determines how often the sensor output is written to file or internal storage during a simulation'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='sensorsStoreAndWriteFiles',
            defaultValue=DVTrue,
            description=r'flag (true/false); if false, no sensor files will be created and no sensor data will be stored; this may be advantageous for benchmarking as well as for special solvers which should not overwrite existing results (e.g. ComputeODE2Eigenvalues); settings this value to False may cause problems if sensors are required to perform operations which are needed e.g. in UserSensors as input of loads, etc.'),
        StructureParameter(type=TString, cFlags=SFPybind,
            pythonName='solutionInformation',
            description=r"""special information added to header of solution file (e.g. parameters and settings, modes, ...); character encoding my be UTF-8, restricted to characters in \refSection{sec:utf8}, but for compatibility, it is recommended to use ASCII characters only (95 characters, see wiki)"""),
        StructureParameter(type=TFileName, cFlags=SFPybind,
            pythonName='solverInformationFileName',
            defaultValue='solverInformation.txt',
            description=r"filename and (relative) path of text file showing detailed information during solving; detail level according to yourSolver.verboseModeFile; if solutionSettings.appendToFile is true, the information is appended in every solution step; directory will be created if it does not exist; character encoding of string is up to your filesystem, but for compatibility, it is recommended to use letters, numbers and '_' only"),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='recordImagesInterval',
            defaultValue='-1.',
            description=r'record frames of the main view in the renderer (images) during solving: amount of time to wait until next image (frame) is recorded; set recordImages = -1. if no images shall be recorded; set, e.g., recordImages = 0.01 to record an image every 10 milliseconds (requires that the time steps / load steps are sufficiently small!); for file names, etc., see VisualizationSettings.exportImages; note that only the main view (0) can be saved in this way, while for multiple views, you have to aquire data via renderer.RedrawAndGetImage()'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   NumericalDifferentiationSettings   ++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='NumericalDifferentiationSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for numerical differentiation of a function (needed for computation of numerical jacobian e.g. in implizit integration).',
    typicalPaths='simulationSettings.timeIntegration.newton,simulationSettings.staticSolver.newton',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='addReferenceCoordinatesToEpsilon',
            defaultValue=DVFalse,
            description=r"""True: for the size estimation of the differentiation parameter, the reference coordinate $q^{Ref}_i$ is added to \hac{ODE2} coordinates --> see; False: only the current coordinate is used for size estimation of the differentiation parameter"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='doSystemWideDifferentiation',
            defaultValue=DVFalse,
            description=r"""True: system wide differentiation (e.g. all \hac{ODE2} equations w.r.t. all \hac{ODE2} coordinates); False: only local (object) differentiation"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='forAE',
            defaultValue=DVFalse,
            description=r"flag (true/false); false = perform direct computation of jacobian for algebraic equations (AE), true = use numerical differentiation; as there must always exist an analytical implemented jacobian for AE, 'true' should only be used for verification"),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='forODE2',
            defaultValue=DVFalse,
            description=r'flag (true/false); false = perform direct computation (e.g., using autodiff) of jacobian for ODE2 equations, true = use numerical differentiation; numerical differentiation is less efficient and may lead to numerical problems, but may smoothen problems of analytical derivatives; sometimes the analytical derivative may neglect terms'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='forODE2connectors',
            defaultValue=DVFalse,
            description=r'flag (true/false); false: if also forODE2==false, perform direct computation of jacobian for ODE2 terms for connectors; else: use numerical differentiation; NOTE: THIS FLAG IS FOR DEVELOPMENT AND WILL BE ERASED IN FUTURE'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='minimumCoordinateSize',
            defaultValue='1e-2',
            description=r'minimum size of coordinates in relative differentiation parameter'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='relativeEpsilon',
            defaultValue='1e-7',
            description=r"""relative differentiation parameter epsilon; the numerical differentiation parameter $\varepsilon$ follows from the formula ($\varepsilon = \varepsilon_\mathrm{relative}*max(q_{min}, |q_i + [q^{Ref}_i]|)$, with $\varepsilon_\mathrm{relative}$=relativeEpsilon, $q_{min} = $minimumCoordinateSize, $q_i$ is the current coordinate which is differentiated, and $qRef_i$ is the reference coordinate of the current coordinate"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='jacobianConnectorDerivative',
            defaultValue=DVTrue,
            description=r'True: for analytic Jacobians of connectors, the Jacobian derivative is computed, causing additional CPU costs and not beeing available for all connectors or markers (thus switching to numerical differentiation); False: Jacobian derivative is neglected in analytic Jacobians (but included in numerical Jacobians), which often has only minor influence on convergence'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   DiscontinuousSettings   +++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='DiscontinuousSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for discontinuous iterations, as in contact, friction, plasticity and general switching phenomena.',
    typicalPaths='simulationSettings.timeIntegration,simulationSettings.staticSolver',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='ignoreMaxIterations',
            defaultValue=DVTrue,
            description=r'continue solver if maximum number of discontinuous (post Newton) iterations is reached (ignore tolerance)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='iterationTolerance',
            defaultValue='1',
            description=r'absolute tolerance for discontinuous (post Newton) iterations; the errors represent absolute residuals and can be quite high'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='maxIterations',
            defaultValue='5',
            description=r'maximum number of discontinuous (post Newton) iterations'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useRecommendedStepSize',
            defaultValue=DVTrue,
            description=r'some objects (contact-related) provide a recommendedStepSize; if True, this recommendation is used, but may lead to very small step sizes and solver could fail if restrictions are too hard; set to False to ignore this recommendation'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   NewtonSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='NewtonSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for Newton method used in static or dynamic simulation.',
    typicalPaths='simulationSettings.timeIntegration,simulationSettings.staticSolver',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='NumericalDifferentiationSettings', cFlags=SFPybind,
            pythonName='numericalDifferentiation',
            description=r'numerical differentiation parameters for numerical jacobian (e.g. Newton in static solver or implicit time integration)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='absoluteTolerance',
            defaultValue='1e-10',
            description=r'absolute tolerance of residual for Newton (needed e.g. if residual is fulfilled right at beginning); condition: sqrt(q*q)/numberOfCoordinates <= absoluteTolerance'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='relativeTolerance',
            defaultValue='1e-8',
            description=r'relative tolerance of residual for Newton (general goal of Newton is to decrease the residual by this factor)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useNewtonSolver',
            defaultValue=DVTrue,
            description=r'flag (true/false); false = linear computation, true = use Newton solver for nonlinear solution'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='weightTolerancePerCoordinate',
            defaultValue=DVFalse,
            description=r'flag (true/false); false = compute error as L2-Norm of residual; true = compute error as (L2-Norm of residual) / (sqrt(number of coordinates)), which can help to use common tolerance independent of system size'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='newtonResidualMode',
            defaultValue=DVZeroIndex,
            description=r"""0 ... use residual for computation of error (standard); 1 ... use \hac{ODE2} and \hac{ODE1} newton increment for error (set relTol and absTol to same values!) ==> may be advantageous if residual is zero, e.g., in kinematic analysis; TAKE CARE with this flag"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='adaptInitialResidual',
            defaultValue=DVTrue,
            description=r'flag (true/false); false = standard; True: if initialResidual is very small (or zero), it may increase significantely in the first Newton iteration; to achieve relativeTolerance, the initialResidual will by updated by a higher residual within the first Newton iteration'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='modifiedNewtonContractivity',
            defaultValue='0.5',
            description=r'maximum contractivity (=reduction of error in every Newton iteration) accepted by modified Newton; if contractivity is greater, a Jacobian update is computed'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useModifiedNewton',
            defaultValue=DVFalse,
            description=r'True: compute Jacobian only at first call to solver; the Jacobian (and its factorizations) is not computed in each Newton iteration, even not in every (time integration) step; False: Jacobian (and factorization) is computed in every Newton iteration (default, but may be costly)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='modifiedNewtonJacUpdatePerStep',
            defaultValue=DVFalse,
            description=r'True: compute Jacobian at every time step (or static step), but not in every Newton iteration (except for bad convergence ==> switch to full Newton)'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='maxIterations',
            defaultValue='25',
            description=r'maximum number of iterations (including modified + restart Newton iterations); after that total number of iterations, the static/dynamic solver refines the step size or stops with an error'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='maxModifiedNewtonIterations',
            defaultValue='8',
            description=r'maximum number of iterations for modified Newton (without Jacobian update); after that number of iterations, the modified Newton method gets a jacobian update and is further iterated'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='maxModifiedNewtonRestartIterations',
            defaultValue='7',
            description=r'maximum number of iterations for modified Newton after a Jacobian update; after that number of iterations, the full Newton method is started for this step'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='maximumSolutionNorm',
            defaultValue='1e38',
            description=r'this is the maximum allowed value for solutionU.L2NormSquared() which is the square of the square norm (i.e., value=$u_1^2$+$u_2^2$+...), and solutionV/A...; if the norm of solution vectors is larger, Newton method is stopped; the default value is chosen such that it would still work for single precision numbers (float)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   GeneralizedAlphaSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='GeneralizedAlphaSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for generalized-alpha, implicit trapezoidal or Newmark time integration methods.',
    typicalPaths='simulationSettings.timeIntegration',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='newmarkBeta',
            defaultValue='0.25',
            description=r"""value beta for Newmark method; default value beta = $\frac 1 4$ corresponds to (undamped) trapezoidal rule"""),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='newmarkGamma',
            defaultValue='0.5',
            description=r"""value gamma for Newmark method; default value gamma = $\frac 1 2$ corresponds to (undamped) trapezoidal rule"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useIndex2Constraints',
            defaultValue=DVFalse,
            description=r'set useIndex2Constraints = true in order to use index2 (velocity level constraints) formulation'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useNewmark',
            defaultValue=DVFalse,
            description=r'if true, use Newmark method with beta and gamma instead of generalized-Alpha'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='spectralRadius',
            defaultValue='0.9',
            description=r'spectral radius for Generalized-alpha solver; set this value to 1 for no damping or to 0 < spectralRadius < 1 for damping of high-frequency dynamics; for position-level constraints (index 3), spectralRadius must be < 1'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='computeInitialAccelerations',
            defaultValue=DVTrue,
            description=r'True: compute initial accelerations from system EOM in acceleration form; NOTE that initial accelerations that are following from user functions in constraints are not considered for now! False: use zero accelerations'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='storeInitialAlgebraicCoordinates',
            defaultValue=DVTrue,
            description=r'True: IF computeInitialAccelerations=True, store initial algebraic coordinates (usually the Lagrange multipliers) in the initial coordinates vector (and thus in the first line of the coordinates solution file); for further details on limitations, see computeInitialAccelerations'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='resetAccelerations',
            defaultValue=DVFalse,
            description=r'this flag only affects if computeInitialAccelerations=False: if resetAccelerations=True, accelerations are set zero in the solver function InitializeSolverInitialConditions; this may be unwanted in case of repeatedly called SolveSteps() and in cases where solutions shall be prolonged from previous computations'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='lieGroupAddTangentOperator',
            defaultValue=DVTrue,
            description=r'True: for Lie group nodes, in case that lieGroupSimplifiedKinematicRelations=True, the integrator adds the tangent operator for stiffness and constraint matrices, for improved Newton convergence; not available for sparse matrix mode (EigenSparse)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='lieGroupSimplifiedKinematicRelations',
            defaultValue=DVFalse,
            description=r'True: for Lie group nodes, the integrator uses the original kinematic relations of the Bruls and Cardona 2010 paper; False (recommended): higher accuracy as proposed in paper by Holzinger, Arnold, Gerstmayr, sigma-modified Lie group generalized alpha methods for constrained multibody systems, 2025 (to be sumitted)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   ExplicitIntegrationSettings   +++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='ExplicitIntegrationSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for explicit solvers, like Explicit Euler, RK44, ODE23, DOPRI5 and others. The settings may significantely influence performance.',
    typicalPaths='simulationSettings.timeIntegration',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TDynamicSolverType, cFlags=SFPybind,
            pythonName='dynamicSolverType',
            defaultValue='DynamicSolverType::DOPRI5',
            description=r"""selection of explicit solver type (DOPRI5, ExplicitEuler, ExplicitMidpoint, RK44, RK67, VelocityVerlet, ...), for detailed description see DynamicSolverType, \refSection{sec:DynamicSolverType}, but only referring to explicit solvers."""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='eliminateConstraints',
            defaultValue=DVTrue,
            description=r'True: make explicit solver work for simple CoordinateConstraints, which are eliminated for ground constraints (e.g. fixed nodes in finite element models). False: incompatible constraints are ignored (BE CAREFUL)!'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useLieGroupIntegration',
            defaultValue=DVTrue,
            description=r'True: use Lie group integration for rigid body nodes; must be turned on for Lie group nodes (without data coordinates) to work properly; does not work for nodes with data coordinates!'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='computeEndOfStepAccelerations',
            defaultValue=DVTrue,
            description=r'accelerations are computed at stages of the explicit integration scheme; if the user needs accelerations at the end of a step, this flag needs to be activated; if True, this causes a second call to the RHS of the equations, which may DOUBLE COMPUTATIONAL COSTS for one-step-methods; if False, the accelerations are re-used from the last stage, being slightly different'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='computeMassMatrixInversePerBody',
            defaultValue=DVFalse,
            description=r'If true, the solver assumes the bodies to be independent and computes the inverse of the mass matrix for all bodies independently; this may lead to WRONG RESULTS, if bodies share nodes, e.g., two MassPoint objects put on the same node or a beam with a mass point attached at a shared node; however, it may speed up explicit time integration for large systems significantly (multi-threaded)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   TimeIntegrationSettings   +++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='TimeIntegrationSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'General parameters used in time integration; specific parameters are provided in the according solver settings, e.g. for generalizedAlpha.',
    typicalPaths='simulationSettings',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='NewtonSettings', cFlags=SFPybind,
            pythonName='newton',
            description=r'parameters for Newton method; used for implicit time integration methods only'),
        StructureParameter(type='DiscontinuousSettings', cFlags=SFPybind,
            pythonName='discontinuous',
            description=r'parameters for treatment of discontinuities'),
        StructureParameter(type='GeneralizedAlphaSettings', cFlags=SFPybind,
            pythonName='generalizedAlpha',
            description=r'parameters for generalized-alpha, implicit trapezoidal rule or Newmark (options only apply for these methods)'),
        StructureParameter(type='ExplicitIntegrationSettings', cFlags=SFPybind,
            pythonName='explicitIntegration',
            description=r'special parameters for explicit time integration'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='startTime',
            defaultValue=DVZeroIndex,
            description=r'$t_{start}$: start time of time integration (usually set to zero)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='endTime',
            defaultValue='1',
            description=r'$t_{end}$: end time of time integration'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='numberOfSteps',
            defaultValue='100',
            description=r"""$n_{steps}$: number of steps in time integration; (maximum) stepSize $h$ is computed from $h = \frac{t_{end} - t_{start}}{n_{steps}}$; for automatic stepsize control, this stepSize is the maximum steps size, $h_{max} = h$; numberOfSteps can also be a float type, but must be close to an integer (relative tolerance $100\cdot\varepsilon$) as it is silently rounded to int"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='adaptiveStep',
            defaultValue=DVTrue,
            description=r'True: the step size may be reduced if step fails; no automatic stepsize control'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepRecoverySteps',
            defaultValue='10',
            description=r'Number of steps needed after which steps will be increased after previous step reduction due to discontinuousIteration or Newton errors'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepRecoveryIterations',
            defaultValue='7',
            description=r'Number of max. (Newton iterations + discontinuous iterations) at which a step increase is considered; in order to immediately increase steps after reduction, chose a high value'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepIncrease',
            defaultValue='2',
            description=r'Multiplicative factor (MUST BE > 1) for step size to increase after previous step reduction due to discontinuousIteration or Newton errors'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepDecrease',
            defaultValue='0.5',
            description=r'Multiplicative factor (MUST BE: 0 < factor < 1) for step size to decrese due to discontinuousIteration or Newton errors'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='automaticStepSize',
            defaultValue=DVTrue,
            description=r"""True: for specific integrators with error control (e.g., DOPRI5), compute automatic step size based on error estimation; False: constant step size (step may be reduced if adaptiveStep=True); the maximum stepSize reads $h = h_{max} = \frac{t_{end} - t_{start}}{n_{steps}}$"""),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='minimumStepSize',
            defaultValue='1e-8',
            description=r'$h_{min}$: if automaticStepSize=True or adaptiveStep=True: lower limit of time step size, before integrator stops with adaptiveStep; lower limit of automaticStepSize control (continues but raises warning)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='initialStepSize',
            defaultValue=DVZeroIndex,
            description=r'$h_{init}$: if automaticStepSize=True, initial step size; if initialStepSize==0, max. stepSize, which is (endTime-startTime)/numberOfSteps, is used as initial guess; a good choice of initialStepSize may help the solver to start up faster.'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='absoluteTolerance',
            defaultValue='1e-8',
            description=r"""$a_{tol}$: if automaticStepSize=True, absolute tolerance for the error control; must fulfill $a_{tol} > 0$; see \refSection{sec:ExplicitSolver}"""),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='relativeTolerance',
            defaultValue='1e-8',
            description=r"""$r_{tol}$: if automaticStepSize=True, relative tolerance for the error control; must fulfill $r_{tol} \ge 0$; see \refSection{sec:ExplicitSolver}"""),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='stepSizeSafety',
            defaultValue='0.90',
            description=r"""$r_{sfty}$: if automaticStepSize=True, a safety factor added to estimated optimal step size, in order to prevent from many rejected steps, see \refSection{sec:ExplicitSolver}. Make this factor smaller if many steps are rejected."""),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='stepSizeMaxIncrease',
            defaultValue='2',
            description=r"""$f_{maxInc}$: if automaticStepSize=True, maximum increase of step size per step, see \refSection{sec:ExplicitSolver}; make this factor smaller (but $> 1$) if too many rejected steps"""),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='computeLoadsJacobian',
            defaultValue=DVZeroIndex,
            description=r'0:  jacobian of loads not considered (may lead to slow convergence or Newton failure); 1: in case of implicit integrators, compute (numerical) Jacobian of ODE2 and ODE1 coordinates for loads, causing additional computational costs; this is advantageous in cases where loads are related nonlinearly to coordinates; 2: also compute ODE2_t dependencies for jacobian; note that computeLoadsJacobian has no effect in case of doSystemWideDifferentiation, as this anyway includes all load dependencies'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='reuseConstantMassMatrix',
            defaultValue=DVTrue,
            description=r'True: does not recompute constant mass matrices (e.g. of some finite elements, mass points, etc.); if False, it always recomputes the mass matrix (e.g. needed, if user changes mass parameters via Python)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='simulateInRealtime',
            defaultValue=DVFalse,
            description=r'True: simulate in realtime; the solver waits for computation of the next step until the CPU time reached the simulation time; if the simulation is slower than realtime, it simply continues'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='realtimeFactor',
            defaultValue='1',
            description=r'if simulateInRealtime=True, this factor is used to make the simulation slower than realtime (factor < 1) or faster than realtime (factor > 1)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='realtimeWaitMicroseconds',
            defaultValue='1000',
            description=r'if simulateInRealtime=True, a loop runs which waits realtimeWaitMicroseconds until checking again if the realtime is reached; using larger values leads to less CPU usage but less accurate realtime accuracy; smaller values (< 1000) increase CPU usage but improve realtime accuracy'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='verboseMode',
            defaultValue=DVZeroIndex,
            description=r'0 ... no output, 1 ... show short step information every 2 seconds (every 30 seconds after 1 hour CPU time), 2 ... show every step information, 3 ... show also solution vector, 4 ... show also mass matrix and jacobian (implicit methods), 5 ... show also Jacobian inverse (implicit methods)'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='verboseModeFile',
            defaultValue=DVZeroIndex,
            description=r'same behaviour as verboseMode, but outputs all solver information to file'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='stepInformation',
            defaultValue='67',
            description=r'add up the following binary flags: 0 ... show only step time, 1 ... show time to go, 2 ... show newton iterations (Nit) per step or period, 4 ... show Newton jacobians (jac) per step or period, 8 ... show discontinuous iterations (Dit) per step or period, 16 ... show step size (dt), 32 ... show CPU time spent; 64 ... show adaptive step reduction warnings; 128 ... show step increase information; 1024 ... show every time step; time is usually shown in fractions of seconds (s), hours (h), or days'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   StaticSolverSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='StaticSolverSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for static solver linear or nonlinear (Newton).',
    typicalPaths='simulationSettings',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='NewtonSettings', cFlags=SFPybind,
            pythonName='newton',
            description=r'parameters for Newton method (e.g. in static solver or time integration)'),
        StructureParameter(type='DiscontinuousSettings', cFlags=SFPybind,
            pythonName='discontinuous',
            description=r'parameters for treatment of discontinuities'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='numberOfLoadSteps',
            defaultValue='1',
            description=r'number of load steps; if numberOfLoadSteps=1, no load steps are used and full forces are applied at once'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='loadStepDuration',
            defaultValue='1',
            description=r'quasi-time for all load steps (added to current time in load steps)'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='loadStepStart',
            defaultValue=DVZeroIndex,
            description=r'a quasi time, which can be used for the output (first column) as well as for time-dependent forces; quasi-time is increased in every step i by loadStepDuration/numberOfLoadSteps; loadStepTime = loadStepStart + i*loadStepDuration/numberOfLoadSteps, but loadStepStart untouched ==> increment by user'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='loadStepGeometric',
            defaultValue=DVFalse,
            description=r'if loadStepGeometric=false, the load steps are incremental (arithmetic series, e.g. 0.1,0.2,0.3,...); if true, the load steps are increased in a geometric series, e.g. for $n=8$ numberOfLoadSteps and $d = 1000$ loadStepGeometricRange, it follows: $1000^{1/8}/1000=0.00237$, $1000^{2/8}/1000=0.00562$, $1000^{3/8}/1000=0.0133$, ..., $1000^{7/8}/1000=0.422$, $1000^{8/8}/1000=1$'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='loadStepGeometricRange',
            defaultValue='1000',
            description=r'if loadStepGeometric=true, the load steps are increased in a geometric series, see loadStepGeometric'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useLoadFactor',
            defaultValue=DVTrue,
            description=r"""True: compute a load factor $\in [0,1]$ from static step time; all loads are scaled by the load factor; False: loads are always scaled with 1 -- use this option if time dependent loads use a userFunction"""),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='stabilizerODE2term',
            defaultValue=DVZeroIndex,
            description=r"""add mass-proportional stabilizer term in \hac{ODE2} part of jacobian for stabilization (scaled ), e.g. of badly conditioned problems; the diagnoal terms are scaled with $stabilizer = (1-loadStepFactor^2)$, and go to zero at the end of all load steps: $loadStepFactor=1$ -> $stabilizer = 0$"""),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='adaptiveStep',
            defaultValue=DVTrue,
            description=r'True: use step reduction if step fails; False: fixed step size'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepRecoverySteps',
            defaultValue='4',
            description=r'Number of steps needed after which steps will be increased after previous step reduction due to discontinuousIteration or Newton errors'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepRecoveryIterations',
            defaultValue='7',
            description=r'Number of max. (Newton iterations + discontinuous iterations) at which a step increase is considered; in order to immediately increase steps after reduction, chose a high value'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepIncrease',
            defaultValue='2',
            description=r'Multiplicative factor (MUST BE > 1) for step size to increase after previous step reduction due to discontinuousIteration or Newton errors'),
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='adaptiveStepDecrease',
            defaultValue='0.25',
            description=r'Multiplicative factor (MUST BE: 0 < factor < 1) for step size to decrese due to discontinuousIteration or Newton errors'),
        StructureParameter(type=TReal(greaterThan=0), cFlags=SFPybind,
            pythonName='minimumStepSize',
            defaultValue='1e-8',
            description=r'lower limit of step size, before nonlinear solver stops'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='computeLoadsJacobian',
            defaultValue=DVTrue,
            description=r'True: compute (currently numerical) Jacobian for loads, causing additional computational costs; this is advantageous in cases where loads are related nonlinearly to coordinates; False: jacobian of loads not considered (may lead to slow convergence or Newton failure); note that computeLoadsJacobian has no effect in case of doSystemWideDifferentiation, as this anyway includes all load dependencies'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='constrainODE1coordinates',
            defaultValue=DVTrue,
            description=r'True: ODE1coordinates are constrained to initial values; False: undefined behavior, currently not supported'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='verboseMode',
            defaultValue='1',
            description=r'0 ... no output, 1 ... show errors and load steps, 2 ... show short Newton step information (error), 3 ... show also solution vector, 4 ... show also jacobian, 5 ... show also Jacobian inverse'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='verboseModeFile',
            defaultValue=DVZeroIndex,
            description=r'same behaviour as verboseMode, but outputs all solver information to file'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='stepInformation',
            defaultValue='67',
            description=r'add up the following binary flags: 0 ... show only step time, 1 ... show time to go, 2 ... show newton iterations (Nit) per step or period, 4 ... show Newton jacobians (jac) per step or period, 8 ... show discontinuous iterations (Dit) per step or period, 16 ... show step size (dt), 32 ... show CPU time spent; 64 ... show adaptive step reduction warnings; 128 ... show step increase information; 1024 ... show every time step; time is usually shown in fractions of seconds (s), hours (h), or days'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   LinearSolverSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='LinearSolverSettings',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for linear solver, both dense and sparse (Eigen).',
    typicalPaths='simulationSettings',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TReal(minimum=0), cFlags=SFPybind,
            pythonName='pivotThreshold',
            defaultValue=DVZeroIndex,
            description=r'[ONLY available for EXUdense and EigenDense (FullPivot) solver] threshold for dense linear solver, can be used to detect close to singular solutions, setting this to, e.g., 1e-12; solver then reports on equations that are causing close to singularity'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='ignoreSingularJacobian',
            defaultValue=DVFalse,
            description=r"[ONLY implemented for dense, Eigen matrix mode] False: standard way, fails if jacobian is singular; True: use Eigen's FullPivLU (thus only works with LinearSolverType.EigenDense) which handles over- and underdetermined systems; can often resolve redundant constraints, but MAY ALSO LEAD TO ERRONEOUS RESULTS!"),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='reuseAnalyzedPattern',
            defaultValue=DVFalse,
            description=r'[ONLY available for sparse matrices] True: the Eigen SparseLU solver offers the possibility to reuse an analyzed pattern of a previous factorization; this may reduce total factorization time by a factor of 2 or 3, depending on the matrix type; however, if the matrix patterns heavily change between computations, this may even slow down performance; this flag is set for SparseMatrices in InitializeSolverData(...) and should be handled with care!'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='showCausingItems',
            defaultValue=DVTrue,
            description=r'False: no output, if solver fails; True: if redundant equations appear, they are resolved such that according solution variables are set to zero; in case of redundant constraints, this may help, but it may lead to erroneous behaviour; for static problems, this may suppress static motion or resolve problems in case of instabilities, but should in general be considered with care!'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   Parallel   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='Parallel',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Settings for linear solver, both dense and sparse (Eigen).',
    typicalPaths='simulationSettings',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='numberOfThreads',
            defaultValue='1',
            description=r'number of threads used for parallel computation (1 == scalar processing); do not use more threads than available threads (in most cases it is good to restrict to the number of cores); currently, only one solver can be started with multithreading; if you use several mbs in parallel (co-simulation), you should use serial computing'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='useLoadBalancing',
            defaultValue=DVTrue,
            description=r'if True, parallel computation uses load balancing, which may give better performance in case of non-equilibrated loads; (mobile) Intel CPUs may perform better without load balancing; this flag is coupled to exudyn.special.solver.multiThreadingLoadBalancing (overwritten when solver starts with multithreading)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='multithreadedLLimitLoads',
            defaultValue='20',
            description=r'compute loads multi-threaded; this is the limit number of loads from which on parallelization is used; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='multithreadedLLimitResiduals',
            defaultValue='20',
            description=r'compute RHS vectors, AE, and reaction forces multi-threaded; this is the limit number of objects from which on parallelization is used; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='multithreadedLLimitJacobians',
            defaultValue='20',
            description=r'compute jacobians (ODE2, AE, ...) multi-threaded; this is the limit number of according objects from which on parallelization is used; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='multithreadedLLimitMassMatrices',
            defaultValue='20',
            description=r'compute bodies mass matrices multi-threaded; this is the limit number of bodies from which on parallelization is used; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='taskSplitMinItems',
            defaultValue='50',
            description=r'number of items from which on the tasks are split into subtasks (which slightly increases threading performance; this may be critical for smaller number of objects, should be roughly between 50 and 5000; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        StructureParameter(type=TIndex(greaterThan=0), cFlags=SFPybind,
            pythonName='taskSplitTasksPerThread',
            defaultValue='16',
            description=r'this is the number of subtasks that every thread receives; minimum is 1, the maximum should not be larger than 100; this factor is 1 as long as the taskSplitMinItems is not reached; flag is copied into MainSystem internal flag at InitializeSolverData(...)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SimulationSettings   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SimulationSettings',
    addDictionaryAccess=True,
    appendToFile=True,
    classDescription=r'General Settings for simulation; according settings for solution and solvers are given in subitems of this structure',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='LinearSolverSettings', cFlags=SFPybind,
            pythonName='linearSolverSettings',
            description=r'linear solver parameters (used for dense and sparse solvers)'),
        StructureParameter(type='Parallel', cFlags=SFPybind,
            pythonName='parallel',
            description=r'parameters for vectorized and parallelized (multi-threaded) computations'),
        StructureParameter(type='SolutionSettings', cFlags=SFPybind,
            pythonName='solutionSettings',
            description=r'settings for solution files'),
        StructureParameter(type='StaticSolverSettings', cFlags=SFPybind,
            pythonName='staticSolver',
            description=r'static solver parameters'),
        StructureParameter(type='TimeIntegrationSettings', cFlags=SFPybind,
            pythonName='timeIntegration',
            description=r'time integration parameters'),
        StructureParameter(type=TLinearSolverType, cFlags=SFPybind,
            pythonName='linearSolverType',
            defaultValue='LinearSolverType::EXUdense',
            description=r'selection of numerical linear solver: exu.LinearSolverType.EXUdense (dense matrix inverse), exu.LinearSolverType.EigenSparse (sparse matrix LU-factorization), ... (enumeration type)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='cleanUpMemory',
            defaultValue=DVFalse,
            description=r'True: solvers will free memory at exit (recommended for large systems); False: keep allocated memory for repeated computations to increase performance'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='displayComputationTime',
            defaultValue=DVFalse,
            description=r'display computation time statistics at end of solving'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='displayGlobalTimers',
            defaultValue=DVTrue,
            description=r'display global timer statistics at end of solving (e.g., for contact, but also for internal timings during development)'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='displayStatistics',
            defaultValue=DVFalse,
            description=r'display general computation information at end of time step (steps, iterations, function calls, step rejections, ...'),
        StructureParameter(type=TIndex(minimum=0), cFlags=SFPybind,
            pythonName='outputPrecision',
            defaultValue='6',
            description=r'precision for floating point numbers written to console; e.g. values written by solver'),
        StructureParameter(type=Tbool, cFlags=SFPybind,
            pythonName='pauseAfterEachStep',
            defaultValue=DVFalse,
            description=r'pause after every time step or static load step(user press SPACE)'),
        ],
    ))
