#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Solvers definitions
#
# Details:  3 definitions, emitted from systemStructuresDefinition.py (revision plan step 31a).
#           This IS Python: import it and read "definitions", a list of dicts.
#
#           ORDER MATTERS. The generators emit in the order the definitions appear,
#           and the generated C++/pybind/RST is compared byte-for-byte, so
#           reordering this list changes generated files. Append at the end unless
#           you mean to reorder.
#
#           Only descriptions, LaTeX and C++ code are raw strings; every other field
#           is a name, a flag constant or a short literal and needs no escaping.
#
#           The constants come from definitionTypes.py, which is hand-written: a
#           value used here with no constant there stops the emit and says what to
#           add, so the two can never drift apart silently.
#
# Contents: MainSolverStatic, MainSolverImplicitSecondOrder, MainSolverExplicit
#
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

from definitionTypes import *

definitions = []
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   MainSolverStatic   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='MainSolverStatic',
    addDictionaryAccess=False,
    appendToFile=False,
    classDescription=r"""PyBind interface (trampoline) class for static solver. With this interface, the static solver and its substructures can be accessed via Python. NOTE that except from SolveSystem(...), these functions are only intended for experienced users and they need to be handled with care, as unexpected crashes may happen if used inappropriate. Furthermore, the functions have a lot of overhead (performance much lower than internal solver) due to Python interfaces, and should thus be used for small systems. To access the solver in Python, write: \\ 
 \texttt{solver = MainSolverStatic()} \\ 
and hereafter you can access all data and functions via 'solver'.""",
    parentClass='MainSolverBase',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='CSolverTimer', cFlags=SFPybind, isLinked=True,
            pythonName='timer',
            cplusplusName='cSolver.timer',
            description=r'timer which measures the CPU time of solver sub functions'),
        StructureParameter(type='SolverIterationData', cFlags=SFPybind, isLinked=True,
            pythonName='it',
            cplusplusName='cSolver.it',
            description=r'all information about iterations (steps, discontinuous iteration, newton,...)'),
        StructureParameter(type='SolverConvergenceData', cFlags=SFPybind, isLinked=True,
            pythonName='conv',
            cplusplusName='cSolver.conv',
            description=r'all information about tolerances, errors and residua'),
        StructureParameter(type='SolverOutputData', cFlags=SFPybind, isLinked=True,
            pythonName='output',
            cplusplusName='cSolver.output',
            description=r'output modes and timers for exporting solver information and solution'),
        StructureParameter(type='NewtonSettings', cFlags=SFPybind, isLinked=True,
            pythonName='newton',
            cplusplusName='cSolver.newton',
            description=r'copy of newton settings from timeint or staticSolver'),
        StructureParameter(type=TCSolverStatic, cFlags='',
            pythonName='cSolver',
            description=r'link to C++ CSolver, not accessible from Python'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='loadStepGeometricFactor',
            cplusplusName='cSolver.loadStepGeometricFactor',
            description=r'multiplicative load step factor; this factor is computed from loadStepGeometric parameters in SolveSystem(...)'),
        StructureParameter(type=Tbool, cFlags='',
            pythonName='isInitialized',
            description=r'variable is used to see, if system is initialized ==> avoid crashes; DO not change these variables: can easily lead to crash! '),
        StructureParameter(type=TIndex4, cFlags='',
            pythonName='initializedSystemSizes',
            description=r'index-array contains 4 integers: nODE2, nODE1, nAE and nData of initialization: this guaranties, that no function is called with wrong system sizes; DO not change these variables: can easily lead to crash! '),
        StructureFunction(type='', cFlags='',
            pythonName='MainSolverStatic',
            implementation='isInitialized=false;',
            description=r'constructor, in order to set valid state (settings not initialized at beginning)'),
        StructureFunction(type='const CSolverBase&', cFlags=SFConst, isVirtual=True,
            pythonName='GetCSolver',
            implementation='return cSolver;',
            description=r'const access to cSolver'),
        StructureFunction(type='CSolverBase&', cFlags='', isVirtual=True,
            pythonName='GetCSolver',
            implementation='return cSolver;',
            description=r'reference access to cSolver'),
        StructureFunction(type=Tbool, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='CheckInitialized',
            args='const MainSystem& mainSystem',
            description=r'check if MainSolver and MainSystem are correctly initialized ==> otherwise raise SysError'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy,
            pythonName='ComputeLoadFactor',
            args='const SimulationSettings& simulationSettings',
            implementation='return cSolver.ComputeLoadFactor(simulationSettings);',
            description=r'for static solver, this is a factor in interval [0,1]; MUST be overwritten'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetErrorString',
            description=r'return error string if solver has not been successful'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSolverName',
            description=r'get solver name - needed for output file header and visualization window'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsStaticSolver',
            description=r'return true, if static solver; needs to be overwritten in derived class'),
        StructureFunction(type=TReal, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSimulationEndTime',
            args='const SimulationSettings& simulationSettings',
            description=r'compute simulation end time (depends on static or time integration solver)'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ReduceStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, Index severity',
            description=r'reduce step size (1..normal, 2..severe problems); return true, if reduction was successful'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IncreaseStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'increase step size if convergence is good'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='HasAutomaticStepSizeControl',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'return true, if solver supports automatic stepsize control, otherwise false'),
        StructureFunction(type=Tbool, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize solverSpecific,data,it,conv; set/compute initial conditions (solver-specific!); initialize output files'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PreInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'pre-initialize for solver specific tasks; called at beginning of InitializeSolver, right after Solver data reset'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverOutput',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize output files; called from InitializeSolver()'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverPreChecks',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'check if system is solvable; initialize dense/sparse computation modes'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverData',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize all data,it,conv; called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverInitialConditions',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'set/compute initial conditions (solver-specific!); called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PostInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'post-initialize for solver specific tasks; called at the end of InitializeSolver'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSystem',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'solve System: InitializeSolver, SolveSteps, FinalizeSolver'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinalizeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write concluding information (timer statistics, messages) and close files'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSteps',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'main solver part: calls multiple InitializeStep(...)/ DiscontinuousIteration(...)/ FinishStep(...); do step reduction if necessary; return true if success, false else'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='UpdateCurrentTime',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'update currentTime (and load factor); MUST be overwritten in special solver class'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize static step / time step; Python-functions; do some outputs, checks, etc.'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinishStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'finish static step / time step; write output of results to file'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='DiscontinuousIteration',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform discontinuousIteration for static step / time step; CALLS ComputeNewtonResidual'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='Newton',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform Newton method for given solver method'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonResidual',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute residual for Newton method (e.g. static or time step); store residual vector in systemResidual and return scalar residual (specific computation may depend on solver types)'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonUpdate',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, initial=true',
            description=r'compute update for currentState from newtonSolution (decrement from residual and jacobian); if initial, this is for the initial update with newtonSolution=0'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonJacobian',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute jacobian for newton method of given solver method; store result in systemJacobian'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteSolutionFileHeader',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique file header, depending on static/ dynamic simulation'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteCoordinatesToFile',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique coordinates solution file'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsVerboseCheck',
            args='Index level',
            description=r'return true, if file or console output is at or above the given level'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='VerboseWrite',
            args='Index level, const std::string& str',
            description=r'write to console and/or file in case of level'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE2size',
            description=r'number of \hac{ODE2} equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE1size',
            description=r"""number of \hac{ODE1} equations in solver (not yet implemented)"""),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetAEsize',
            description=r'number of algebraic equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetDataSize',
            description=r'number of data (history) variables in solver'),
        StructureFunction(type=TNumpyMatrix, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemJacobian',
            description=r'get locally stored / last computed system jacobian of solver'),
        StructureFunction(type=TNumpyMatrix, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemMassMatrix',
            description=r'get locally stored / last computed mass matrix of solver'),
        StructureFunction(type=TNumpyVector, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemResidual',
            description=r'get locally stored / last computed system residual'),
        StructureFunction(type=TNumpyVector, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetNewtonSolution',
            description=r'get locally stored / last computed solution (=increment) of Newton'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemJacobian',
            args='const py::array_t<Real>& systemJacobian',
            description=r'set locally stored system jacobian of solver; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemMassMatrix',
            args='const py::array_t<Real>& systemMassMatrix',
            description=r'set locally stored mass matrix of solver; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemResidual',
            args='const Vector& systemResidual',
            description=r'set locally stored system residual; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeMassMatrix',
            args='MainSystem& mainSystem, Real scalarFactor=1.',
            description=r'compute systemMassMatrix (multiplied with factor) in cSolver and return mass nODE2 x nODE2 matrix'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianODE2RHS',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1., Index computeLoadsJacobian=0',
            description=r'set systemJacobian to zero, size = (nODE2+nODE1+nAE) x (nODE2+nODE1+nAE), and add jacobian (multiplied with factors for ODE2 and ODE1 coordinates) of ODE2RHS to systemJacobian in cSolver; using (scalarFactor_ODE2=-1,scalarFactor_ODE2=0) gives the stiffness matrix (=derivatives of ODE2 coords) in the nODE2 x nODE2 part, while using (scalarFactor_ODE2=0,scalarFactor_ODE2=-1) gives the damping matrix (= derivatives of ODE2 velocity coordinates) in the same part; a superposition of these two parts makes sense for implicit solvers; if , Index computeLoadsJacobian=0, loads are not considered in the Jacobian computation; for , Index computeLoadsJacobian=1 the ODE2 and ODE1 derivatives of loads are included and for , Index computeLoadsJacobian=2, also the ODE2_t dependencies are added'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianODE1RHS',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1.',
            description=r'ADD jacobian of ODE1RHS (multiplied with factors for ODE2 and ODE1 coordinates) to the according rows (nODE2:nODE2+nODE1) of the exising systemJacobian in cSolver; it requires a prior call to ComputeJacobianODE2RHS(...); the scalar factors scalarFactor_ODE2=0 and scalarFactor_ODE2 are used for the same ODE2 block in the jacobian'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianAE',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1., bool velocityLevel=false',
            description=r"""add jacobian of algebraic equations (multiplied with factor) to systemJacobian in cSolver; the scalarFactors are scaling the derivatives w.r.t. \hac{ODE2} coordinates, ODE2_t (velocity) coordinates and ODE1 coordinates; if velocityLevel == true, the constraints are evaluated at velocity level; the scalar factors scalarFactor_ODE2=0 and scalarFactor_ODE2 are used for the same ODE2 block in the jacobian"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeODE2RHS',
            args='MainSystem& mainSystem',
            description=r"""compute the RHS of \hac{ODE2} equations in systemResidual in range(0,nODE2)"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeAlgebraicEquations',
            args='MainSystem& mainSystem, bool velocityLevel=false',
            description=r'compute the algebraic equations in systemResidual in range(nODE2+nODE1, nODE2+nODE1+nAE)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   MainSolverImplicitSecondOrder   +++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='MainSolverImplicitSecondOrder',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r"""PyBind interface (trampoline) class for dynamic implicit solver. Note that this solver includes the classical Newmark method (set useNewmark True; with option of index 2 reduction) as well as the generalized-alpha method. With the interface, the dynamic implicit solver and its substructures can be accessed via Python. NOTE that except from SolveSystem(...), these functions are only intended for experienced users and they need to be handled with care, as unexpected crashes may happen if used inappropriate. Furthermore, the functions have a lot of overhead (still fast, but performance much lower than internal solver) due to Python interfaces, and should thus be used for small systems. To access the solver in Python, write: \\ 
 \texttt{solver = MainSolverImplicitSecondOrder()} \\ 
and hereafter you can access all data and functions via 'solver'.
 In this solver, user functions are possible to extend the solver at certain parts, while keeping the overal C++ performance. User functions, which are added with SetUserFunction...(...), have the arguments (MainSolver, MainSystem, simulationSettings), except for ComputeNewtonUpdate which adds the initial flag as an additional argument and ComputeNewtonResidual, which returns the scalar residual.""",
    parentClass='MainSolverBase',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='CSolverTimer', cFlags=SFPybind, isLinked=True,
            pythonName='timer',
            cplusplusName='cSolver.timer',
            description=r'timer which measures the CPU time of solver sub functions; note that solver structures can only be written indirectly, e.g.,  timer=dynamicSolver.timer; timer.useTimer = False; dynamicSolver.timer=timer; however, dynamicSolver.timer.useTimer cannot be written.'),
        StructureParameter(type='SolverIterationData', cFlags=SFPybind, isLinked=True,
            pythonName='it',
            cplusplusName='cSolver.it',
            description=r'all information about iterations (steps, discontinuous iteration, newton,...)'),
        StructureParameter(type='SolverConvergenceData', cFlags=SFPybind, isLinked=True,
            pythonName='conv',
            cplusplusName='cSolver.conv',
            description=r'all information about tolerances, errors and residua'),
        StructureParameter(type='SolverOutputData', cFlags=SFPybind, isLinked=True,
            pythonName='output',
            cplusplusName='cSolver.output',
            description=r'output modes and timers for exporting solver information and solution'),
        StructureParameter(type='NewtonSettings', cFlags=SFPybind, isLinked=True,
            pythonName='newton',
            cplusplusName='cSolver.newton',
            description=r'copy of newton settings from timeint or staticSolver'),
        StructureParameter(type=TCSolverImplicitSecondOrderTimeIntUserFunction, cFlags='',
            pythonName='cSolver',
            description=r'link to C++ CSolver, not accessible from Python'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='newmarkBeta',
            cplusplusName='GetCSolverImplicitSecondOrder().newmarkBeta',
            description=r'copy of parameter in timeIntegration.generalizedAlpha'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='newmarkGamma',
            cplusplusName='GetCSolverImplicitSecondOrder().newmarkGamma',
            description=r'copy of parameter in timeIntegration.generalizedAlpha'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='alphaM',
            cplusplusName='GetCSolverImplicitSecondOrder().alphaM',
            description=r'copy of parameter in timeIntegration.generalizedAlpha'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='alphaF',
            cplusplusName='GetCSolverImplicitSecondOrder().alphaF',
            description=r'copy of parameter in timeIntegration.generalizedAlpha'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='spectralRadius',
            cplusplusName='GetCSolverImplicitSecondOrder().spectralRadius',
            description=r'copy of parameter in timeIntegration.generalizedAlpha'),
        StructureParameter(type=TReal, cFlags=SFPybind,
            pythonName='factJacAlgorithmic',
            cplusplusName='GetCSolverImplicitSecondOrder().factJacAlgorithmic',
            description=r'locally computed parameter from generalizedAlpha parameters'),
        StructureParameter(type=Tbool, cFlags='',
            pythonName='isInitialized',
            defaultValue=DVFalse,
            description=r'variable is used to see, if system is initialized ==> avoid crashes; DO not change these variables: can easily lead to crash! '),
        StructureParameter(type=TIndex4, cFlags='',
            pythonName='initializedSystemSizes',
            description=r'index-array contains 4 integers: nODE2, nODE1, nAE and nData of initialization: this guaranties, that no function is called with wrong system sizes; DO not change these variables: can easily lead to crash! '),
        StructureFunction(type='const CSolverBase&', cFlags=SFConst, isVirtual=True,
            pythonName='GetCSolver',
            implementation='return GetCSolverImplicitSecondOrder();',
            description=r'const access to cSolver'),
        StructureFunction(type='CSolverBase&', cFlags='', isVirtual=True,
            pythonName='GetCSolver',
            implementation='return GetCSolverImplicitSecondOrder();',
            description=r'reference access to cSolver'),
        StructureFunction(type='const CSolverImplicitSecondOrderTimeIntUserFunction&', cFlags=SFConst,
            pythonName='GetCSolverImplicitSecondOrder',
            implementation='return cSolver;',
            description=r'const access to cSolver'),
        StructureFunction(type='CSolverImplicitSecondOrderTimeIntUserFunction&', cFlags='',
            pythonName='GetCSolverImplicitSecondOrder',
            implementation='return cSolver;',
            description=r'reference access to cSolver'),
        StructureFunction(type=Tbool, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='CheckInitialized',
            args='const MainSystem& mainSystem',
            description=r'check if MainSolver and MainSystem are correctly initialized ==> otherwise raise SysError'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy,
            pythonName='ComputeLoadFactor',
            args='const SimulationSettings& simulationSettings',
            implementation='return GetCSolverImplicitSecondOrder().ComputeLoadFactor(simulationSettings);',
            description=r'for static solver, this is a factor in interval [0,1]; MUST be overwritten'),
        StructureFunction(type=TNumpyVector, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy,
            pythonName='GetAAlgorithmic',
            description=r'get locally stored / last computed algorithmic accelerations'),
        StructureFunction(type=TNumpyVector, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy,
            pythonName='GetStartOfStepStateAAlgorithmic',
            description=r'get locally stored / last computed algorithmic accelerations at start of step'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionUpdateCurrentTime',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionUpdateCurrentTime(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionInitializeStep',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionInitializeStep(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionFinishStep',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionFinishStep(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionDiscontinuousIteration',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionDiscontinuousIteration(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionNewton',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionNewton(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionComputeNewtonUpdate',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunctionBool& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionComputeNewtonUpdate(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionComputeNewtonResidual',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunctionReal& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionComputeNewtonResidual(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionComputeNewtonJacobian',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunction& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionComputeNewtonJacobian(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type=Tvoid, cFlags=SFPybind,
            pythonName='SetUserFunctionPostNewton',
            args='MainSystem& mainSystem, const MainSolverImplicitSecondOrderUserFunctionReal& userFunction',
            implementation='GetCSolverImplicitSecondOrder().SetUserFunctionPostNewton(this, &mainSystem, userFunction);',
            description=r'set user function'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetErrorString',
            description=r'return error string if solver has not been successful'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSolverName',
            description=r'get solver name - needed for output file header and visualization window'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsStaticSolver',
            description=r'return true, if static solver; needs to be overwritten in derived class'),
        StructureFunction(type=TReal, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSimulationEndTime',
            args='const SimulationSettings& simulationSettings',
            description=r'compute simulation end time (depends on static or time integration solver)'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ReduceStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, Index severity',
            description=r'reduce step size (1..normal, 2..severe problems); return true, if reduction was successful'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IncreaseStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'increase step size if convergence is good'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='HasAutomaticStepSizeControl',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'return true, if solver supports automatic stepsize control, otherwise false'),
        StructureFunction(type=Tbool, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize solverSpecific,data,it,conv; set/compute initial conditions (solver-specific!); initialize output files'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PreInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'pre-initialize for solver specific tasks; called at beginning of InitializeSolver, right after Solver data reset'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverOutput',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize output files; called from InitializeSolver()'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverPreChecks',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'check if system is solvable; initialize dense/sparse computation modes'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverData',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize all data,it,conv; called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverInitialConditions',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'set/compute initial conditions (solver-specific!); called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PostInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'post-initialize for solver specific tasks; called at the end of InitializeSolver'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSystem',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'solve System: InitializeSolver, SolveSteps, FinalizeSolver'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinalizeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write concluding information (timer statistics, messages) and close files'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSteps',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'main solver part: calls multiple InitializeStep(...)/ DiscontinuousIteration(...)/ FinishStep(...); do step reduction if necessary; return true if success, false else'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='UpdateCurrentTime',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'update currentTime (and load factor); MUST be overwritten in special solver class'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize static step / time step; Python-functions; do some outputs, checks, etc.'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinishStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'finish static step / time step; write output of results to file'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='DiscontinuousIteration',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform discontinuousIteration for static step / time step; CALLS ComputeNewtonResidual'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='Newton',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform Newton method for given solver method'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PostNewton',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'call PostNewton for all relevant objects (contact, friction, ... iterations); returns error for discontinuous iteration'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonResidual',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute residual for Newton method (e.g. static or time step); store residual vector in systemResidual and return scalar residual (specific computation may depend on solver types)'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonUpdate',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, initial=true',
            description=r'compute update for currentState from newtonSolution (decrement from residual and jacobian); if initial, this is for the initial update with newtonSolution=0'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonJacobian',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute jacobian for newton method of given solver method; store result in systemJacobian'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteSolutionFileHeader',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique file header, depending on static/ dynamic simulation'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteCoordinatesToFile',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique coordinates solution file'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsVerboseCheck',
            args='Index level',
            description=r'return true, if file or console output is at or above the given level'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='VerboseWrite',
            args='Index level, const std::string& str',
            description=r'write to console and/or file in case of level'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE2size',
            description=r'number of \hac{ODE2} equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE1size',
            description=r"""number of \hac{ODE1} equations in solver (not yet implemented)"""),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetAEsize',
            description=r'number of algebraic equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetDataSize',
            description=r'number of data (history) variables in solver'),
        StructureFunction(type=TNumpyMatrix, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemJacobian',
            description=r'get locally stored / last computed system jacobian of solver'),
        StructureFunction(type=TNumpyMatrix, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemMassMatrix',
            description=r'get locally stored / last computed mass matrix of solver'),
        StructureFunction(type=TNumpyVector, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemResidual',
            description=r'get locally stored / last computed system residual'),
        StructureFunction(type=TNumpyVector, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetNewtonSolution',
            description=r'get locally stored / last computed solution (=increment) of Newton'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemJacobian',
            args='const py::array_t<Real>& systemJacobian',
            description=r'set locally stored system jacobian of solver; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemMassMatrix',
            args='const py::array_t<Real>& systemMassMatrix',
            description=r'set locally stored mass matrix of solver; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemResidual',
            args='const Vector& systemResidual',
            description=r'set locally stored system residual; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeMassMatrix',
            args='MainSystem& mainSystem, Real scalarFactor=1.',
            description=r'compute systemMassMatrix (multiplied with factor) in cSolver and return mass nODE2 x nODE2 matrix'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianODE2RHS',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1., Index computeLoadsJacobian=0',
            description=r'set systemJacobian to zero, size = (nODE2+nODE1+nAE) x (nODE2+nODE1+nAE), and add jacobian (multiplied with factors for ODE2 and ODE1 coordinates) of ODE2RHS to systemJacobian in cSolver; using (scalarFactor_ODE2=-1,scalarFactor_ODE2=0) gives the stiffness matrix (=derivatives of ODE2 coords) in the nODE2 x nODE2 part, while using (scalarFactor_ODE2=0,scalarFactor_ODE2=-1) gives the damping matrix (= derivatives of ODE2 velocity coordinates) in the same part; a superposition of these two parts makes sense for implicit solvers; if , Index computeLoadsJacobian=0, loads are not considered in the Jacobian computation; for , Index computeLoadsJacobian=1 the ODE2 and ODE1 derivatives of loads are included and for , Index computeLoadsJacobian=2, also the ODE2_t dependencies are added'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianODE1RHS',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1.',
            description=r'ADD jacobian of ODE1RHS (multiplied with factors for ODE2 and ODE1 coordinates) to the according rows (nODE2:nODE2+nODE1) of the exising systemJacobian in cSolver; it requires a prior call to ComputeJacobianODE2RHS(...); the scalar factors scalarFactor_ODE2=0 and scalarFactor_ODE2 are used for the same ODE2 block in the jacobian'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeJacobianAE',
            args='MainSystem& mainSystem, Real scalarFactor_ODE2=1., Real scalarFactor_ODE2_t=0., Real scalarFactor_ODE1=1., bool velocityLevel=false',
            description=r"""add jacobian of algebraic equations (multiplied with factor) to systemJacobian in cSolver; the scalarFactors are scaling the derivatives w.r.t. \hac{ODE2} coordinates, ODE2_t (velocity) coordinates and ODE1 coordinates; if velocityLevel == true, the constraints are evaluated at velocity level; the scalar factors scalarFactor_ODE2=0 and scalarFactor_ODE2 are used for the same ODE2 block in the jacobian"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeODE2RHS',
            args='MainSystem& mainSystem',
            description=r"""compute the RHS of \hac{ODE2} equations in systemResidual in range(0,nODE2)"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeODE1RHS',
            args='MainSystem& mainSystem',
            description=r"""compute the RHS of \hac{ODE1} equations in systemResidual in range(0,nODE1)"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeAlgebraicEquations',
            args='MainSystem& mainSystem, bool velocityLevel=false',
            description=r'compute the algebraic equations in systemResidual in range(nODE2+nODE1, nODE2+nODE1+nAE)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   MainSolverExplicit   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='MainSolverExplicit',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r"""PyBind interface (trampoline) class for dynamic explicit solver. Note that this solver includes the 1st order explicit Euler scheme and the 4th order Runge-Kutta scheme with 5th order error estimation (DOPRI5). With the interface, the solver and its substructures can be accessed via Python. NOTE that except from SolveSystem(...), these functions are only intended for experienced users and they need to be handled with care, as unexpected crashes may happen if used inappropriate. Furthermore, the functions have a lot of overhead (still fast, but performance much lower than internal solver) due to Python interfaces, and should thus be used for small systems. To access the solver in Python, write \\ 
 \texttt{solver = MainSolverExplicit()} \\ 
and hereafter you can access all data and functions via 'solver'.
 In this solver, no user functions are possible, but you can use SolverImplicitSecondOrder instead (turning off Newton gives explicit scheme ...).""",
    parentClass='MainSolverBase',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='CSolverTimer', cFlags=SFPybind, isLinked=True,
            pythonName='timer',
            cplusplusName='cSolver.timer',
            description=r'timer which measures the CPU time of solver sub functions'),
        StructureParameter(type='SolverIterationData', cFlags=SFPybind, isLinked=True,
            pythonName='it',
            cplusplusName='cSolver.it',
            description=r'all information about iterations (steps, discontinuous iteration, newton,...)'),
        StructureParameter(type='SolverConvergenceData', cFlags=SFPybind, isLinked=True,
            pythonName='conv',
            cplusplusName='cSolver.conv',
            description=r'all information about tolerances, errors and residua'),
        StructureParameter(type='SolverOutputData', cFlags=SFPybind, isLinked=True,
            pythonName='output',
            cplusplusName='cSolver.output',
            description=r'output modes and timers for exporting solver information and solution'),
        StructureParameter(type=TCSolverExplicitTimeInt, cFlags='',
            pythonName='cSolver',
            description=r'link to C++ CSolver, not accessible from Python'),
        StructureParameter(type=Tbool, cFlags='',
            pythonName='isInitialized',
            description=r'variable is used to see, if system is initialized ==> avoid crashes; DO not change these variables: can easily lead to crash! '),
        StructureParameter(type=TIndex4, cFlags='',
            pythonName='initializedSystemSizes',
            description=r'index-array contains 4 integers: nODE2, nODE1, nAE and nData of initialization: this guaranties, that no function is called with wrong system sizes; DO not change these variables: can easily lead to crash! '),
        StructureFunction(type='', cFlags=SFNoDictType,
            pythonName='MainSolverExplicit',
            description=r'constructor, in order to set valid state (settings not initialized at beginning)'),
        StructureFunction(type='const CSolverBase&', cFlags=SFConst, isVirtual=True,
            pythonName='GetCSolver',
            implementation='return cSolver;',
            description=r'const access to cSolver'),
        StructureFunction(type='CSolverBase&', cFlags='', isVirtual=True,
            pythonName='GetCSolver',
            implementation='return cSolver;',
            description=r'reference access to cSolver'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy,
            pythonName='ComputeLoadFactor',
            args='const SimulationSettings& simulationSettings',
            implementation='return cSolver.ComputeLoadFactor(simulationSettings);',
            description=r'for static solver, this is a factor in interval [0,1]; MUST be overwritten'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybind,
            pythonName='GetNumberOfStages',
            implementation='return cSolver.nStages;',
            description=r'return number of stages in current method'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybind,
            pythonName='GetMethodOrder',
            implementation='return cSolver.rk.orderMethod;',
            description=r'return order of method (higher value in methods with automatic step size, e.g., DOPRI5=5)'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetErrorString',
            description=r'return error string if solver has not been successful'),
        StructureFunction(type='std::string', cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSolverName',
            description=r'get solver name - needed for output file header and visualization window'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsStaticSolver',
            description=r'return true, if static solver; needs to be overwritten in derived class'),
        StructureFunction(type=TReal, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSimulationEndTime',
            args='const SimulationSettings& simulationSettings',
            description=r'compute simulation end time (depends on static or time integration solver)'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ReduceStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, Index severity',
            description=r'reduce step size (1..normal, 2..severe problems); return true, if reduction was successful'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IncreaseStepSize',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'increase step size if convergence is good'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='HasAutomaticStepSizeControl',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'return true, if solver supports automatic stepsize control, otherwise false'),
        StructureFunction(type=Tbool, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize solverSpecific,data,it,conv; set/compute initial conditions (solver-specific!); initialize output files'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PreInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'pre-initialize for solver specific tasks; called at beginning of InitializeSolver, right after Solver data reset'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverOutput',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize output files; called from InitializeSolver()'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverPreChecks',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'check if system is solvable; initialize dense/sparse computation modes'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverData',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize all data,it,conv; called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeSolverInitialConditions',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'set/compute initial conditions (solver-specific!); called from InitializeSolver()'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='PostInitializeSolverSpecific',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'post-initialize for solver specific tasks; called at the end of InitializeSolver'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSystem',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'solve System: InitializeSolver, SolveSteps, FinalizeSolver'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinalizeSolver',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write concluding information (timer statistics, messages) and close files'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SolveSteps',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'main solver part: calls multiple InitializeStep(...)/ DiscontinuousIteration(...)/ FinishStep(...); do step reduction if necessary; return true if success, false else'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='UpdateCurrentTime',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'update currentTime (and load factor); MUST be overwritten in special solver class'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='InitializeStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'initialize static step / time step; Python-functions; do some outputs, checks, etc.'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='FinishStep',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'finish static step / time step; write output of results to file'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='DiscontinuousIteration',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform discontinuousIteration for static step / time step; CALLS ComputeNewtonResidual'),
        StructureFunction(type=Tbool, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='Newton',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'perform Newton method for given solver method'),
        StructureFunction(type=TReal, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonResidual',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute residual for Newton method (e.g. static or time step); store residual vector in systemResidual and return scalar residual (specific computation may depend on solver types)'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonUpdate',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings, initial=true',
            description=r'compute update for currentState from newtonSolution (decrement from residual and jacobian); if initial, this is for the initial update with newtonSolution=0'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeNewtonJacobian',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'compute jacobian for newton method of given solver method; store result in systemJacobian'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteSolutionFileHeader',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique file header, depending on static/ dynamic simulation'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='WriteCoordinatesToFile',
            args='MainSystem& mainSystem, const SimulationSettings& simulationSettings',
            description=r'write unique coordinates solution file'),
        StructureFunction(type=Tbool, cFlags=SFConst+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='IsVerboseCheck',
            args='Index level',
            description=r'return true, if file or console output is at or above the given level'),
        StructureFunction(type=Tvoid, cFlags=SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='VerboseWrite',
            args='Index level, const std::string& str',
            description=r'write to console and/or file in case of level'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE2size',
            description=r'number of \hac{ODE2} equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetODE1size',
            description=r"""number of \hac{ODE1} equations in solver (not yet implemented)"""),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetAEsize',
            description=r'number of algebraic equations in solver'),
        StructureFunction(type=TIndex, cFlags=SFConst+SFPybindArgs+SFPybind, isVirtual=True, isLinked=True,
            pythonName='GetDataSize',
            description=r'number of data (history) variables in solver'),
        StructureFunction(type=TNumpyMatrix, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemMassMatrix',
            description=r'get locally stored / last computed mass matrix of solver'),
        StructureFunction(type=TNumpyVector, cFlags=SFConst+SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='GetSystemResidual',
            description=r'get locally stored / last computed system residual'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemMassMatrix',
            args='const py::array_t<Real>& systemMassMatrix',
            description=r'set locally stored mass matrix of solver; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='SetSystemResidual',
            args='const Vector& systemResidual',
            description=r'set locally stored system residual; must have size nODE2+nODE1+nAE'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeMassMatrix',
            args='MainSystem& mainSystem, Real scalarFactor=1.',
            description=r'compute systemMassMatrix (multiplied with factor) in cSolver and return mass matrix'),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeODE2RHS',
            args='MainSystem& mainSystem',
            description=r"""compute the RHS of \hac{ODE2} equations in systemResidual in range(0,nODE2)"""),
        StructureFunction(type=Tvoid, cFlags=SFNoDictType+SFPybindArgs+SFPybind+SFReturnCopy, isVirtual=True, isLinked=True,
            pythonName='ComputeODE1RHS',
            args='MainSystem& mainSystem',
            description=r"""compute the RHS of \hac{ODE1} equations in systemResidual in range(0,nODE1)"""),
        ],
    ))
