#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# SolverData definitions
#
# Details:  6 definitions; the input of the generators.
#           This IS Python: import it and read "definitions", a list of dicts.
#
#           ORDER MATTERS. The generators emit in the order the definitions appear,
#           and the generated C++/pybind/RST is compared byte-for-byte, so
#           reordering this list changes generated files. Append at the end unless
#           you mean to reorder.
#
#           Only descriptions, LaTeX and C++ code are raw strings; every other field
#           is a name, a flag constant or a short literal and needs no escaping.
#
#           The constants come from definitionTypes.py, which is hand-written: a
#           value used here with no constant there stops the emit and says what to
#           add, so the two can never drift apart silently.
#
#           DESCRIPTIONS: read definitions/README.md, section "Writing a
#           description", before writing or changing one - what the text may
#           contain, and how it is checked.
#
# Contents: CSolverTimer, SolverLocalData, SolverIterationData, SolverConvergenceData, SolverOutputData, SolverFileData
#
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

from definitionTypes import *

definitions = []
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   CSolverTimer   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='CSolverTimer',
    writeFile='CSolverStructures.h',
    addDictionaryAccess=False,
    appendToFile=False,
    classDescription=r'Structure for timing in solver. Each Real variable is used to measure the CPU time which certain parts of the solver need. This structure is only active if the code is not compiled with the __FAST_EXUDYN_LINALG option and if displayComputationTime is set True. Timings will only be filled, if useTimer is True.',
    sectionText=r"""
<!--++++++++++++++++++++++++++++++++++++++ -->

(sec-solversubstructures)=
## Solver substructures

This section includes structures contained in the solver, which can be accessed via the Python interface during solution or for building a customized solver in Python.
There is plenty of possibilities to interact with the solvers, being it the extraction of data at the end (such as .it or .conv), computation of mass matrix or system matrices, and finally the modification of solver structures (which may have effect or not). In any case, there is no full description for all these methods and the user must always consider the according C++ function to verify the desired behavior.
""",
    writePybindIncludes=True,
    members=[
        StructureParameter(type=Tbool, 
            pythonName='useTimer',
            defaultValue=True,
            description=r'flag to decide, whether the timer is used (true) or not'),
        StructureParameter(type=TReal, 
            pythonName='total',
            defaultValue=0.,
            description=r'total time measured between start and end of computation (static/dynamics)'),
        StructureParameter(type=TReal, 
            pythonName='factorization',
            defaultValue=0.,
            description=r'solve or inverse'),
        StructureParameter(type=TReal, 
            pythonName='newtonIncrement',
            defaultValue=0.,
            description=r'Jac$^{-1}$ * RHS; backsubstitution'),
        StructureParameter(type=TReal, 
            pythonName='integrationFormula',
            defaultValue=0.,
            description=r'time spent for evaluation of integration formulas'),
        StructureParameter(type=TReal, 
            pythonName='ODE2RHS',
            defaultValue=0.,
            description=r'time for residual evaluation of ABRV:ODE2 right-hand-side'),
        StructureParameter(type=TReal, 
            pythonName='ODE1RHS',
            defaultValue=0.,
            description=r'time for residual evaluation of ABRV:ODE1 right-hand-side'),
        StructureParameter(type=TReal, 
            pythonName='AERHS',
            defaultValue=0.,
            description=r'time for residual evaluation of algebraic equations right-hand-side'),
        StructureParameter(type=TReal, 
            pythonName='totalJacobian',
            defaultValue=0.,
            description=r'time for all jacobian computations'),
        StructureParameter(type=TReal, 
            pythonName='jacobianODE1',
            defaultValue=0.,
            description=r"""jacobian w.r.t. coordinates of ABRV:ODE1 equations (not counted in sum)"""),
        StructureParameter(type=TReal, 
            pythonName='jacobianODE2',
            defaultValue=0.,
            description=r"""jacobian w.r.t. coordinates of ABRV:ODE2 equations (not counted in sum)"""),
        StructureParameter(type=TReal, 
            pythonName='jacobianODE2_t',
            defaultValue=0.,
            description=r"""jacobian w.r.t. coordinates_t of ABRV:ODE2 equations (not counted in sum)"""),
        StructureParameter(type=TReal, 
            pythonName='jacobianAE',
            defaultValue=0.,
            description=r'jacobian of algebraic equations (not counted in sum)'),
        StructureParameter(type=TReal, 
            pythonName='massMatrix',
            defaultValue=0.,
            description=r'mass matrix computation'),
        StructureParameter(type=TReal, 
            pythonName='reactionForces',
            defaultValue=0.,
            description=r'CqT * lambda'),
        StructureParameter(type=TReal, 
            pythonName='postNewton',
            defaultValue=0.,
            description=r'discontinuous iteration / PostNewtonStep'),
        StructureParameter(type=TReal, 
            pythonName='errorEstimator',
            defaultValue=0.,
            description=r'for explicit solvers, additional evaluation'),
        StructureParameter(type=TReal, 
            pythonName='writeSolution',
            defaultValue=0.,
            description=r'time for writing solution'),
        StructureParameter(type=TReal, 
            pythonName='overhead',
            defaultValue=0.,
            description=r'overhead, such as initialization, copying and some matrix-vector multiplication'),
        StructureParameter(type=TReal, 
            pythonName='realtimeIdleCPU',
            defaultValue=0.,
            description=r'time waited for next frame to compute and draw if timeIntegration.realtime.active is True'),
        StructureParameter(type=TReal, 
            pythonName='python',
            defaultValue=0.,
            description=r'time spent for Python functions'),
        StructureParameter(type=TReal, 
            pythonName='visualization',
            defaultValue=0.,
            description=r'time spent for visualization in computation thread'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='Reset',
            args='bool useSolverTimer',
            implementation='*this = CSolverTimer(); useTimer = useSolverTimer;',
            description=r'reset solver timings to initial state by assigning default values; useSolverTimer sets the useTimer flag'),
        StructureFunction(type=TReal, cFlags=SFConst+SFReturnCopy, isVirtual=False,
            pythonName='Sum',
            description=r'compute sum of all timers (except for those counted multiple, e.g., jacobians'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='StartTimer',
            args='Real& value',
            implementation='if (useTimer) { value -= EXUstd::GetTimeInSeconds();}',
            description=r'start timer function for a given variable; subtracts current CPU time from value'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='StopTimer',
            args='Real& value',
            implementation='if (useTimer) { value += EXUstd::GetTimeInSeconds();}',
            description=r'stop timer function for a given variable; adds current CPU time to value'),
        StructureFunction(type=TString, cFlags=SFConst+SFReturnCopy, isVirtual=False,
            pythonName='ToString',
            description=r'converts the current timings to a string'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolverLocalData   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolverLocalData',
    writeFile='CSolverStructures.h',
    addConstructor=r"""    SetLinearSolverType(LinearSolverType::EXUdense); //for safety, data is linked initially\n""",
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Solver local data structure for solution vectors, system matrices and temporary vectors and data structures.',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TIndex, 
            pythonName='nODE2',
            defaultValue=0,
            description=r'number of second order ordinary diff. eq. coordinates'),
        StructureParameter(type=TIndex, 
            pythonName='nODE1',
            defaultValue=0,
            description=r'number of first order ordinary diff. eq. coordinates'),
        StructureParameter(type=TIndex, 
            pythonName='nAE',
            defaultValue=0,
            description=r'number of algebraic coordinates'),
        StructureParameter(type=TIndex, 
            pythonName='nData',
            defaultValue=0,
            description=r'number of data coordinates'),
        StructureParameter(type=TIndex, 
            pythonName='nSys',
            defaultValue=0,
            description=r'number of system (unknown) coordinates = nODE2+nODE1+nAE'),
        StructureParameter(type=TIndex, 
            pythonName='startAE',
            defaultValue=0,
            description=r'start of algebraic coordinates, but set to zero if nAE==0'),
        StructureParameter(type='GeneralMatrix*', cFlags=SFNoPybind,
            pythonName='systemJacobian',
            defaultValue='nullptr',
            description=r'link to dense or sparse system jacobian'),
        StructureParameter(type='GeneralMatrix*', cFlags=SFNoPybind,
            pythonName='systemMassMatrix',
            defaultValue='nullptr',
            description=r'link to dense or sparse system mass matrix; in explicit solver, after a step, this will contain the factorized mass matrix'),
        StructureParameter(type='GeneralMatrix*', cFlags=SFNoPybind,
            pythonName='jacobianAE',
            defaultValue='nullptr',
            description=r'link to dense or sparse algebraic equations jacobian'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='systemResidual',
            defaultValue=NoDefaultValue,
            description=r'system residual vector (vectors will be linked to this vector!)'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='newtonSolution',
            defaultValue=NoDefaultValue,
            description=r'Newton decrement (computed from residual and jacobian)'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='tempODE2',
            defaultValue=NoDefaultValue,
            description=r"""temporary vector for ABRV:ODE2 quantities; use in initial accelerations and during Newton"""),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='temp2ODE2',
            defaultValue=NoDefaultValue,
            description=r"""second temporary vector for ABRV:ODE2 quantities; use in static computation"""),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='tempODE2F0',
            defaultValue=NoDefaultValue,
            description=r'temporary vector for ABRV:ODE2 Jacobian'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='tempODE2F1',
            defaultValue=NoDefaultValue,
            description=r'temporary vector for ABRV:ODE2 Jacobian'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='tempODE1F0',
            defaultValue=NoDefaultValue,
            description=r'temporary vector for ABRV:ODE1 Jacobian'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='tempODE1F1',
            defaultValue=NoDefaultValue,
            description=r'temporary vector for ABRV:ODE1 Jacobian'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='startOfStepStateAAlgorithmic',
            defaultValue=NoDefaultValue,
            description=r'additional term needed for generalized alpha (startOfStep state)'),
        StructureParameter(type=TResizableVectorParallel, 
            pythonName='aAlgorithmic',
            defaultValue=NoDefaultValue,
            description=r'additional term needed for generalized alpha (current state)'),
        StructureParameter(type=TTemporaryComputationData, cFlags=SFNoPybind,
            pythonName='tempCompData',
            defaultValue=NoDefaultValue,
            description=r'temporary data used during item-related residual and jacobian computation; duplicated for serial computation, will be removed in future'),
        StructureParameter(type=TTemporaryComputationDataArray, cFlags=SFNoPybind,
            pythonName='tempCompDataArray',
            defaultValue=NoDefaultValue,
            description=r'temporary data per thread, used during item-related residual and jacobian computation; for parallel computation'),
        StructureParameter(type=TLinearSolverType, cFlags=SFNoPybind, fromParent=True,
            pythonName='linearSolverType',
            defaultValue=NoDefaultValue,
            description=r'contains linear solver type value; cannot be accessed directly, because a change requires new linking of system matrices'),
        StructureParameter(type=TGeneralMatrixEXUdense, cFlags=SFNoPybind, fromParent=True,
            pythonName='systemJacobianDense',
            defaultValue=NoDefaultValue,
            description=r'dense system jacobian'),
        StructureParameter(type=TGeneralMatrixEXUdense, cFlags=SFNoPybind, fromParent=True,
            pythonName='systemMassMatrixDense',
            defaultValue=NoDefaultValue,
            description=r'dense mass matrix'),
        StructureParameter(type=TGeneralMatrixEXUdense, cFlags=SFNoPybind, fromParent=True,
            pythonName='jacobianAEdense',
            defaultValue=NoDefaultValue,
            description=r'dense ABRV:AE jacobian'),
        StructureParameter(type=TGeneralMatrixEigenSparse, cFlags=SFNoPybind, fromParent=True,
            pythonName='systemJacobianSparse',
            defaultValue=NoDefaultValue,
            description=r'sparse system jacobian'),
        StructureParameter(type=TGeneralMatrixEigenSparse, cFlags=SFNoPybind, fromParent=True,
            pythonName='systemMassMatrixSparse',
            defaultValue=NoDefaultValue,
            description=r'sparse mass matrix'),
        StructureParameter(type=TGeneralMatrixEigenSparse, cFlags=SFNoPybind, fromParent=True,
            pythonName='jacobianAEsparse',
            defaultValue=NoDefaultValue,
            description=r'sparse ABRV:AE jacobian'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='CleanUpMemory',
            description=r'if desired, temporary data is cleaned up to safe memory'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='SetLinearSolverType',
            args='LinearSolverType linearSolverType, bool reuseAnalyzedPattern=false, bool ignoreSingularJacobian=false, Real pivotThreshold=0.',
            description=r'set linear solver type and matrix version: links system matrices to according dense/sparse versions and with option for singular jacobian (redundant constraints)'),
        StructureFunction(type=TLinearSolverType, cFlags=SFConst+SFReturnCopy, isVirtual=False,
            pythonName='GetLinearSolverType',
            implementation='return linearSolverType;',
            description=r'return current linear solver type (dense/sparse)'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolverIterationData   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolverIterationData',
    writeFile='CSolverStructures.h',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Solver internal structure for counters, steps, step size, time, etc.; solution vectors, residuals, etc. are SolverLocalData. The given default values are overwritten by the simulationSettings when initializing the solver.',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=TReal, 
            pythonName='maxStepSize',
            defaultValue=0.,
            description=r'constant or maximum stepSize'),
        StructureParameter(type=TReal, 
            pythonName='minStepSize',
            defaultValue=0.,
            description=r'minimum stepSize for static/dynamic solver; only used, if automaticStepSize is activated'),
        StructureParameter(type=TReal, 
            pythonName='initialStepSize',
            defaultValue=1e-6,
            description=r'initial stepSize for dynamic solver; only used, if automaticStepSize is activated'),
        StructureParameter(type=TReal, 
            pythonName='lastStepSize',
            defaultValue=0.,
            description=r'stepSize suggested from last step or by initial step size; only used, if automaticStepSize is activated'),
        StructureParameter(type=TReal, 
            pythonName='currentStepSize',
            defaultValue=0.,
            description=r'stepSize of current step'),
        StructureParameter(type=TReal, 
            pythonName='recommendedStepSize',
            defaultValue=-1.,
            description=r'recommended step size $h_{recom}$ after PostNewton(...): $h_{recom} < 0$: no recommendation, $h_{recom}==0$: use minimum step size, $h_{recom}>0$: use specific step size, if no smaller size requested by other reason'),
        StructureParameter(type=TIndex, 
            pythonName='numberOfSteps',
            defaultValue=0,
            description=r'number of time steps (if fixed size); $n$'),
        StructureParameter(type=TIndex, 
            pythonName='currentStepIndex',
            defaultValue=0,
            description=r'current step index; $i$'),
        StructureParameter(type=Tbool, 
            pythonName='adaptiveStep',
            defaultValue=True,
            description=r'True: the step size may be reduced if step fails; no automatic stepsize control'),
        StructureParameter(type=Tbool, 
            pythonName='automaticStepSize',
            defaultValue=True,
            description=r'True: if timeIntegration.automaticStepSize == True AND chosen integrators supports automatic step size control (e.g., DOPRI5); False: constant step size used (step may be reduced if adaptiveStep=True)'),
        StructureParameter(type=TReal, 
            pythonName='currentTime',
            defaultValue=0.,
            description=r'holds the current simulation time, copy of state.current.time; interval is [startTime,tEnd]; in static solver, duration is loadStepDuration'),
        StructureParameter(type=TReal, 
            pythonName='startTime',
            defaultValue=0.,
            description=r'time at beginning of time integration'),
        StructureParameter(type=TReal, 
            pythonName='endTime',
            defaultValue=0.,
            description=r'end time of static/dynamic solver'),
        StructureParameter(type=TIndex, 
            pythonName='discontinuousIteration',
            defaultValue=0,
            description=r'number of current discontinuous iteration'),
        StructureParameter(type=TIndex, 
            pythonName='newtonSteps',
            defaultValue=0,
            description=r'number of current newton steps'),
        StructureParameter(type=TIndex, 
            pythonName='newtonStepsCount',
            defaultValue=0,
            description=r'count total Newton steps'),
        StructureParameter(type=TIndex, 
            pythonName='newtonJacobiCount',
            defaultValue=0,
            description=r'count total Newton jacobian computations'),
        StructureParameter(type=TIndex, 
            pythonName='rejectedModifiedNewtonSteps',
            defaultValue=0,
            description=r'count the number of rejected modified Newton steps (switch to full Newton)'),
        StructureParameter(type=TIndex, 
            pythonName='discontinuousIterationsCount',
            defaultValue=0,
            description=r'count total number of discontinuous iterations (min. 1 per step)'),
        StructureParameter(type=TIndex, 
            pythonName='rejectedAutomaticStepSizeSteps',
            defaultValue=0,
            description=r'count the number of rejected steps in case of automatic step size control (rejected steps are repeated with smaller step size)'),
        StructureParameter(type=TReal, 
            pythonName='automaticStepSizeError',
            defaultValue=0,
            description=r"""estimated error (relative to atol + rtol*solution) of last step; must be $\le 1$  for a step to be accepted"""),
        StructureFunction(type=TString, cFlags=SFConst+SFReturnCopy, isVirtual=False,
            pythonName='ToString',
            description=r'convert iteration statistics to string; used for displayStatistics option'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolverConvergenceData   +++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolverConvergenceData',
    writeFile='CSolverStructures.h',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Solver internal structure for convergence information: residua, iteration loop errors and error flags. For detailed behavior of these flags, visit the source code!',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=Tbool, 
            pythonName='stepReductionFailed',
            defaultValue=False,
            description=r'true, if iterations over time/static steps failed (finally, cannot be recovered)'),
        StructureParameter(type=Tbool, 
            pythonName='discontinuousIterationSuccessful',
            defaultValue=True,
            description=r'true, if last discontinuous iteration had success (failure may be recovered by adaptive step)'),
        StructureParameter(type=Tbool, 
            pythonName='linearSolverFailed',
            defaultValue=False,
            description=r'true, if linear solver failed to factorize'),
        StructureParameter(type=TIndex, 
            pythonName='linearSolverCausingRow',
            defaultValue=-1,
            description=r'-1 if successful, 0 ... n-1, the system equation (=coordinate) index which may have caused the problem, at which the linear solver failed'),
        StructureParameter(type=Tbool, 
            pythonName='stopNewton',
            defaultValue=False,
            description=r'set true by Newton, if Newton was stopped, e.g., because of exceeding iterations or linear solver failed'),
        StructureParameter(type=Tbool, 
            pythonName='newtonConverged',
            defaultValue=False,
            description=r'true, if Newton has (finally) converged'),
        StructureParameter(type=Tbool, 
            pythonName='newtonSolutionDiverged',
            defaultValue=False,
            description=r'true, if Newton diverged (may be recovered)'),
        StructureParameter(type=Tbool, 
            pythonName='jacobianUpdateRequested',
            defaultValue=True,
            description=r'true, if a jacobian update is requested in modified Newton (determined in previous step)'),
        StructureParameter(type=Tbool, 
            pythonName='massMatrixNotInvertible',
            defaultValue=False,
            description=r'true, if mass matrix is not invertable during initialization or solution (explicit solver)'),
        StructureParameter(type=TReal, 
            pythonName='discontinuousIterationError',
            defaultValue=0.,
            description=r'error of discontinuous iterations (contact, friction, ...) outside of Newton iteration'),
        StructureParameter(type=TReal, 
            pythonName='residual',
            defaultValue=0.,
            description=r'current Newton residual'),
        StructureParameter(type=TReal, 
            pythonName='lastResidual',
            defaultValue=0.,
            description=r'last Newton residual to determine contractivity'),
        StructureParameter(type=TReal, 
            pythonName='contractivity',
            defaultValue=0.,
            description=r'Newton contractivity = geometric decay of error in every step'),
        StructureParameter(type=TReal, 
            pythonName='errorCoordinateFactor',
            defaultValue=1.,
            description=r'factor may include the number of system coordinates to reduce the residual'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='InitializeData',
            implementation='*this = SolverConvergenceData();',
            description=r'initialize SolverConvergenceData by assigning default values'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolverOutputData   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolverOutputData',
    writeFile='CSolverStructures.h',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Solver internal structure for output modes, output timers and counters.',
    writePybindIncludes=True,
    members=[
        StructureParameter(type=Tbool, 
            pythonName='finishedSuccessfully',
            defaultValue=False,
            description=r'flag is false until solver functions SolveSteps)...) or SolveSystem(...) finished successfully (can be used as external trigger)'),
        StructureParameter(type=Tbool, 
            pythonName='initializationSuccessful',
            defaultValue=False,
            description=r'flag is set during call to InitializeSolver(...); reasons for failure are multiple, either inconsistent solver settings are used, files cannot be written (file locked), or initial conditions could not be computed '),
        StructureParameter(type=Tbool, 
            pythonName='simulationStoppedByUser',
            defaultValue=False,
            description=r'flag (initialized false) is set true when user stops the simulation (press Q, Escape, etc.)'),
        StructureParameter(type=Tbool, 
            pythonName='simulationStoppedByUserFunction',
            defaultValue=False,
            description=r'flag (initialized false) is set true when a user function (PreStep, PostNewton, etc.) sends termination signal'),
        StructureParameter(type=Tbool, 
            pythonName='simulationTimeout',
            defaultValue=False,
            description=r'flag (initialized false) is set true when exudyn.special.solver.timeout is reached (and timeout is >= 0)'),
        StructureParameter(type=TIndex, 
            pythonName='verboseMode',
            defaultValue=0,
            description=r'this is a copy of the solvers verboseMode used for console output'),
        StructureParameter(type=TIndex, 
            pythonName='verboseModeFile',
            defaultValue=0,
            description=r'this is a copy of the solvers verboseModeFile used for file'),
        StructureParameter(type=TIndex, 
            pythonName='stepInformation',
            defaultValue=0,
            description=r'this is a copy of the solvers stepInformation used for console output'),
        StructureParameter(type=Tbool, 
            pythonName='writeToSolutionFile',
            defaultValue=False,
            description=r'if false, no solution file is generated and no file is written'),
        StructureParameter(type=Tbool, 
            pythonName='writeToSolverFile',
            defaultValue=False,
            description=r'if false, no solver output file is generated and no file is written'),
        StructureParameter(type=TResizableVector, cFlags=SFNoPybind,
            pythonName='sensorValuesTemp',
            defaultValue=NoDefaultValue,
            description=r'temporary vector for per sensor values (overwritten for every sensor; usually contains last sensor values)'),
        StructureParameter(type=TResizableVector, cFlags=SFNoPybind,
            pythonName='sensorValuesTemp2',
            defaultValue=NoDefaultValue,
            description=r'additional temporary vector for per sensor values (overwritten for every sensor; usually contains time+last sensor values)'),
        StructureParameter(type=TReal, 
            pythonName='lastSolutionWritten',
            defaultValue=0.,
            description=r'simulation time when last solution has been written'),
        StructureParameter(type=TReal, 
            pythonName='lastSensorsWritten',
            defaultValue=0.,
            description=r'simulation time when last sensors have been written'),
        StructureParameter(type=TReal, 
            pythonName='lastImageRecorded',
            defaultValue=0.,
            description=r'simulation time when last image has been recorded'),
        StructureParameter(type=TReal,
            pythonName='lastRestartWritten',
            defaultValue=0.,
            description=r'simulation time when the restart file has been written last'),
        StructureParameter(type=TReal,
            pythonName='restartTime',
            defaultValue=-1.,
            description=r'simulation time from which the solver continued with the restart file (solution.restart.continueIfAvailable); -1 if it started at the start time'),
        StructureParameter(type=TReal, 
            pythonName='cpuStartTime',
            defaultValue=0.,
            description=r'CPU start time of computation (starts counting at computation of initial conditions)'),
        StructureParameter(type=TReal, 
            pythonName='cpuSolverStartTime',
            defaultValue=0.,
            description=r'CPU start time of main solver (not including initial conditions); cpuSolverStartTime-cpuStartTime gives time for initialization'),
        StructureParameter(type=TReal, 
            pythonName='cpuLastTimePrinted',
            defaultValue=0.,
            description=r'CPU time when output has been printed last time'),
        StructureParameter(type=TIndex, 
            pythonName='lastVerboseStepIndex',
            defaultValue=0,
            description=r'step index when last time written to console (or file)'),
        StructureParameter(type=TIndex, 
            pythonName='lastNewtonStepsCount',
            defaultValue=0,
            description=r'newton steps count when written to console (or file) last time'),
        StructureParameter(type=TIndex, 
            pythonName='lastNewtonJacobiCount',
            defaultValue=0,
            description=r'jacobian update count when written to console (or file) last time'),
        StructureParameter(type=TIndex, 
            pythonName='lastDiscontinuousIterationsCount',
            defaultValue=0,
            description=r'discontinuous iterations count when written to console (or file) last time'),
        StructureParameter(type=TIndex, 
            pythonName='numberOfThreadsUsed',
            defaultValue=1,
            description=r'number of threads that have been used in simulation'),
        StructureParameter(type=TIndex, 
            pythonName='multiThreadingMode',
            defaultValue=0,
            description=r'multithreading mode that has been used: 0=None (serial), 1=multithreading, 2=multithreading with load balancing; (modes new since 2025-06, V1.9.198)'),
        StructureFunction(type=Tvoid, isVirtual=False,
            pythonName='InitializeData',
            implementation='*this = SolverOutputData();',
            description=r'initialize SolverOutputData by assigning default values'),
        ],
    ))

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++   SolverFileData   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
definitions.append(StructureDefinition(
    className='SolverFileData',
    writeFile='CSolverStructures.h',
    addDictionaryAccess=False,
    appendToFile=True,
    classDescription=r'Solver internal structure for output files. This structure is not linked to pybind, because std::ofstream is not supported.',
    writePybindIncludes=True,
    members=[
        StructureParameter(type='std::ofstream', cFlags=SFNoPybind,
            pythonName='solutionFile',
            defaultValue=NoDefaultValue,
            description=r'solution file with coordinate data'),
        StructureParameter(type='std::ofstream', cFlags=SFNoPybind,
            pythonName='solverFile',
            defaultValue=NoDefaultValue,
            description=r'file with detailed solver information'),
        StructureParameter(type='std::vector<std::ofstream*>', cFlags=SFNoPybind,
            pythonName='sensorFileList',
            defaultValue=NoDefaultValue,
            description=r'files for sensor output; the ofstream list corresponds exactly to the sensors in the computationalSystem (i.e., sensorFileList[0] is the ofstream for sensor 0, etc.); file lists need to be closed and deleted at end of simulation!'),
        StructureParameter(type='ExuFile::BinaryFileSettings', cFlags=SFNoPybind,
            pythonName='binaryFileSettings',
            defaultValue=NoDefaultValue,
            description=r'settings for binary file write mode'),
        ],
    ))
