/** ***********************************************************************************************
* @brief        Implementation for MarkerNodeODE1Coordinate
*
* @author       Gerstmayr Johannes
* @date         2019-06-13 (generated)
*
* @copyright    This file is part of Exudyn. Exudyn is free software: you can redistribute it and/or modify it under the terms of the Exudyn license. See "LICENSE.txt" for more details.
* @note         Bug reports, support and further information:
                - email: johannes.gerstmayr@uibk.ac.at
                - weblink: https://github.com/jgerstmayr/EXUDYN
                
************************************************************************************************ */

#include "Main/CSystemData.h"
#include "Autogenerated/CMarkerNodeODE1Coordinate.h"


void CMarkerNodeODE1Coordinate::GetPosition(const CSystemData& cSystemData, Vector3D& position, ConfigurationType configuration) const
{
	//ODE1 nodes do not provide position information; CMarkerNodeODE1Coordinate currently not drawn
	position = Vector3D(0.);
}

void CMarkerNodeODE1Coordinate::ComputeMarkerData(const CSystemData& cSystemData, bool computeJacobian, MarkerData& markerData) const
{
	//A marker 'NodeCoordinate' must be attached to the ODE1 part of a node
	//always markerData.value is written
	
	Index n = cSystemData.GetCNodes()[parameters.nodeNumber]->GetNumberOfODE1Coordinates(); //works already for both cases
	if (n) //access to GetCurrentCoordinateVector only if not ground node (which has no real coordinates, but it is allows to constrain to a ground node 'coordinate' being always zero
	{
		markerData.velocityAvailable = false; //never available for ODE2
		markerData.vectorValue.SetVector({ cSystemData.GetCNodes()[parameters.nodeNumber]->GetCurrentCoordinateVector()[parameters.coordinate] }); //works for all coordinates

		if (computeJacobian)
		{
			//zero-vector with 1 at parameters.coordinate => this is also done for velocity markers; this might not work for non-holonomic constraints
			markerData.jacobian.SetNumberOfRowsAndColumns(1, n);
			markerData.jacobian.SetAll(0.);
			markerData.jacobian(0, parameters.coordinate) = 1; //action only to the specified coordinate
		}
	}
	else //ground node
	{
		markerData.velocityAvailable = false;
		//markerData.value = 0;
		//markerData.value_t = 0; //set this also for ground markers, because it could be asked for in connector!!!!
		markerData.vectorValue.SetVector({ 0. });   //indicates that value is zero
		markerData.jacobian.SetNumberOfRowsAndColumns(0, 0); //this signals the connector/system not to apply any load or Lagrange multiplier
	}
}

