#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# This is an EXUDYN maintainer tool
#
# Details:  Emits the pages that show the example and test model sources, and the list of
#           abbreviations: docs/generated/examples/*.md, docs/generated/testModels/*.md with their
#           index pages, and docs/generated/abbreviations.md. These three were the last things
#           src/pythonGenerator/doc2rst.py did besides converting LaTeX, and they moved here when
#           that converter was deleted.
#
#           The test models are listed in the order of the reference solution of the test suite,
#           the examples in the order of the folder, so that a page is where the reader of the
#           previous documentation expects it.
#
# Usage:    python tools/generators/examplesDocsEmitter.py
#
# Author:   Johannes Gerstmayr
# Date:     2020-06-09 (created as doc2rst.py), 2026-09-20 (emitter)
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

import io
import os
import sys

toolsDirectory = os.path.dirname(os.path.abspath(__file__))
if toolsDirectory not in sys.path:
    sys.path.insert(0, toolsDirectory)

import generatorPaths as paths                                                  # noqa: E402
from autoGenerateHelper import MarkdownLabel                                    # noqa: E402

#the abbreviations of the documentation; each one is a target, because the \acs{..} macros of the
#chapters point at it (they became {ref}`ODE2 <ODE2>` in the Markdown)
abbreviations = {
    '2D': 'two dimensions or planar',
    '3D': 'three dimensions or spatial',
    'abs': 'absolute (e.g., absolute error), absolute value',
    'AE': 'algebraic equations',
    'CMS': 'component mode synthesis',
    'coeffs': 'coefficients',
    'COM': 'center of mass',
    'DOF': 'degree of freedom',
    'EOM': 'equations of motion',
    'EP': 'Euler parameters',
    'FFRF': 'floating frame of reference formulation',
    'HT': 'homogeneous transformation',
    'LHS': 'Left-Hand-Side (of equation)',
    'LTG': 'local-to-global',
    'mbs': 'multibody system',
    'min': 'minimum',
    'max': 'maximum',
    'ODE': 'ordinary differential equation',
    'ODE1': 'first order ordinary differential equations',
    'ODE2': 'second order ordinary differential equations',
    'pos': 'position',
    'quad': 'quadrangle, polygon with 4 vertices',
    'rel': 'relative (e.g., relative error)',
    'RHS': 'Right-Hand-Side (of equation)',
    'Rot': 'rotation',
    'Rxyz': 'rotation parameterization: consecutive rotations around x, y and z-axis (Tait-Bryan)',
    'STL': 'STereoLithography',
    'T66': 'Plücker transformation',
    'trig': 'triangle',
    }


def Banner():
    return ('<!-- GENERATED by tools/generators/examplesDocsEmitter.py from python/ '
            '- do not edit -->\n')


def Write(markdownDir, fileName, text):
    os.makedirs(markdownDir, exist_ok=True)
    with io.open(os.path.join(markdownDir, fileName), 'w', encoding='utf8', newline='\n') as file:
        file.write(text)


def TestModelNames():
    """the test models, in the order of the reference solution of the test suite"""
    testingDirectory = os.path.join(paths.repositoryRoot, 'python', 'testing')
    if testingDirectory not in sys.path:
        sys.path.append(testingDirectory)
    from runTestSuiteRefSol import TestExamplesReferenceSolution
    return list(TestExamplesReferenceSolution().keys())


def ExampleNames():
    """every .py in python/Examples; sorted, because listdir() order is filesystem dependent and
    made the generated documentation differ between Windows and Linux"""
    directory = paths.examplesDir
    return sorted([name for name in os.listdir(directory)
                   if name.endswith('.py') and os.path.isfile(os.path.join(directory, name))],
                  key=str.lower)


def WriteSourcePages(folder, fileNames, title, label, directoryName, indexName):
    """one page per source file, plus the index that lists them"""
    markdownDir = os.path.join(paths.repositoryRoot, 'docs', 'generated', directoryName)
    githubDir = paths.githubSourceURL.replace('/blob/', '/tree/') + folder

    index = (Banner() + MarkdownLabel(label) + '\n'
             + '# ' + title + '\n\n'
             + 'This section includes all ' + folder + ' for Exudyn. They can also be found and '
             + 'downloaded at the [' + folder + ' folder of Exudyn on Github](' + githubDir
             + ').\n\n'
             + '```{toctree}\n:maxdepth: 2\n\n')

    for fileName in fileNames:
        pureName = fileName.replace('.py', '')
        with io.open(os.path.join(paths.pythonDir, folder, fileName), encoding='utf8') as file:
            source = file.read()

        page = (Banner() + MarkdownLabel(folder.lower() + '-' + pureName) + '\n'
                + '# ' + fileName + '\n\n'
                + 'You can view and download this file on Github: ['
                + fileName + '](' + githubDir + '/' + fileName + ')\n\n'
                #the directive rather than a plain fence, because the line numbers are what makes
                #a source listing quotable in an issue or a lecture
                + '```{code-block} python\n:linenos:\n\n' + source.rstrip() + '\n```\n')
        Write(markdownDir, pureName + '.md', page)
        index += pureName + '\n'

    Write(markdownDir, indexName + '.md', index + '```\n')
    return len(fileNames) + 1


def WriteAbbreviations():
    """the list of abbreviations; every entry is a target of its own, because the abbreviation
    macros of the chapters reference it by name"""
    text = (Banner() + MarkdownLabel('sec:listofabbreviations') + '\n'
            + '# List of Abbreviations\n\n'
            + 'This section shows typical abbreviations. For further notation, see also '
            + '{ref}`Section Notation <sec-generalnotation>`.\n\n')
    for (key, value) in abbreviations.items():
        text += '(' + key + ')=\n\n**' + key + '**: ' + value + '\n\n'

    Write(os.path.join(paths.repositoryRoot, 'docs', 'generated'), 'abbreviations.md', text)
    return 1


def main():
    written = WriteSourcePages('TestModels', TestModelNames(), 'TestModels',
                               'sec:testmodels:index', 'testModels', 'testModelsIndex')
    written += WriteSourcePages('Examples', ExampleNames(), 'Examples',
                                'sec:examples:index', 'examples', 'examplesIndex')
    written += WriteAbbreviations()
    print('examplesDocsEmitter: ' + str(written) + ' Markdown file(s) written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
