#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# This is an EXUDYN maintainer tool
#
# Details:  Emits the references page, docs/generated/references.md, from docs/bibliographyDoc.bib,
#           and the citation keys as data for conf.py in tools/generators/generated/
#           confHelperCitations.py (revision2026b step RG3.5, #2550).
#
#           WHY a generator and not a hand-written page: the .bib is the bibliography of the
#           project and outlived the LaTeX build (revision2026 step R7.1.7 moved it to docs/).
#           The chapters cite with [Key2021] in the running text, which the LaTeX build resolved
#           and nothing has resolved since - the keys were printed and pointed nowhere.
#
#           HOW the citation becomes a link without touching a single source text: every entry
#           gets a target (ref-<key in lower case>) here, and conf.py appends one Markdown link
#           definition per key to every document it reads. CommonMark then resolves [Key2021] as
#           a shortcut reference link - and only where it IS text, never inside a code fence or
#           inline code, because the Markdown parser itself decides that. See conf.py,
#           AppendCitationDefinitions().
#
#           The page lists the WHOLE bibliography, not only what is cited today: the input is the
#           .bib alone, so the output never depends on the state of another generated page. The
#           report at the end of a run says how many of the entries are cited and names a key that
#           is cited but missing from the .bib - such a key renders as plain text, and nothing
#           else would notice.
#
# Usage:    python tools/generators/referencesDocsEmitter.py
#
# Author:   Johannes Gerstmayr
# Date:     2026-09-22 (created)
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

import glob
import io
import os
import re
import sys

toolsDirectory = os.path.dirname(os.path.abspath(__file__))
if toolsDirectory not in sys.path:
    sys.path.insert(0, toolsDirectory)

import generatorPaths as paths                                                  # noqa: E402

bibliographyFile = paths.repositoryRoot + 'docs/bibliographyDoc.bib'

#the fields that are rendered, in the order they are rendered; everything else in an entry
#(abstract, keywords, file, issn, ...) is bibliographic housekeeping and is not shown
renderedFields = ['author', 'editor', 'title', 'journal', 'booktitle', 'series', 'publisher',
                  'institution', 'school', 'address', 'edition', 'volume', 'number', 'pages',
                  'year', 'howpublished', 'doi', 'url', 'isbn']

#LaTeX accents and escapes that occur in this bibliography; the braces around them are stripped
#before the table is applied, so {\"o}, {\"{o}} and \"o all arrive here as \"o
latexReplacements = [
    (r'\"a', 'ä'), (r'\"o', 'ö'), (r'\"u', 'ü'), (r'\"A', 'Ä'), (r'\"O', 'Ö'), (r'\"U', 'Ü'),
    (r'\"e', 'ë'), (r'\"i', 'ï'), (r'\ss', 'ß'),
    (r"\'a", 'á'), (r"\'e", 'é'), (r"\'i", 'í'), (r"\'o", 'ó'), (r"\'u", 'ú'),
    (r"\'A", 'Á'), (r"\'E", 'É'), (r"\'O", 'Ó'),
    (r'\`a', 'à'), (r'\`e', 'è'), (r'\`o', 'ò'),
    (r'\^a', 'â'), (r'\^e', 'ê'), (r'\^i', 'î'), (r'\^o', 'ô'), (r'\^u', 'û'),
    (r'\~n', 'ñ'), (r'\~a', 'ã'), (r'\cc', 'ç'), (r'\o', 'ø'), (r'\O', 'Ø'), (r'\aa', 'å'),
    (r'\&', '&'), (r'\%', '%'), (r'\$', '$'), (r'\#', '#'), (r'\_', '_'),
    ]


def Banner():
    return ('<!-- GENERATED by tools/generators/referencesDocsEmitter.py from '
            'docs/bibliographyDoc.bib - do not edit -->\n')


def ParseBibliography(text):
    """the entries of a .bib as a list of (key, type, {field: value}), in the order of the file.

    A hand-written parser rather than a dependency: the format in use here is one line per field,
    values in braces or quotes, and 100 entries of it. bibtexparser would be a new dependency for
    what fits in thirty lines (rule 6 of CLAUDE.md)."""
    entries = []
    for match in re.finditer(r'@(\w+)\s*\{\s*([^,\s]+)\s*,', text):
        entryType = match.group(1).lower()
        key = match.group(2)
        #the body of the entry: from the opening brace of @type{ to its matching closing brace
        start = text.index('{', match.start())
        depth = 0
        end = start
        for (index, character) in enumerate(text[start:], start):
            if character == '{':
                depth += 1
            elif character == '}':
                depth -= 1
                if depth == 0:
                    end = index
                    break
        entries.append((key, entryType, ParseFields(text[match.end():end])))
    return entries


def ParseFields(body):
    """field = {value} or field = "value", one per entry body; nested braces are kept"""
    fields = {}
    position = 0
    while True:
        match = re.compile(r'(\w+)\s*=\s*').search(body, position)
        if match is None:
            return fields
        position = match.end()
        if position < len(body) and body[position] in '{"':
            opening = body[position]
            closing = '}' if opening == '{' else '"'
            depth = 0
            for (index, character) in enumerate(body[position:], position):
                if character == opening and (opening == '{' or index == position):
                    depth += 1
                elif character == closing and not (opening == '"' and index == position):
                    depth -= 1
                    if depth == 0:
                        fields[match.group(1).lower()] = body[position + 1:index]
                        position = index + 1
                        break
            else:
                return fields
        else:                                     #a bare number, as in year = 1959
            end = body.find(',', position)
            end = len(body) if end == -1 else end
            fields[match.group(1).lower()] = body[position:end]
            position = end + 1


def CleanLatex(value):
    """what the LaTeX of a .bib field means in Markdown.

    Math in $...$ is left alone: MyST renders it through the dollarmath extension, so
    'the generalized-$\\alpha$ method' stays a formula instead of becoming a backslash."""
    value = ' '.join(value.split())               #the fields wrap over several lines
    value = value.replace(r'{\{}', '{').replace(r'{\}}', '}')
    value = re.sub(r'\\url\{([^}]*)\}', r'\1', value)
    #{\"{o}} and {\"o} both become \"o, so that one table below covers them
    value = re.sub(r'\{\\(.)\{(\w)\}\}', r'\\\1\2', value)
    value = re.sub(r'\{\\(.)(\w)\}', r'\\\1\2', value)
    for (latex, character) in latexReplacements:
        value = value.replace(latex, character)
    value = value.replace('~', ' ')               #a non-breaking space in names: E.~P.
    #the braces of {M}ehrkörpersysteme and {{A Title}} go, the braces of $x_{gap}$ stay: the math
    #is masked while the braces are stripped, and put back afterwards. A title may enclose math in
    #its outer braces, so masking rather than splitting is what keeps that pair strippable.
    math = re.findall(r'\$[^$]*\$', value)
    for (index, segment) in enumerate(math):
        value = value.replace(segment, '\x00' + str(index) + '\x00', 1)
    while re.search(r'\{[^{}]*\}', value):
        value = re.sub(r'\{([^{}]*)\}', r'\1', value)
    for (index, segment) in enumerate(math):
        value = value.replace('\x00' + str(index) + '\x00', segment, 1)
    value = value.replace('--', '\u2013')         #the en dash of page ranges
    return ' '.join(value.split()).strip()


def FormatNames(value):
    """'Hairer, E. and N{\\o}rsett, S.~P.' -> 'E. Hairer, S. P. Nørsett'"""
    names = []
    for name in CleanLatex(value).split(' and '):
        parts = name.split(',')
        if len(parts) == 2:
            name = parts[1].strip() + ' ' + parts[0].strip()
        names.append(' '.join(name.split()))
    return ', '.join(names)


def FormatEntry(key, entryType, fields):
    """one reference as one paragraph of Markdown, with its target above it"""
    rendered = {}
    for field in renderedFields:
        if field in fields and fields[field].strip() != '':
            rendered[field] = (FormatNames(fields[field]) if field in ('author', 'editor')
                               else CleanLatex(fields[field]))

    text = ''
    if 'author' in rendered:
        text += rendered['author'] + ': '
    elif 'editor' in rendered:
        text += rendered['editor'] + ' (ed.): '
    if 'title' in rendered:
        text += '*' + rendered['title'] + '*. '

    where = rendered.get('journal', rendered.get('booktitle', rendered.get('series', '')))
    if where != '':
        text += where
        if 'volume' in rendered:
            text += ' ' + rendered['volume']
            if 'number' in rendered:
                text += '(' + rendered['number'] + ')'
        text += ', '
    for field in ('edition', 'publisher', 'institution', 'school', 'address'):
        if field in rendered:
            text += rendered[field] + ', '
    if 'pages' in rendered:
        text += 'pp. ' + rendered['pages'] + ', '
    if 'howpublished' in rendered:
        text += rendered['howpublished'] + ', '
    text += rendered.get('year', 'no year') + '.'

    if 'doi' in rendered:
        doi = rendered['doi']
        link = doi if doi.startswith('http') else 'https://doi.org/' + doi
        text += ' [doi:' + doi.replace('https://doi.org/', '') + '](' + link + ')'
    elif 'url' in rendered and rendered['url'].startswith('http'):
        text += ' [link](' + rendered['url'] + ')'
    elif 'isbn' in rendered:
        text += ' ISBN ' + rendered['isbn']

    return ('(' + CitationTarget(key) + ')=\n'
            + '**[' + key + ']** ' + text + '\n\n')


def CitationTarget(key):
    """the MyST target of one entry; lower case, because a Sphinx target is case-insensitive and
    two keys differing only in case would silently be the same target"""
    return 'ref-' + key.lower()


def DocumentationText():
    """every Markdown page of the documentation as one string, for the report below"""
    sources = []
    for pattern in ('*.md', 'docs/manual/*.md', 'docs/dev/*.md', 'docs/howTo/*.md',
                    'docs/generated/*.md', 'docs/generated/*/*.md', 'definitions/*.py'):
        sources += glob.glob(paths.repositoryRoot + pattern)
    texts = []
    for source in sources:
        if os.path.basename(source) == 'references.md':
            continue
        with io.open(source, encoding='utf8', errors='replace') as file:
            texts.append(file.read())
    return '\n'.join(texts)


def CitedKeys(text, known):
    """which of the bibliography's keys the documentation writes as [Key], and which [Key] it
    writes that the bibliography does not have. For the report only - the emitted page depends on
    the .bib alone"""
    cited = set(key for key in known if '[' + key + ']' in text)
    written = set(re.findall(r'\[([A-Za-z][A-Za-z_]*\d{4}[a-z]?)\]', text))
    return (cited, sorted(key for key in written
                          if key.lower() not in set(name.lower() for name in known)))


def main():
    with io.open(bibliographyFile, encoding='utf8') as file:
        entries = ParseBibliography(file.read())
    entries.sort(key=lambda entry: entry[0].lower())

    page = (Banner() + '(sec-references)=\n'
            + '# References\n\n'
            + 'The literature the documentation cites. A citation in the text - '
            + '[Newmark1959], [ZwoelferGerstmayr2021] - links here; this page is generated from '
            + '`docs/bibliographyDoc.bib`, which is the bibliography of the project and holds '
            + 'more than the chapters cite.\n\n')
    for (key, entryType, fields) in entries:
        page += FormatEntry(key, entryType, fields)

    referencesFile = paths.repositoryRoot + 'docs/generated/references.md'
    with io.open(referencesFile, 'w', encoding='utf8', newline='\n') as file:
        file.write(page)

    helper = ('#this is a helper file: the citation keys of docs/bibliographyDoc.bib, so that\n'
              '#conf.py can turn every [Key] in the documentation into a link to the references\n'
              '#page without parsing BibTeX itself (revision2026b step RG3.5)\n'
              '#GENERATED by tools/generators/referencesDocsEmitter.py - do not edit\n\n'
              'citationKeys=[' + ', '.join(["'" + key + "'" for (key, _, _) in entries]) + ']\n')
    with io.open(paths.generatedDir + 'confHelperCitations.py', 'w', encoding='utf8',
                 newline='\n') as file:
        file.write(helper)

    known = set(key for (key, _, _) in entries)
    (cited, missing) = CitedKeys(DocumentationText(), known)
    print('referencesDocsEmitter: ' + str(len(entries)) + ' references written, '
          + str(len(cited)) + ' of them cited')
    if missing != []:
        print('   WARNING: cited but NOT in the bibliography, and therefore not a link:')
        for key in missing:
            print('      [' + key + ']')
    return 0


if __name__ == '__main__':
    sys.exit(main())
