#this file provides a list of file names for mini examples

miniExamplesFileList = ['NodePoint.py',
'NodePoint2D.py',
'NodeRigidBodyEP.py',
'NodeRigidBodyRxyz.py',
'NodeRigidBodyRotVecLG.py',
'NodeRigidBody2D.py',
'Node1D.py',
'NodePoint2DSlope1.py',
'NodePointSlope1.py',
'NodePointSlope12.py',
'NodePointSlope23.py',
'NodeGenericODE2.py',
'NodeGenericODE1.py',
'NodeGenericData.py',
'NodePointGround.py',
'ObjectGround.py',
'ObjectMassPoint.py',
'ObjectMassPoint2D.py',
'ObjectMass1D.py',
'ObjectRotationalMass1D.py',
'ObjectRigidBody.py',
'ObjectRigidBody2D.py',
'ObjectGenericODE2.py',
'ObjectGenericODE1.py',
'ObjectKinematicTree.py',
'ObjectANCFCable.py',
'ObjectANCFCable2D.py',
'ObjectALEANCFCable2D.py',
'ObjectANCFBeam.py',
'ObjectBeamGeometricallyExact2D.py',
'ObjectBeamGeometricallyExact.py',
'ObjectANCFThinPlate.py',
'ObjectConnectorSpringDamper.py',
'ObjectConnectorCartesianSpringDamper.py',
'ObjectConnectorRigidBodySpringDamper.py',
'ObjectConnectorLinearSpringDamper.py',
'ObjectConnectorTorsionalSpringDamper.py',
'ObjectConnectorCoordinateSpringDamper.py',
'ObjectConnectorCoordinateSpringDamperExt.py',
'ObjectConnectorGravity.py',
'ObjectConnectorHydraulicActuatorSimple.py',
'ObjectConnectorReevingSystemSprings.py',
'ObjectConnectorDistance.py',
'ObjectConnectorCoordinate.py',
'ObjectConnectorCoordinateVector.py',
'ObjectConnectorRollingDiscPenalty.py',
'ObjectContactCoordinate.py',
'ObjectContactCircleCable2D.py',
'ObjectContactFrictionCircleCable2D.py',
'ObjectContactSphereSphere.py',
'ObjectContactSphereTorus.py',
'ObjectContactSphereTriangle.py',
'ObjectContactCurveCircles.py',
'ObjectJointGeneric.py',
'ObjectJointRevoluteZ.py',
'ObjectJointPrismaticX.py',
'ObjectJointSpherical.py',
'ObjectJointRollingDisc.py',
'ObjectJointRevolute2D.py',
'ObjectJointPrismatic2D.py',
'ObjectJointSliding.py',
'ObjectJointSliding2D.py',
'ObjectJointALEMoving2D.py',
'MarkerBodyMass.py',
'MarkerBodyPosition.py',
'MarkerBodyRigid.py',
'MarkerNodePosition.py',
'MarkerNodeRigid.py',
'MarkerNodeCoordinate.py',
'MarkerNodeCoordinates.py',
'MarkerNodeODE1Coordinate.py',
'MarkerNodeRotationCoordinate.py',
'MarkerBodiesRelativeTranslationCoordinate.py',
'MarkerBodiesRelativeRotationCoordinate.py',
'MarkerSuperElementPosition.py',
'MarkerSuperElementRigid.py',
'MarkerKinematicTreeRigid.py',
'MarkerObjectODE2Coordinates.py',
'MarkerBodyCable2DShape.py',
'MarkerBodyCable2DCoordinates.py',
'MarkerBodyBeamShape.py',
'LoadForceVector.py',
'LoadTorqueVector.py',
'LoadMassProportional.py',
'LoadCoordinate.py',
'SensorNode.py',
'SensorObject.py',
'SensorBody.py',
'SensorSuperElement.py',
'SensorKinematicTree.py',
'SensorMarker.py',
'SensorLoad.py',
'SensorUserFunction.py']

#per mini example the settings of its performance run, from the item definitions (miniExamplePerformance);
#an item without an entry uses the defaults of python/testing/runMiniExamplePerformance.py
miniExamplesPerformance = {'LoadCoordinate': {'numberOfSteps': 1285720},
'LoadForceVector': {'numberOfSteps': 1201600},
'LoadMassProportional': {'numberOfSteps': 1603210},
'LoadTorqueVector': {'numberOfSteps': 577350},
'MarkerBodiesRelativeRotationCoordinate': {'numberOfSteps': 349140},
'MarkerBodiesRelativeTranslationCoordinate': {'numberOfSteps': 434380},
'MarkerBodyBeamShape': {'numberOfSteps': 27920},
'MarkerBodyCable2DCoordinates': {'numberOfSteps': 78860},
'MarkerBodyCable2DShape': {'numberOfSteps': 57080},
'MarkerBodyMass': {'numberOfSteps': 1584910},
'MarkerBodyPosition': {'numberOfSteps': 920110},
'MarkerBodyRigid': {'numberOfSteps': 226940},
'MarkerKinematicTreeRigid': {'numberOfSteps': 638920},
'MarkerNodeCoordinate': {'numberOfSteps': 1414030},
'MarkerNodeCoordinates': {'numberOfSteps': 757100},
'MarkerNodeODE1Coordinate': {'numberOfSteps': 1564820},
'MarkerNodePosition': {'numberOfSteps': 956230},
'MarkerNodeRigid': {'numberOfSteps': 547540},
'MarkerNodeRotationCoordinate': {'numberOfSteps': 467030},
'MarkerObjectODE2Coordinates': {'numberOfSteps': 905650},
'MarkerSuperElementPosition': {'numberOfSteps': 581100},
'MarkerSuperElementRigid': {'numberOfSteps': 121470},
'Node1D': {'numberOfSteps': 1715930},
'NodeGenericData': {'numberOfSteps': 1229520},
'NodeGenericODE1': {'numberOfSteps': 1666940},
'NodeGenericODE2': {'numberOfSteps': 1316310},
'NodePoint': {'numberOfSteps': 1673150},
'NodePoint2D': {'numberOfSteps': 1614470},
'NodePoint2DSlope1': {'numberOfSteps': 330150},
'NodePointGround': {'numberOfSteps': 1001500},
'NodePointSlope1': {'numberOfSteps': 126950},
'NodePointSlope12': {'skip': True},
'NodePointSlope23': {'numberOfSteps': 2940},
'NodeRigidBody2D': {'numberOfSteps': 1747720},
'NodeRigidBodyEP': {'numberOfSteps': 650680},
'NodeRigidBodyRotVecLG': {'numberOfSteps': 644750},
'NodeRigidBodyRxyz': {'numberOfSteps': 609950},
'ObjectALEANCFCable2D': {'numberOfSteps': 34180},
'ObjectANCFBeam': {'numberOfSteps': 2900},
'ObjectANCFCable': {'numberOfSteps': 1930},
'ObjectANCFCable2D': {'numberOfSteps': 4940},
'ObjectANCFThinPlate': {'skip': True},
'ObjectBeamGeometricallyExact': {'numberOfSteps': 24100},
'ObjectBeamGeometricallyExact2D': {'numberOfSteps': 233750},
'ObjectConnectorCartesianSpringDamper': {'numberOfSteps': 948610},
'ObjectConnectorCoordinate': {'numberOfSteps': 851050},
'ObjectConnectorCoordinateSpringDamper': {'numberOfSteps': 483470},
'ObjectConnectorCoordinateSpringDamperExt': {'numberOfSteps': 1219510},
'ObjectConnectorCoordinateVector': {'numberOfSteps': 760930},
'ObjectConnectorDistance': {'numberOfSteps': 1238700},
'ObjectConnectorGravity': {'numberOfSteps': 404760},
'ObjectConnectorHydraulicActuatorSimple': {'numberOfSteps': 398340},
'ObjectConnectorLinearSpringDamper': {'numberOfSteps': 240230},
'ObjectConnectorReevingSystemSprings': {'numberOfSteps': 270520},
'ObjectConnectorRigidBodySpringDamper': {'numberOfSteps': 232850},
'ObjectConnectorRollingDiscPenalty': {'numberOfSteps': 142170},
'ObjectConnectorSpringDamper': {'numberOfSteps': 1020020},
'ObjectConnectorTorsionalSpringDamper': {'numberOfSteps': 208390},
'ObjectContactCircleCable2D': {'numberOfSteps': 57310},
'ObjectContactCoordinate': {'numberOfSteps': 1256910},
'ObjectContactCurveCircles': {'numberOfSteps': 514120},
'ObjectContactFrictionCircleCable2D': {'numberOfSteps': 55910},
'ObjectContactSphereSphere': {'numberOfSteps': 330100},
'ObjectContactSphereTorus': {'numberOfSteps': 273130},
'ObjectContactSphereTriangle': {'numberOfSteps': 274900},
'ObjectGenericODE1': {'numberOfSteps': 1576350},
'ObjectGenericODE2': {'numberOfSteps': 650270},
'ObjectGround': {'numberOfSteps': 973260},
'ObjectJointALEMoving2D': {'numberOfSteps': 33580},
'ObjectJointGeneric': {'numberOfSteps': 343660},
'ObjectJointPrismatic2D': {'numberOfSteps': 753760},
'ObjectJointPrismaticX': {'numberOfSteps': 352510},
'ObjectJointRevolute2D': {'numberOfSteps': 858330},
'ObjectJointRevoluteZ': {'numberOfSteps': 365300},
'ObjectJointRollingDisc': {'numberOfSteps': 396690},
'ObjectJointSliding': {'numberOfSteps': 28550},
'ObjectJointSliding2D': {'numberOfSteps': 81330},
'ObjectJointSpherical': {'numberOfSteps': 393840},
'ObjectKinematicTree': {'numberOfSteps': 755290},
'ObjectMass1D': {'numberOfSteps': 1845530},
'ObjectMassPoint': {'numberOfSteps': 1726000},
'ObjectMassPoint2D': {'numberOfSteps': 1757550},
'ObjectRigidBody': {'numberOfSteps': 607590},
'ObjectRigidBody2D': {'numberOfSteps': 1728680},
'ObjectRotationalMass1D': {'numberOfSteps': 1841280},
'SensorBody': {'numberOfSteps': 1650230},
'SensorKinematicTree': {'numberOfSteps': 628000},
'SensorLoad': {'numberOfSteps': 989710},
'SensorMarker': {'numberOfSteps': 1307060},
'SensorNode': {'numberOfSteps': 1660510},
'SensorObject': {'numberOfSteps': 759980},
'SensorSuperElement': {'numberOfSteps': 719900},
'SensorUserFunction': {'numberOfSteps': 1443940}}
