#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# This is an EXUDYN test file
#
# Details:  The issue tracker escapes what issue authors write, so that no description can turn
#           into markup of the document it is written into. This is the test that #2545 asks for:
#           the LaTeX escaping of ToLatex broke the PDF build twice before it existed, and
#           revision2026 step R7.1.6 moved the requirement to ToMarkdown, which writes
#           docs/generated/trackerlog.md.
#
# Usage:    pytest python/testing/test_issueTracker.py
#
# Author:   Johannes Gerstmayr
# Date:     2026-09-20
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

import importlib.util
import os
import sys

import pytest

trackerDirectory = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                 '..', '..', 'tools', 'issueTracker'))


def IssueTracker():
    """import tools/issueTracker/issueTracker.py, which is not part of the exudyn package"""
    if trackerDirectory not in sys.path:
        sys.path.insert(0, trackerDirectory)
    specification = importlib.util.spec_from_file_location(
        'issueTrackerUnderTest', os.path.join(trackerDirectory, 'issueTracker.py'))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


#the characters that make an issue description into Markdown instead of text
markdownSpecials = ['`', '*', '_', '[', ']', '<', '>', '#', '|', '$', '\\']


@pytest.mark.parametrize('character', markdownSpecials)
def testEverySpecialCharacterIsEscaped(character):
    text = IssueTracker().ToMarkdown('a' + character + 'b')
    assert text == 'a\\' + character + 'b' or text == 'a\\\\b', text


def testRealIssueTextStaysText():
    """three shapes that actually occur in the tracker and each of which is markup if it is not
    escaped: a star that opens emphasis, a word ending in an underscore, an unpaired backtick"""
    toMarkdown = IssueTracker().ToMarkdown
    assert toMarkdown('rename *.md files') == 'rename \\*.md files'
    assert toMarkdown('the CIBW_ variable') == 'the CIBW\\_ variable'
    assert toMarkdown('use `pip install') == 'use \\`pip install'


def testBackslashIsEscapedFirst():
    """a backslash that arrives escaped would otherwise escape the escape of the next rule and
    the text would lose it"""
    assert IssueTracker().ToMarkdown('C:\\temp') == 'C:\\\\temp'
    assert IssueTracker().ToMarkdown('\\#tag') == '\\\\\\#tag'


def testNothingElseIsTouched():
    """escaping is total for the specials and silent for everything else - an issue author writes
    ordinary sentences and they have to arrive as they were written"""
    text = 'solver fails after 3 steps; tolerance 1e-8 (see issue 2401), 50% slower'
    assert IssueTracker().ToMarkdown(text) == text


def testGeneratedPageIsThere():
    """the page the tracker writes; its first line says that it is generated"""
    path = os.path.normpath(os.path.join(trackerDirectory, '..', '..', 'docs', 'generated',
                                         'trackerlog.md'))
    assert os.path.exists(path), path
    with open(path, encoding='utf-8') as file:
        assert 'GENERATED by tools/issueTracker/issueTracker.py' in file.readline()


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#ExtendIssue and the triage notes (revision2026 steps R8.3.3 and R8.5.2)

@pytest.fixture
def tracker(tmp_path, monkeypatch):
    """the tracker working on a COPY of the log in a temporary directory: it reads and writes
    trackerlog.txt relative to the current directory, and the three files it updates afterwards
    (the version files, the HTML and the Markdown page) live outside it"""
    import shutil
    module = IssueTracker()
    shutil.copy(os.path.join(trackerDirectory, 'trackerlog.txt'),
                os.path.join(str(tmp_path), 'trackerlog.txt'))
    #the tracker reads its directory from a module global since revision2026 step R8.3, so the
    #tests point it at the copy instead of changing the working directory
    monkeypatch.setattr(module, 'trackerDirectory', str(tmp_path))
    monkeypatch.setattr(module, 'repositoryRoot', str(tmp_path))
    monkeypatch.setattr(module, 'UpdateDateAndVersion', lambda *args, **kwargs: None)
    monkeypatch.setattr(module, 'ConvertToHTML', lambda *args, **kwargs: None)
    monkeypatch.setattr(module, 'ConvertToMarkdown', lambda *args, **kwargs: None)
    return module


def OpenIssueNumber(module):
    return int([issue for issue in module.GetIssues() if issue['status'] == 'RAISED'][-1]['number'])


def ClosedIssueNumber(module):
    return int([issue for issue in module.GetIssues()
                if issue['status'] in module.closedStatuses][-1]['number'])


def testExtendAppendsAndChangesNothingElse(tracker):
    number = OpenIssueNumber(tracker)
    before = tracker.GetIssue(number)
    count = tracker.NumberOfIssues()

    tracker.ExtendIssue(number, 'the parser also fails on an empty file', author='Claude-JG')

    after = tracker.GetIssue(number)
    assert after['description'].startswith(before['description'].rstrip()[:40])
    assert after['description'].endswith('the parser also fails on an empty file')
    assert 'Claude-JG' in after['description']
    #everything else is untouched - above all the status, which is what the version counts
    for field in ['issue', 'status', 'type', 'date raised', 'releaseNotes', 'workingRemarks']:
        assert after[field] == before[field], field
    assert tracker.NumberOfIssues() == count


def testExtendRefusesAClosedIssue(tracker):
    """a closed issue has been published in the release notes; it is reopened or superseded,
    not rewritten"""
    with pytest.raises(ValueError):
        tracker.ExtendIssue(ClosedIssueNumber(tracker), 'more analysis')


def testExtendRefusesEmptyText(tracker):
    with pytest.raises(ValueError):
        tracker.ExtendIssue(OpenIssueNumber(tracker), '   ')


def testResolveWritesTheReleaseNoteAndClearsTheRemarks(tracker):
    """the working remarks of an open issue ("duplicate of #2134") are worthless once it closes
    and must not reach the release notes, which is what releaseNotes is"""
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'duplicate of #2134, check before starting')

    tracker.ResolveIssue(number, notes='fixed by the new parser', author='Claude-JG')

    issue = tracker.GetIssue(number)
    assert issue['releaseNotes'] == 'fixed by the new parser'
    assert issue['workingRemarks'] == ''
    assert issue['status'] == 'RESOLVED'


def testAbandonAlsoClearsTheRemarks(tracker):
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'marked for deprecation')

    tracker.AbandonIssue(number, reason='superseded by the new solver', author='Claude-JG')

    issue = tracker.GetIssue(number)
    assert issue['releaseNotes'] == 'superseded by the new solver'
    assert issue['workingRemarks'] == ''
    assert issue['status'] == 'ABANDONED'


def testRemarkAppendsAndReplaces(tracker):
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'part A solved')
    tracker.RemarkIssue(number, 'B still open')
    assert tracker.GetIssue(number)['workingRemarks'] == 'part A solved; B still open'

    tracker.RemarkIssue(number, 'all of it is the parser', replace=True)
    assert tracker.GetIssue(number)['workingRemarks'] == 'all of it is the parser'


def testRemarkRefusesAClosedIssue(tracker):
    """the remarks of a closed issue are gone by design"""
    with pytest.raises(ValueError):
        tracker.RemarkIssue(ClosedIssueNumber(tracker), 'something')


def testRaiseRefusesAReleaseNote(tracker):
    """the release note is written when the issue closes; what is known now is a working remark"""
    with pytest.raises(ValueError):
        tracker.RaiseIssueDict({'issue': 'x', 'description': 'y', 'type': 'FIX',
                                'releaseNotes': 'not yet'})


def testUnknownEffortAndPriorityAreRefused(tracker):
    """one spelling per value, at both places that write one"""
    with pytest.raises(ValueError):
        tracker.RaiseIssueDict({'issue': 'x', 'description': 'y', 'type': 'FIX',
                                'effort': 'SMALL'})
    with pytest.raises(ValueError):
        tracker.ChangeIssue(OpenIssueNumber(tracker), 'effort', 'quick')
    with pytest.raises(ValueError):
        tracker.ChangeIssue(OpenIssueNumber(tracker), 'priority', 'med')


def testEffortIsKeptAndNormalized(tracker):
    number = tracker.RaiseIssue('an issue with an effort', 'description', issueType='FIX',
                                author='Claude-JG')
    tracker.ChangeIssue(number, 'effort', 'medium')
    assert tracker.GetIssue(number)['effort'] == 'MEDIUM'


def testTheSchemaIsTheOneOfTheFile(tracker):
    """the 16 columns of trackerlog.txt and the names the module reads them under are one list;
    they went out of step once already (the status column is padded to 8 characters, #2519)"""
    with open(os.path.join(trackerDirectory, 'trackerlog.txt'), encoding='utf-8') as file:
        header = [next(file) for _ in range(tracker.nHeaderLines)]
    formatLine = [line for line in header if line.startswith('# line format:')]
    assert len(formatLine) == 1
    for name in ['releaseNotes', 'workingRemarks', 'effort']:
        assert name in formatLine[0], name
    assert header[-1].strip() == '# end of comment (' + str(tracker.nHeaderLines) + ' lines)'
    assert len(tracker.trackerItems) == tracker.numberOfItems == 16


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#the version arithmetic (revision2026 step R8.3). These two functions are the ONLY definition of
#what version.txt says - the micro number is the count of closed issues - and nothing covered them.

def testTheMicroVersionIsTheCountOfClosedIssues(tracker):
    """what GetMajorMinorMicroVersion returns has to be what the file contains"""
    closed = len([issue for issue in tracker.GetIssues()
                  if issue['status'].strip() in tracker.closedStatuses])
    [major, minor, micro] = tracker.GetMajorMinorMicroVersion()

    assert major == 1
    assert minor == len(tracker.versionResolved) - 2
    assert micro == closed - tracker.versionResolved[-1]


def testResolvingMovesTheVersionByOne(tracker):
    """the one property the whole scheme rests on; it is also why a closed-not-resolved issue
    still counts (see the note on closedStatuses)"""
    before = tracker.GetMajorMinorMicroVersion()
    tracker.ResolveIssue(OpenIssueNumber(tracker), notes='done', author='Claude-JG')
    after = tracker.GetMajorMinorMicroVersion()

    assert after[2] == before[2] + 1 and after[:2] == before[:2]


def testAbandoningCountsLikeResolving(tracker):
    before = tracker.GetMajorMinorMicroVersion()
    tracker.AbandonIssue(OpenIssueNumber(tracker), reason='decided against', author='Claude-JG')
    after = tracker.GetMajorMinorMicroVersion()

    assert after[2] == before[2] + 1


def testResolvedIssues2VersionOnAndBetweenTheBaselines(tracker):
    """the release notes are grouped by what this returns, so its boundaries matter: a count
    exactly ON a minor baseline belongs to that minor version with micro 0"""
    baselines = tracker.versionResolved
    total = baselines[-1] + 10                      #ten issues into the current minor version

    #ten issues back from the total is the baseline itself: minor = the last one, micro = 0
    assert tracker.ResolvedIssues2Version(10, total) == [len(baselines) - 2, 0]
    #the newest issue is the highest micro of the current minor version
    assert tracker.ResolvedIssues2Version(0, total) == [len(baselines) - 2, 10]
    #one below the baseline is the PREVIOUS minor version, at its highest micro
    [minor, micro] = tracker.ResolvedIssues2Version(11, total)
    assert minor == len(baselines) - 3
    assert micro == baselines[-1] - 1 - baselines[-2]


def testVersionStringFollowsTheBuildMode(tracker, monkeypatch):
    """fact 26: the .dev1 suffix decides what setup.py builds and whether pip would take it"""
    [major, minor, micro] = tracker.GetMajorMinorMicroVersion()
    plain = str(major) + '.' + str(minor) + '.' + str(micro)

    monkeypatch.setattr(tracker, 'versionDev', '')
    assert tracker.VersionString() == plain

    monkeypatch.setattr(tracker, 'versionDev', '.dev1')
    assert tracker.VersionString() == plain + '.dev1'


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#the command line: exudev issue <verb> (revision2026 step R8.3)

def ExudevCommands():
    """tools/exudev/commands.py, loaded by path like the tracker above - a plain "import commands"
    would read as a dependency on the PyPI package of that name (tools/checkExtras.py says so)"""
    exudevDirectory = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                    '..', '..', 'tools', 'exudev'))
    if exudevDirectory not in sys.path:
        sys.path.insert(0, exudevDirectory)      #commands.py imports runner from there
    specification = importlib.util.spec_from_file_location(
        'exudevCommandsUnderTest', os.path.join(exudevDirectory, 'commands.py'))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def IssueOptions(**fields):
    """the options object the parser would build"""
    class Options:
        pass
    options = Options()
    for (name, value) in fields.items():
        setattr(options, name, value)
    return options


def testEveryWritingVerbIsAStepWithAnActionAndANote():
    """--dry-run must be able to print what a verb would do WITHOUT doing it; that is only true
    if the work sits in the step's action and the note describes it"""
    commands = ExudevCommands()
    verbs = [IssueOptions(issueVerb='extend', number=1, text='t', author='JG'),
             IssueOptions(issueVerb='remark', number=1, text='t', author='JG', replace=False),
             IssueOptions(issueVerb='resolve', number=1, notes='n', author='JG'),
             IssueOptions(issueVerb='abandon', number=1, reason='r', author='JG'),
             IssueOptions(issueVerb='modify', number=1, field='effort', value='LOW'),
             IssueOptions(issueVerb='mode', release=True, dev=False)]

    for options in verbs:
        steps = commands.Issue(options)
        assert len(steps) == 1, options.issueVerb
        assert steps[0].action is not None and steps[0].note, options.issueVerb
        assert steps[0].argv is None, options.issueVerb   #nothing is run as a process


def testListFiltersByStatusTypeAndEffort(tracker, capsys):
    commands = ExudevCommands()
    options = IssueOptions(open=True, type='FIX', effort=None, priority=None, limit=0)

    commands.ListIssues(tracker, options)

    printed = capsys.readouterr().out
    expected = len([issue for issue in tracker.GetIssues()
                    if issue['status'].strip() == 'RAISED' and issue['type'].strip() == 'FIX'])
    assert str(expected) + ' of ' + str(expected) + ' matching issues' in printed


def testShowPrintsTheFieldsThatAreFilled(tracker, capsys):
    commands = ExudevCommands()
    issue = tracker.GetIssue(OpenIssueNumber(tracker))

    commands.ShowIssue(issue)

    printed = capsys.readouterr().out
    assert issue['issue'].strip() in printed
    assert 'description:' in printed
    #an empty field is not printed at all - a screen full of empty labels helps nobody
    assert 'date resolved' not in printed
