#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# This is an EXUDYN test file
#
# Details:  The issue tracker escapes what issue authors write, so that no description can turn
#           into markup of the document it is written into. This is the test that #2545 asks for:
#           the LaTeX escaping of ToLatex broke the PDF build twice before it existed, and
#           revision2026 step R7.1.6 moved the requirement to ToMarkdown, which writes
#           docs/generated/trackerlog.md.
#
# Usage:    pytest python/testing/test_issueTracker.py
#
# Author:   Johannes Gerstmayr
# Date:     2026-09-20
# Copyright:This file is part of Exudyn. Exudyn is free software: see 'LICENSE.txt'
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

import importlib.util
import json
import os
import sys

import pytest

trackerDirectory = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                 '..', '..', 'tools', 'issueTracker'))


def IssueTracker():
    """import tools/issueTracker/issueTracker.py, which is not part of the exudyn package"""
    if trackerDirectory not in sys.path:
        sys.path.insert(0, trackerDirectory)
    specification = importlib.util.spec_from_file_location(
        'issueTrackerUnderTest', os.path.join(trackerDirectory, 'issueTracker.py'))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


#the characters that make an issue description into Markdown instead of text
markdownSpecials = ['`', '*', '_', '[', ']', '<', '>', '#', '|', '$', '\\']


@pytest.mark.parametrize('character', markdownSpecials)
def testEverySpecialCharacterIsEscaped(character):
    text = IssueTracker().ToMarkdown('a' + character + 'b')
    assert text == 'a\\' + character + 'b' or text == 'a\\\\b', text


def testRealIssueTextStaysText():
    """three shapes that actually occur in the tracker and each of which is markup if it is not
    escaped: a star that opens emphasis, a word ending in an underscore, an unpaired backtick"""
    toMarkdown = IssueTracker().ToMarkdown
    assert toMarkdown('rename *.md files') == 'rename \\*.md files'
    assert toMarkdown('the CIBW_ variable') == 'the CIBW\\_ variable'
    assert toMarkdown('use `pip install') == 'use \\`pip install'


def testBackslashIsEscapedFirst():
    """a backslash that arrives escaped would otherwise escape the escape of the next rule and
    the text would lose it"""
    assert IssueTracker().ToMarkdown('C:\\temp') == 'C:\\\\temp'
    assert IssueTracker().ToMarkdown('\\#tag') == '\\\\\\#tag'


def testNothingElseIsTouched():
    """escaping is total for the specials and silent for everything else - an issue author writes
    ordinary sentences and they have to arrive as they were written"""
    text = 'solver fails after 3 steps; tolerance 1e-8 (see issue 2401), 50% slower'
    assert IssueTracker().ToMarkdown(text) == text


def testGeneratedPageIsThere():
    """the page the tracker writes; its first line says that it is generated"""
    path = os.path.normpath(os.path.join(trackerDirectory, '..', '..', 'docs', 'generated',
                                         'trackerlog.md'))
    assert os.path.exists(path), path
    with open(path, encoding='utf-8') as file:
        assert 'GENERATED by tools/issueTracker/issueTracker.py' in file.readline()


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#ExtendIssue and the triage notes (revision2026 steps R8.3.3 and R8.5.2)

@pytest.fixture
def tracker(tmp_path, monkeypatch):
    """the tracker working on a COPY of the log in a temporary directory: it reads and writes
    trackerlog.txt relative to the current directory, and the three files it updates afterwards
    (the version files, the HTML and the Markdown page) live outside it"""
    import shutil
    module = IssueTracker()
    #the issues are a directory of JSON files since revision2026 step R8.5; the tests work on a
    #copy of it and point both modules at the copy, so that a test run can never write into the
    #real tracker (it also owns version.txt)
    shutil.copytree(os.path.join(trackerDirectory, 'issues'),
                    os.path.join(str(tmp_path), 'issues'))
    monkeypatch.setattr(module, 'trackerDirectory', str(tmp_path))
    monkeypatch.setattr(module, 'repositoryRoot', str(tmp_path))
    monkeypatch.setattr(module.issueStore, 'storeDirectory',
                        os.path.join(str(tmp_path), 'issues'))
    monkeypatch.setattr(module, 'UpdateDateAndVersion', lambda *args, **kwargs: None)
    monkeypatch.setattr(module, 'ConvertToHTML', lambda *args, **kwargs: None)
    monkeypatch.setattr(module, 'ConvertToMarkdown', lambda *args, **kwargs: None)
    return module


def OpenIssueNumber(module):
    return int([issue for issue in module.GetIssues() if issue['status'] == 'RAISED'][-1]['number'])


def ClosedIssueNumber(module):
    return int([issue for issue in module.GetIssues()
                if issue['status'] in module.closedStatuses][-1]['number'])


def testExtendAppendsAndChangesNothingElse(tracker):
    number = OpenIssueNumber(tracker)
    before = tracker.GetIssue(number)
    count = tracker.NumberOfIssues()

    tracker.ExtendIssue(number, 'the parser also fails on an empty file', author='Claude-JG')

    after = tracker.GetIssue(number)
    assert after['description'].startswith(before['description'].rstrip()[:40])
    assert after['description'].endswith('the parser also fails on an empty file')
    assert 'Claude-JG' in after['description']
    #everything else is untouched - above all the status, which is what the version counts
    for field in ['title', 'status', 'type', 'dateRaised', 'releaseNotes', 'workingRemarks']:
        assert after[field] == before[field], field
    assert tracker.NumberOfIssues() == count


def testExtendRefusesAClosedIssue(tracker):
    """a closed issue has been published in the release notes; it is reopened or superseded,
    not rewritten"""
    with pytest.raises(ValueError):
        tracker.ExtendIssue(ClosedIssueNumber(tracker), 'more analysis')


def testExtendRefusesEmptyText(tracker):
    with pytest.raises(ValueError):
        tracker.ExtendIssue(OpenIssueNumber(tracker), '   ')


def testResolveWritesTheReleaseNoteAndClearsTheRemarks(tracker):
    """the working remarks of an open issue ("duplicate of #2134") are worthless once it closes
    and must not reach the release notes, which is what releaseNotes is"""
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'duplicate of #2134, check before starting')

    tracker.ResolveIssue(number, notes='fixed by the new parser', author='Claude-JG')

    issue = tracker.GetIssue(number)
    assert issue['releaseNotes'] == 'fixed by the new parser'
    assert issue['workingRemarks'] == ''
    assert issue['status'] == 'RESOLVED'


def testAbandonAlsoClearsTheRemarks(tracker):
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'marked for deprecation')

    tracker.AbandonIssue(number, reason='superseded by the new solver', author='Claude-JG')

    issue = tracker.GetIssue(number)
    assert issue['releaseNotes'] == 'superseded by the new solver'
    assert issue['workingRemarks'] == ''
    assert issue['status'] == 'ABANDONED'


def testRemarkAppendsAndReplaces(tracker):
    number = OpenIssueNumber(tracker)
    tracker.RemarkIssue(number, 'part A solved')
    tracker.RemarkIssue(number, 'B still open')
    assert tracker.GetIssue(number)['workingRemarks'] == 'part A solved; B still open'

    tracker.RemarkIssue(number, 'all of it is the parser', replace=True)
    assert tracker.GetIssue(number)['workingRemarks'] == 'all of it is the parser'


def testRemarkRefusesAClosedIssue(tracker):
    """the remarks of a closed issue are gone by design"""
    with pytest.raises(ValueError):
        tracker.RemarkIssue(ClosedIssueNumber(tracker), 'something')


def testRaiseRefusesAReleaseNote(tracker):
    """the release note is written when the issue closes; what is known now is a working remark"""
    with pytest.raises(ValueError):
        tracker.RaiseIssueDict({'issue': 'x', 'description': 'y', 'type': 'FIX',
                                'releaseNotes': 'not yet'})


def testUnknownEffortAndPriorityAreRefused(tracker):
    """one spelling per value, at both places that write one"""
    with pytest.raises(ValueError):
        tracker.RaiseIssueDict({'issue': 'x', 'description': 'y', 'type': 'FIX',
                                'effort': 'SMALL'})
    with pytest.raises(ValueError):
        tracker.ChangeIssue(OpenIssueNumber(tracker), 'effort', 'quick')
    with pytest.raises(ValueError):
        tracker.ChangeIssue(OpenIssueNumber(tracker), 'priority', 'med')


def testEffortIsKeptAndNormalized(tracker):
    number = tracker.RaiseIssue('an issue with an effort', 'description', issueType='FIX',
                                author='Claude-JG')
    tracker.ChangeIssue(number, 'effort', 'medium')
    assert tracker.GetIssue(number)['effort'] == 'MEDIUM'


def testTheStoreIsConsistent(tracker):
    """the check that runs in the commit gate, against the real store: no number twice, no file
    whose name and content disagree, no issue in the wrong directory, and the closed count the
    version is derived from"""
    assert tracker.issueStore.CheckStore() == []


def testEveryFieldOfAnIssueIsKnown(tracker):
    """a field that is written but not in issueFields would be dropped by the next Save; the store
    refuses it instead"""
    for name in ['title', 'releaseNotes', 'workingRemarks', 'effort', 'planStep', 'duplicateOf',
                 'resolvedInVersion', 'component', 'resolvedCommit']:
        assert name in tracker.issueStore.issueFields, name

    with pytest.raises(ValueError):
        tracker.issueStore.CleanIssue({'number': 1, 'notes': 'the field of the old format'})


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#the version arithmetic (revision2026 step R8.3). These two functions are the ONLY definition of
#what version.txt says - the micro number is the count of closed issues - and nothing covered them.

def testTheMicroVersionIsTheCountOfClosedIssues(tracker):
    """what GetMajorMinorMicroVersion returns has to be what the file contains"""
    closed = len([issue for issue in tracker.GetIssues()
                  if issue['status'].strip() in tracker.closedStatuses])
    [major, minor, micro] = tracker.GetMajorMinorMicroVersion()

    assert major == 1
    assert minor == len(tracker.versionResolved) - 2
    assert micro == closed - tracker.versionResolved[-1]


def testResolvingMovesTheVersionByOne(tracker):
    """the one property the whole scheme rests on; it is also why a closed-not-resolved issue
    still counts (see the note on closedStatuses)"""
    before = tracker.GetMajorMinorMicroVersion()
    tracker.ResolveIssue(OpenIssueNumber(tracker), notes='done', author='Claude-JG')
    after = tracker.GetMajorMinorMicroVersion()

    assert after[2] == before[2] + 1 and after[:2] == before[:2]


def testAbandoningCountsLikeResolving(tracker):
    before = tracker.GetMajorMinorMicroVersion()
    tracker.AbandonIssue(OpenIssueNumber(tracker), reason='decided against', author='Claude-JG')
    after = tracker.GetMajorMinorMicroVersion()

    assert after[2] == before[2] + 1


def testResolvedIssues2VersionOnAndBetweenTheBaselines(tracker):
    """the release notes are grouped by what this returns, so its boundaries matter: a count
    exactly ON a minor baseline belongs to that minor version with micro 0"""
    baselines = tracker.versionResolved
    total = baselines[-1] + 10                      #ten issues into the current minor version

    #ten issues back from the total is the baseline itself: minor = the last one, micro = 0
    assert tracker.ResolvedIssues2Version(10, total) == [len(baselines) - 2, 0]
    #the newest issue is the highest micro of the current minor version
    assert tracker.ResolvedIssues2Version(0, total) == [len(baselines) - 2, 10]
    #one below the baseline is the PREVIOUS minor version, at its highest micro
    [minor, micro] = tracker.ResolvedIssues2Version(11, total)
    assert minor == len(baselines) - 3
    assert micro == baselines[-1] - 1 - baselines[-2]


def testVersionStringFollowsTheBuildMode(tracker, monkeypatch):
    """fact 26: the .dev1 suffix decides what setup.py builds and whether pip would take it"""
    [major, minor, micro] = tracker.GetMajorMinorMicroVersion()
    plain = str(major) + '.' + str(minor) + '.' + str(micro)

    monkeypatch.setattr(tracker, 'versionDev', '')
    assert tracker.VersionString() == plain

    monkeypatch.setattr(tracker, 'versionDev', '.dev1')
    assert tracker.VersionString() == plain + '.dev1'


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#the command line: exudev issue <verb> (revision2026 step R8.3)

def ExudevCommands():
    """tools/exudev/commands.py, loaded by path like the tracker above - a plain "import commands"
    would read as a dependency on the PyPI package of that name (tools/checkExtras.py says so)"""
    exudevDirectory = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                    '..', '..', 'tools', 'exudev'))
    if exudevDirectory not in sys.path:
        sys.path.insert(0, exudevDirectory)      #commands.py imports runner from there
    specification = importlib.util.spec_from_file_location(
        'exudevCommandsUnderTest', os.path.join(exudevDirectory, 'commands.py'))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def IssueOptions(**fields):
    """the options object the parser would build"""
    class Options:
        pass
    options = Options()
    for (name, value) in fields.items():
        setattr(options, name, value)
    return options


def testEveryWritingVerbIsAStepWithAnActionAndANote():
    """--dry-run must be able to print what a verb would do WITHOUT doing it; that is only true
    if the work sits in the step's action and the note describes it"""
    commands = ExudevCommands()
    verbs = [IssueOptions(issueVerb='extend', number=1, text='t', author='JG'),
             IssueOptions(issueVerb='remark', number=1, text='t', author='JG', replace=False),
             IssueOptions(issueVerb='resolve', number=1, notes='n', author='JG'),
             IssueOptions(issueVerb='abandon', number=1, reason='r', author='JG'),
             IssueOptions(issueVerb='modify', number=1, field='effort', value='LOW'),
             IssueOptions(issueVerb='mode', release=True, dev=False)]

    for options in verbs:
        steps = commands.Issue(options)
        assert len(steps) == 1, options.issueVerb
        assert steps[0].action is not None and steps[0].note, options.issueVerb
        assert steps[0].argv is None, options.issueVerb   #nothing is run as a process


def testListFiltersByStatusTypeAndEffort(tracker, capsys):
    commands = ExudevCommands()
    options = IssueOptions(open=True, type='FIX', effort=None, priority=None, limit=0)

    commands.ListIssues(tracker, options)

    printed = capsys.readouterr().out
    expected = len([issue for issue in tracker.GetIssues()
                    if issue['status'].strip() == 'RAISED' and issue['type'].strip() == 'FIX'])
    assert str(expected) + ' of ' + str(expected) + ' matching issues' in printed


def testShowPrintsTheFieldsThatAreFilled(tracker, capsys):
    commands = ExudevCommands()
    issue = tracker.GetIssue(OpenIssueNumber(tracker))

    commands.ShowIssue(issue)

    printed = capsys.readouterr().out
    assert issue['title'].strip() in printed
    assert 'description:' in printed
    #an empty field is not printed at all - a screen full of empty labels helps nobody
    assert 'date resolved' not in printed


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#the local viewer: exudev issue serve (revision2026 step R8.5.1). The request layer of
#issueServer.py takes a method, a path, a query and a payload and returns a response, which is
#why these tests need no port, no browser and no thread.

@pytest.fixture
def server(tracker, monkeypatch):
    """the server module, pointed at the same temporary copy of the store as the tracker fixture.
    It imports issueTracker itself, and that import gives the REAL module, so the monkeypatching
    of the fixture is applied to the module the server holds."""
    specification = importlib.util.spec_from_file_location(
        'issueServerUnderTest', os.path.join(trackerDirectory, 'issueServer.py'))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    monkeypatch.setattr(module, 'issueTracker', tracker)
    monkeypatch.setattr(module, 'issueStore', tracker.issueStore)
    return module


def Call(server, method, path, data=None):
    """one request; what a GET reads as its query is what a POST sends as its payload, and the
    body comes back decoded, as JSON where the response says so"""
    (status, contentType, body) = server.HandleRequest(
        method, path, query=data if method == 'GET' else None,
        payload=data if method != 'GET' else None)
    text = body.decode('utf-8')
    return (status, json.loads(text) if 'json' in contentType else text)


def testThePageIsOneSelfContainedFile(server):
    """no framework and no request to anything outside this server: it has to work on a machine
    with no network (and a page that silently loads nothing is worse than no page)"""
    (status, page) = Call(server, 'GET', '/')
    assert status == 200
    assert '<title>Exudyn issues</title>' in page
    for outside in ['http://', 'https://', 'src=']:
        assert outside not in page, outside


def testTheListFiltersLikeTheCommandLine(server, tracker):
    """the same question as "exudev issue list --open --type FIX --effort LOW", through the page"""
    (status, data) = Call(server, 'GET', '/api/issues',
                          {'status': 'open', 'type': 'FIX', 'effort': 'LOW'})
    expected = [issue for issue in tracker.GetIssues()
                if issue['status'] == 'RAISED' and issue['type'] == 'FIX'
                and issue['effort'] == 'LOW']
    assert status == 200
    assert data['matching'] == len(expected)
    assert set(issue['number'] for issue in data['issues']) == \
           set(issue['number'] for issue in expected)


def testSearchFindsTextAndANumber(server, tracker):
    number = OpenIssueNumber(tracker)
    (status, data) = Call(server, 'GET', '/api/issues', {'status': 'all',
                                                         'search': '#' + str(number)})
    assert status == 200 and data['matching'] == 1
    assert data['issues'][0]['number'] == number

    word = tracker.GetIssue(number)['title'].split()[0]
    (status, data) = Call(server, 'GET', '/api/issues', {'status': 'all', 'search': word})
    assert number in [issue['number'] for issue in data['issues']]


def testTheListDoesNotSendTheDescriptions(server):
    """2,568 descriptions are 700 KB and the list shows none of them"""
    (status, data) = Call(server, 'GET', '/api/issues', {'status': 'all'})
    assert status == 200 and data['issues']
    assert 'description' not in data['issues'][0]
    assert len(data['issues']) <= data['limit']


def testAMissingIssueIsAMessageAndNotACrash(server):
    (status, data) = Call(server, 'GET', '/api/issue', {'number': 999999})
    assert status == 404 and 'no issue' in data['error']


def testWritingGoesThroughTheTrackerAndItsChecks(server, tracker):
    """the point of the whole module: the page calls the functions a script calls, so it cannot
    write a value the command line would refuse"""
    number = OpenIssueNumber(tracker)
    (status, data) = Call(server, 'POST', '/api/modify',
                          {'number': number, 'field': 'effort', 'value': 'ENORMOUS'})
    assert status == 400 and 'ENORMOUS' in data['error']
    assert tracker.GetIssue(number)['effort'] != 'ENORMOUS'

    (status, data) = Call(server, 'POST', '/api/modify',
                          {'number': number, 'field': 'effort', 'value': 'high'})
    assert status == 200 and data['issue']['effort'] == 'HIGH'


def testTheFieldsTheTrackerOwnsAreNotWritable(server, tracker):
    """the status moves an issue between open/ and closed/ and decides the version; it is written
    by resolve and abandon, never by a field editor"""
    number = OpenIssueNumber(tracker)
    for field in ['status', 'number', 'dateResolved', 'somethingElse']:
        (status, data) = Call(server, 'POST', '/api/modify',
                              {'number': number, 'field': field, 'value': 'RESOLVED'})
        assert status == 400, field
    assert tracker.GetIssue(number)['status'] == 'RAISED'


def testRaiseExtendRemarkAndResolveThroughTheApi(server, tracker):
    (status, data) = Call(server, 'POST', '/api/raise',
                          {'title': 'raised through the page', 'description': 'what it is about',
                           'type': 'CHECK', 'effort': 'LOW', 'author': 'Claude-JG'})
    assert status == 200
    number = data['number']
    assert data['issue']['author'] == 'Claude-JG' and data['issue']['effort'] == 'LOW'

    Call(server, 'POST', '/api/extend', {'number': number, 'text': 'and this as well'})
    Call(server, 'POST', '/api/remark', {'number': number, 'text': 'duplicate of #1'})
    issue = tracker.GetIssue(number)
    assert 'and this as well' in issue['description'] and 'what it is about' in issue['description']
    assert issue['workingRemarks'] == 'duplicate of #1'

    (status, data) = Call(server, 'POST', '/api/resolve',
                          {'number': number, 'notes': 'done', 'author': 'Claude-JG'})
    assert status == 200 and data['issue']['status'] == 'RESOLVED'
    #the remarks were useful while it was open and are not published - as everywhere else
    assert data['issue']['workingRemarks'] == '' and data['issue']['releaseNotes'] == 'done'


def testAClosedIssueIsRefusedWithTheTrackersOwnMessage(server, tracker):
    number = ClosedIssueNumber(tracker)
    (status, data) = Call(server, 'POST', '/api/extend', {'number': number, 'text': 'too late'})
    assert status == 400 and 'closed issue is not extended' in data['error']


def testOnlyThisMachineIsAnswered(server):
    """the store is the version of the package and there is no authentication; a name that
    resolves to 127.0.0.1 must not reach it either"""
    assert server.AllowedHost('127.0.0.1:8099')
    assert server.AllowedHost('localhost:8099')
    assert server.AllowedHost('[::1]:8099')
    assert not server.AllowedHost('evil.example.com')
    assert not server.AllowedHost('192.168.0.5:8099')


def testAnUnknownPathOrMethodIsAMessage(server):
    (status, data) = Call(server, 'GET', '/api/nonsense')
    assert status == 404 and 'unknown path' in data['error']
    (status, data) = Call(server, 'DELETE', '/api/issue')
    #deleting an issue stays a file operation with a commit behind it (revision2026 step R8.5.1)
    assert status == 405


def testServeIsAStepWithAnActionLikeEveryOtherVerb():
    """"exudev -n issue serve" must print what it would do and open no port"""
    commands = ExudevCommands()
    steps = commands.Issue(IssueOptions(issueVerb='serve', port=8099, noBrowser=True,
                                        author='JG'))
    assert len(steps) == 1 and steps[0].action is not None and steps[0].argv is None
    assert '8099' in steps[0].note


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#changing a CLOSED issue (maintainer 2026-09-21): raising, resolving and closing are ordinary
#work; editing a field of an issue that has been published in the release notes is not

def testAClosedIssueIsNotChangedByAccident(tracker):
    number = ClosedIssueNumber(tracker)
    before = tracker.GetIssue(number)['effort']

    with pytest.raises(ValueError) as error:
        tracker.ChangeIssue(number, 'effort', 'HUGE')
    assert 'published' in str(error.value) and '--force' in str(error.value)
    assert tracker.GetIssue(number)['effort'] == before

    #...but it IS possible, deliberately: a closed issue is not read-only, it is protected
    tracker.ChangeIssue(number, 'effort', 'HUGE', force=True)
    assert tracker.GetIssue(number)['effort'] == 'HUGE'


def testTheFieldsTheTrackerOwnsAreRefusedEvenWithForce(tracker):
    """the status decides which directory an issue lies in and with it the micro version; the
    dates say when something happened. None of them is a field edit."""
    number = OpenIssueNumber(tracker)
    for field in ['status', 'number', 'dateRaised', 'dateResolved']:
        with pytest.raises(ValueError):
            tracker.ChangeIssue(number, field, 'RESOLVED', force=True)
    assert tracker.GetIssue(number)['status'] == 'RAISED'


def testReplacingATextFieldSaysSo(tracker, capsys):
    """modify overwrites, extend and remark append - and the text somebody else wrote is gone"""
    number = OpenIssueNumber(tracker)
    previous = tracker.GetIssue(number)['description']
    tracker.ChangeIssue(number, 'description', 'something else entirely')

    printed = capsys.readouterr().out
    assert 'REPLACED' in printed and 'ExtendIssue' in printed
    assert previous.strip()[:40] in printed          #so that it can be pasted back


def testTheServerRefusesAClosedIssueTooAndCanForceIt(server, tracker):
    number = ClosedIssueNumber(tracker)
    (status, data) = Call(server, 'POST', '/api/modify',
                          {'number': number, 'field': 'effort', 'value': 'HUGE'})
    assert status == 400 and 'published' in data['error']

    (status, data) = Call(server, 'POST', '/api/modify',
                          {'number': number, 'field': 'effort', 'value': 'HUGE', 'force': True})
    assert status == 200 and data['issue']['effort'] == 'HUGE'


def testThePageAsksBeforeItForces(server):
    """the confirm() is what the maintainer sees; a page that sent force silently would be worse
    than no protection, because the command line refuses the same edit"""
    (status, page) = Call(server, 'GET', '/')
    assert 'confirm(' in page and 'PUBLISHED in the release notes' in page
    assert 'force: closed' in page
