// AUTO:  ++++++++++++++++++++++
// AUTO:  version info automatically generated by tracker; generated by Johannes Gerstmayr
// AUTO:  last modified = 2023-12-18
// AUTO:  ++++++++++++++++++++++
namespace EXUstd {
 const char* exudynVersion = "1.7.69.dev1";
}
