// AUTO:  ++++++++++++++++++++++
// AUTO:  version info automatically generated by tracker; generated by Johannes Gerstmayr
// AUTO:  last modified = 2023-01-19
// AUTO:  ++++++++++++++++++++++
namespace EXUstd {
 const char* exudynVersion = "1.5.75.dev1";
}
