// AUTO:  ++++++++++++++++++++++
// AUTO:  version info automatically generated by tracker; generated by Johannes Gerstmayr
// AUTO:  last modified = 2024-02-28
// AUTO:  ++++++++++++++++++++++
namespace EXUstd {
 const char* exudynVersion = "1.7.119.dev1";
}
